/*
    (c) 2025 Microchip Technology Inc. and its subsidiaries. You may use this
    software and any derivatives exclusively with Microchip products.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION
    WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.

    MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE
    TERMS.
 */

#ifndef PFC_FRAMEWORK_SETUP_H_
#define	PFC_FRAMEWORK_SETUP_H_


/*******************************************************************************
 * @defgroup pfc_mode_settings Mode Settings
 * @brief Defines mode settings for the Totem-Pole PFC solution.
 *
 * @details This group of macros defines settings related to the operating mode
 * of the Totem-Pole PFC, including voltage configuration, midpoint balancing,
 * and start-up behavior.  These #ifdefs are typically generated by the GUI
 * configuration tool and copied to the clipboard for use in the firmware.
 */

/**
 * @def HIGH_VOLTAGE
 * @brief Selects high voltage operation.
 *
 * When defined as 1, this macro configures the system for high voltage operation.
 * If not defined or set to 0, the system operates in low voltage mode.
 *
 * @ingroup pfc_mode_settings
 */
#define HIGH_VOLTAGE 1

/**
 * @def ACTIVE_MIDPOINT_BALANCING_ENABLED
 * @brief Enables active midpoint balancing.
 *
 * When defined, this macro enables active control of the midpoint voltage
 * in the Totem-Pole PFC.
 *
 * @ingroup pfc_mode_settings
 */
#define ACTIVE_MIDPOINT_BALANCING_ENABLED

/**
 * @def AUTO_START
 * @brief Enables automatic start-up.
 *
 * When defined, this macro enables the automatic start-up sequence of the PFC.
 * sp PBV GUI is not required in this case
 * 
 * @ingroup pfc_mode_settings
 */
#undef AUTO_START

/**
 * @def CANSendID
 * @brief CAN identifier for sending messages.
 *
 * This macro defines the CAN identifier used for transmitting messages.
 *
 * @ingroup pfc_mode_settings
 */
#define CANSendID 0x202

/**
 * @def CANReceiveID
 * @brief CAN identifier for receiving messages.
 *
 * This macro defines the CAN identifier used for receiving messages.
 *
 * @ingroup pfc_mode_settings
 */
#define CANReceiveID 0x203

/* ----------------------------------------------------------------------------- */

/**
 * @defgroup pfc_test_mode_settings Test Mode Settings for PFC Firmware
 * @brief Defines test mode and debugging options for the PFC firmware.
 *
 * @details This group of macros defines various test modes and debugging
 * features for the Power Factor Correction (PFC) system.  These options
 * should be carefully managed and typically remain in their default
 * (commented out or defined) states for normal operation.
 */

/**
 * @def SINGLE_PHASE_TEST
 * @brief Enables single-phase test mode.
 *
 * This macro, when defined, configures the PFC to operate in single-phase
 * mode.  It is typically undefined for normal three-phase operation
 * and only used for specific test and measurement procedures.
 *
 * @warning This macro should only be defined under the guidance of a
 * Microchip representative.
 *
 * @ingroup pfc_test_mode_settings
 */
#undef SINGLE_PHASE_TEST

/**
 * @def VOLTAGE_LOOP
 * @brief Enables the voltage control loop.
 *
 * This macro enables the voltage control loop for the PFC. It should
 * normally be defined.  If undefined, the voltage loop is disabled,
 * which is typically only done for specific test and measurement.
 *
 * @warning  The voltage loop should only be disabled for testing
 * purposes under the guidance of a Microchip representative.
 *
 * @ingroup pfc_test_mode_settings
 */
#define VOLTAGE_LOOP

/**
 * @def DEBUG_SECONDARY_CORE
 * @brief Enables debugging of the secondary core.
 *
 * This macro, when defined, enables debugging of the secondary core.
 * Note that to fully enable debugging, project settings in the primary
 * core project must also be configured.
 * go to "properties -> secondaries" and check the "Debug" box in the "Secondary Cores" window
 *
 * @warning This macro should only be defined during development or
 * debugging and not for normal operation.
 *
 * @ingroup pfc_test_mode_settings
 */
#undef DEBUG_SECONDARY_CORE

/* ----------------------------------------------------------------------------- */
/**
 * @defgroup pfc_hardware_params Hardware-specific parameters for the PFC firmware.
 * @brief Defines hardware-specific parameters used in the PFC firmware.
 *
 * @details This group of macros contains parameters that are crucial
 * for adapting the firmware to the specific hardware configuration of the
 * Power Factor Correction (PFC) system.
 */

/**
 * @def PH1_PWM
 * @brief Index of the PWM module used for phase 1.
 *
 * This macro defines the PWM module number assigned to control the
 * first AC phase.
 *
 * @ingroup pfc_hardware_params
 */
#define PH1_PWM 1

/**
 * @def PH2_PWM
 * @brief Index of the PWM module used for phase 2.
 *
 * This macro defines the PWM module number assigned to control the
 * second AC phase.
 *
 * @ingroup pfc_hardware_params
 */
#define PH2_PWM 2

/**
 * @def PH3_PWM
 * @brief Index of the PWM module used for phase 3.
 *
 * This macro defines the PWM module number assigned to control the
 * third AC phase.
 *
 * @ingroup pfc_hardware_params
 */
#define PH3_PWM 3

/**
 * @def VAC_SENSE_GAIN_HV
 * @brief AC voltage sense gain for high voltage configuration.
 *
 * This macro defines the gain of the voltage sensing circuit when the
 * PFC is operating in a high voltage configuration. The value
 * represents the ratio between the voltage at the ADC pin and the
 * actual AC line voltage.
 *
 * @unit V/V
 *
 * @ingroup pfc_hardware_params
 */
#define VAC_SENSE_GAIN_HV (3.771e-3)

/**
 * @def VAC_SENSE_GAIN_LV
 * @brief AC voltage sense gain for low voltage configuration.
 *
 * This macro defines the gain of the voltage sensing circuit when the
 * PFC is operating in a low voltage configuration. The value
 * represents the ratio between the voltage at the ADC pin and the
 * actual AC line voltage.
 *
 * @unit V/V
 *
 * @ingroup pfc_hardware_params
 */
#define VAC_SENSE_GAIN_LV (37.585e-3)

/**
 * @def VAC_SENSE_OFS
 * @brief AC voltage sense offset.
 *
 * This macro defines the offset voltage of the AC voltage sensing
 * circuit. This offset is present at the ADC pin when the AC
 * line voltage is zero.
 * 
 * @note The AC voltage sense offset (@ref VAC_SENSE_OFS) is measured at
 * startup and removed from the AC voltage measurements in firmware.
 *
 * @unit V
 *
 * @ingroup pfc_hardware_params
 */
#define VAC_SENSE_OFS (1.65)

/**
 * @def IAC_SENSE_GAIN
 * @brief AC current sense gain.
 *
 * This macro defines the gain of the current sensing circuit.
 * The value represents the ratio between the voltage at the ADC pin and
 * the actual AC current. This gain is the same for both high- and low-voltage
 * configurations.
 *
 * @unit V/A
 *
 * @ingroup pfc_hardware_params
 */
#define IAC_SENSE_GAIN (25.0e-3)

/**
 * @def IAC_SENSE_OFS
 * @brief AC current sense offset.
 *
 * This macro defines the offset voltage of the AC current sensing circuit.
 * This offset is present at the ADC pin even when the AC current is zero.
 *
 * @note The AC current sense offset is measured at startup and removed
 * from the AC current measurements in firmware.
 *
 * @unit V
 *
 * @ingroup pfc_hardware_params
 */
#define IAC_SENSE_OFS (1.65)

/**
 * @def VBUS_SENSE_GAIN_HV
 * @brief DC bus voltage sense gain for high voltage configuration.
 *
 * This macro defines the gain of the voltage sensing circuit for the DC
 * bus voltage when the PFC is operating in a high voltage
 * configuration.
 *
 * @unit V/V
 *
 * @ingroup pfc_hardware_params
 */
#define VBUS_SENSE_GAIN_HV (3.184e-3)

/**
 * @def VBUS_SENSE_GAIN_LV
 * @brief DC bus voltage sense gain for low voltage configuration.
 *
 * This macro defines the gain of the voltage sensing circuit for the DC
 * bus voltage when the PFC is operating in a low voltage
 * configuration.
 *
 * @unit V/V
 *
 * @ingroup pfc_hardware_params
 */
#define VBUS_SENSE_GAIN_LV (31.7e-3)

/* ----------------------------------------------------------------------------- */

/**
 * @def VBUS_DEFAULT_VOLTS
 * @brief Default DC bus voltage setpoint.
 *
 * This macro defines the default value for the DC bus voltage setpoint.
 * This value can be overwritten by a user interface, such as the Power Board Visualizer GUI.
 *
 * @unit V
 */
#define VBUS_DEFAULT_VOLTS (750.0)

/**
 * @def ADC_ISR_TO_FSW_RATIO
 * @brief Ratio of ADC ISR frequency to switching frequency.
 *
 * This macro defines the ratio between the frequency at which the ADC
 * interrupt service routine (ISR) is called and the switching frequency.
 * - A value of 1 means that the ADC ISR is called every switching period.
 * - A value of 2 means that the ADC ISR is called every 2nd switching period.
 * - Other values are invalid and will cause a compile-time error.
 */
#define ADC_ISR_TO_FSW_RATIO (1)


/* ----------------------------------------------------------------------------- */
/**
 * @defgroup pfc_fault_settings Fault Settings for PFC Firmware
 * @brief Defines fault detection thresholds for the PFC firmware.
 *
 * @details This group of macros defines thresholds for various fault conditions
 * in the Power Factor Correction (PFC) system.  These thresholds are
 * used to trigger protective actions to prevent damage to the hardware.
 */

/**
 * @def FAULT_IAC_OC_AMPS
 * @brief AC input current overcurrent fault threshold.
 *
 * This macro defines the threshold for the AC input current overcurrent fault.
 * It specifies the maximum allowable instantaneous current value.
 *
 * @note This is an instantaneous value, not an RMS value.
 *
 * @unit A
 *
 * @ingroup pfc_fault_settings
 */
#define FAULT_IAC_OC_AMPS (30.0)

/**
 * @def FAULT_VBUS_OV_VOLTS
 * @brief DC bus voltage overvoltage fault threshold.
 *
 * This macro defines the threshold for the DC bus voltage overvoltage fault.
 * It specifies the maximum allowable voltage on the DC bus.
 *
 * @unit V
 *
 * @ingroup pfc_fault_settings
 */
#define FAULT_VBUS_OV_VOLTS (950.0)

/**
 * @def VBUS_MAX_LV_VOLTS
 * @brief Maximum DC bus voltage for low voltage configuration.
 *
 * This macro defines the maximum allowable DC bus voltage when the PFC is
 * operating in a low voltage configuration. Exceeding this voltage may
 * cause damage to the system.
 *
 * @unit V
 *
 * @ingroup pfc_hardware_params
 */
#define VBUS_MAX_LV_VOLTS    (95.0)

/**
 * @def VBUS_MAX_HV_VOLTS
 * @brief Maximum DC bus voltage for high voltage configuration.
 *
 * This macro defines the maximum allowable DC bus voltage when the PFC is
 * operating in a high voltage configuration. Exceeding this voltage may
 * cause damage to the system.
 *
 * @unit V
 *
 * @ingroup pfc_hardware_params
 */
#define VBUS_MAX_HV_VOLTS    (890.0)


/**
 * @def FREQ_SW_HZ
 * @brief Switching frequency of the PFC.
 *
 * This macro defines the switching frequency of the PFC. This value
 * should not be changed as it is critical for the operation of the
 * converter. Changes also need to be reflected in DCDT and MCC Melody settings!
 *
 * @unit Hz
 *
 * @ingroup pfc_hardware_params
 */
#define FREQ_SW_HZ             (100000U)

/**
 * @def DUTYCYCLE_MIN_PERCENT
 * @brief Minimum duty cycle percentage.
 *
 * This macro defines the minimum allowed duty cycle percentage for the PWM signals.
 * note that because of the symmetry of the switching scheme, the max duty cycle is 
 * always = (100 - DUTYCYCLE_MIN_PERCENT)
 *
 * @unit %
 *
 * @ingroup pfc_hardware_params
 */
#define DUTYCYCLE_MIN_PERCENT (4U)

/**
 * @def MIDPOINT_COMP_OUT_MAX_AMPS
 * @brief Defines the maximum expected output current from the Vbus midpoint balancer.
 *
 * This constant represents the maximum permissible or expected output current (in Amperes)
 * generated by the Vbus midpoint balancer. In a 3-phase Power Factor Correction (PFC)
 * system, the midpoint balancer's output current is added to the main current loop
 * reference. Its purpose is to actively ensure that the bus voltage midpoint,
 * which is established by a capacitive divider and tied to the system neutral,
 * remains precisely at half of the total DC bus voltage (Vbus/2).
 *
 * A value of 1.0 Ampere means that the operational limit or a scaling factor
 * for the midpoint balancing current, indicating the maximum correction current
 * that the balancer is designed to inject into the control loop.
 * 
 *  @unit A
 *
 * @ingroup pfc_hardware_params
 */
#define MIDPOINT_COMP_OUT_MAX_AMPS    (1.0)

/**
 * @brief Compile-time check for ADC ISR to switching frequency ratio.
 *
 * This code ensures that the `ADC_ISR_TO_FSW_RATIO` macro is set to a valid value
 * (either 1 or 2).  If it is not, a compile-time error will be generated.
 */
#if ((ADC_ISR_TO_FSW_RATIO != 1) && (ADC_ISR_TO_FSW_RATIO != 2))
#error "ADC_ISR_TO_FSW_RATIO should be set to either 1 or 2, other values are invalid"
#endif

/**
 * @brief Selects DC bus and AC voltage sense gains based on voltage configuration.
 *
 * This code block selects the appropriate gain values for the DC bus voltage
 * (`VBUS_SENSE_GAIN`) and AC voltage (`VAC_SENSE_GAIN`) sensing circuits
 * based on whether the system is operating in a high-voltage or low-voltage
 * configuration, as determined by the `HIGH_VOLTAGE` macro.
 */
#if HIGH_VOLTAGE == 1
#define VBUS_SENSE_GAIN    (VBUS_SENSE_GAIN_HV)
#define VAC_SENSE_GAIN     (VAC_SENSE_GAIN_HV)
#define VBUS_MAX_VOLTS     (VBUS_MAX_HV_VOLTS)
#else
#define VBUS_SENSE_GAIN    (VBUS_SENSE_GAIN_LV)
#define VAC_SENSE_GAIN     (VAC_SENSE_GAIN_LV)
#define VBUS_MAX_VOLTS     (VBUS_MAX_LV_VOLTS)
#endif // #if HIGH_VOLTAGE == 1

/**
 * @brief Warns about special test mode configurations.
 *
 * This code generates a compiler warning if the `SINGLE_PHASE_TEST` macro is
 * defined or the `VOLTAGE_LOOP` macro is not defined. These configurations
 * are intended for special test modes, and the user is advised to contact
 * Microchip for more details.
 */
#if defined(SINGLE_PHASE_TEST) || !defined(VOLTAGE_LOOP)
#warning "SINGLE_PHASE_TEST is defined or VOLTAGE_LOOP is not defined. These are special test mode switches, contact MCHP for more details"
#endif

#if FREQ_SW_HZ != 100000U
#error "FREQ_SW_HZ should be set to 100kHz for this hardware design. Please contact a Microchip representative if you iwh to change it for your design"
#endif 

//==============================================================================
//==============================================================================

#endif	/* PFC_FRAMEWORK_SETUP_H_ */