// bom-gen.mjs — BOM generator (§49-7/21/22, §43): reads built circuit JSON of all six boards,
// classifies every component via parts-db patterns, emits per-board BOM CSVs, per-module costed
// roll-ups at 100/1000/5000 pcs, a second-source BOM, and docs/bom-cost.md.
// UNMATCHED components are listed loudly — the BOM is not "perfect" until that list is empty.
// Run (after tsci builds): node calculations/cost/bom-gen.mjs

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { DB, skuOverrides, mechLines, biasCommon } from "./parts-db.mjs";
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const f = (x, d = 0) => Number(x.toFixed(d));

const SKUS = ["30kw", "60kw", "120kw"];
const TARGETS = { "30kw": [25000, 22000], "60kw": [42000, 36000], "120kw": [78000, 68000] };
const CAT = (mpn, desc) =>
  /SiC|MOSFET|JBS|FET 1200|650 V 4 A/.test(desc) ? "semiconductors"
    : /driver|iso |LDO|MCU|shift|ULN|flyback controller|transceiver|amplifier/.test(desc) ? "drive+control ICs"
    : /module/.test(desc) ? "bias/iso modules"
    : /choke|transformer|trim|CT /i.test(desc) ? "magnetics"
    : /µF|nF|pF|film|snap|X2|Y2|MLCC/i.test(desc) ? "capacitors"
    : /resistor|shunt|Ω|ceramic/i.test(desc) ? "resistors/shunts"
    : /relay/i.test(desc) ? "relays"
    : /MOV|fuse|TVS/i.test(desc) ? "protection"
    : /stud|header|connector|harness/i.test(desc) ? "connectors"
    : /7-seg|tactile/.test(desc) ? "HMI"
    : "misc";

const summary = {};
let anyUnmatched = false;
for (const sku of SKUS) {
  const parts = new Map();
  const unmatched = new Set();
  for (const side of ["acdc", "dcdc"]) {
    const p = join(ROOT, "dist", "boards", sku, side, "circuit.json");
    if (!existsSync(p)) { console.log(`!! missing build: ${sku}/${side} — run tsci build first`); continue; }
    const j = JSON.parse(readFileSync(p, "utf8"));
    for (const c of j.filter(e => e.type === "source_component")) {
      const name = c.name;
      if (/^NC_/.test(name)) continue;
      const rule = DB.find(r => r.m.test(name));
      if (!rule) { unmatched.add(`${side}:${name} (${c.ftype ?? "?"})`); anyUnmatched = true; continue; }
      const ov = (skuOverrides[sku] ?? {})[name] ?? {};
      const key = ov.price1k ? `${rule.mpn}@${name}` : rule.mpn;
      const rec = parts.get(key) ?? { mpn: rule.mpn, mfr: rule.mfr, desc: rule.desc + (ov.note ? ` [${ov.note}]` : ""), alt: rule.alt, qty: 0, price1k: ov.price1k ?? rule.price1k, sides: new Set(), refs: [] };
      rec.qty += ov.qtyMul ?? 1;
      rec.sides.add(side);
      if (rec.refs.length < 12) rec.refs.push(name);
      parts.set(key, rec);
    }
  }
  const rows = [...parts.values()].sort((a, b) => b.qty * b.price1k - a.qty * a.price1k);
  const csv = [["mpn", "manufacturer", "description", "second_source", "boards", "qty", "unit_100", "unit_1k", "unit_5k", "ext_1k_INR", "sample_refs"]];
  let totE = 0;
  const cats = {};
  for (const r of rows) {
    const ext = r.qty * r.price1k;
    totE += ext;
    const cat = CAT(r.mpn, r.desc);
    cats[cat] = (cats[cat] ?? 0) + ext;
    csv.push([r.mpn, r.mfr, `"${r.desc}"`, `"${r.alt}"`, [...r.sides].join("+"), r.qty, f(r.price1k * 1.35, 1), r.price1k, f(r.price1k * 0.88, 1), f(ext), r.refs.join(" ")]);
  }
  csv.push(["BIAS-XFMR-SET", "custom", `"${biasCommon.desc}"`, `"—"`, "acdc+dcdc", 2, f(biasCommon.price1k * 1.35, 0), biasCommon.price1k, f(biasCommon.price1k * 0.88, 0), 2 * biasCommon.price1k, ""]);
  totE += 2 * biasCommon.price1k;
  cats["bias/iso modules"] = (cats["bias/iso modules"] ?? 0) + 2 * biasCommon.price1k;
  let mechTot = 0;
  for (const [d, q, pr] of mechLines[sku]) { const e = q * pr; mechTot += e; csv.push([`MECH`, "—", `"${d}"`, `"—"`, "module", q, f(pr * 1.15, 0), pr, f(pr * 0.93, 0), f(e), ""]); }
  cats["mechanical/assembly"] = mechTot;
  const grand = totE + mechTot;
  csv.push(["TOTAL_ELECTRONIC", "", "", "", "", "", "", "", "", f(totE), ""]);
  csv.push(["TOTAL_MODULE_1K", "", "", "", "", "", "", "", "", f(grand), ""]);
  writeFileSync(join(ROOT, "calculations", "out", `bom-${sku}.csv`), csv.map(r => r.join(",")).join("\n") + "\n");
  const [red, stretch] = TARGETS[sku];
  summary[sku] = { grand, g100: f(totE * 1.35 + mechTot * 1.15), g5k: f(totE * 0.88 + mechTot * 0.93), red, stretch, cats, nLines: rows.length, unmatched: [...unmatched] };
  console.log(`${sku}: ${rows.length} BOM lines, electronics ₹${f(totE)}, module ₹${f(grand)} @1k (red ₹${red}) ${grand <= red ? "≤ RED ✓" : "OVER by ₹" + f(grand - red)}`);
  if (unmatched.size) console.log(`   UNMATCHED (${unmatched.size}): ${[...unmatched].slice(0, 10).join(", ")}${unmatched.size > 10 ? " …" : ""}`);
}

// docs/bom-cost.md
const md = [`# BOM & Cost Roll-up (generated by calculations/cost/bom-gen.mjs — do not hand-edit)

Basis: schematic-exact quantities from the six built boards (two-board sandwich per module, E17),
parts-db RFQ-target pricing (A7, ±25%), mechanical/assembly lines from thermal/DFM calcs.
Price breaks: 100 pc = ×1.35 electronics / ×1.15 mech; 5000 pc = ×0.88 / ×0.93 (heuristic, RFQ refines).
Full line-item CSVs: \`calculations/out/bom-{sku}.csv\` (second-source column included).
`];
for (const sku of SKUS) {
  const s = summary[sku];
  md.push(`## ${sku.toUpperCase()} — module COGS ₹${f(s.grand)} @1k (100 pc ₹${s.g100}, 5k ₹${s.g5k}) vs red-line ₹${s.red} / stretch ₹${s.stretch} → **${s.grand <= s.red ? "UNDER red-line" : `OVER red-line by ₹${f(s.grand - s.red)}`}${s.grand <= s.stretch ? ", meets stretch" : ""}**\n`);
  md.push(`| Category | ₹ @1k | share |`, `|---|---|---|`);
  const tot = s.grand;
  for (const [c, v] of Object.entries(s.cats).sort((a, b) => b[1] - a[1])) md.push(`| ${c} | ${f(v)} | ${f(100 * v / tot, 1)}% |`);
  if (s.unmatched.length) md.push(`\n**UNMATCHED PARTS (${s.unmatched.length}) — BOM incomplete:** ${s.unmatched.join(", ")}`);
  md.push("");
}
md.push(`## Red-line closure levers (R12) — quantified, owner = Phase-17 RFQ round

| Lever | Δ @30 kW | Δ @60 kW | Δ @120 kW | Condition |
|---|---|---|---|---|
| ~~Custom gate-bias transformer (E23)~~ **EXECUTED — already in totals** | 0 | 0 | 0 | done (was −₹0.2–0.9k net incl. E22 adds) |
| Magnetics RFQ at Chinese winder (choke ₹1035→800, xfmr ₹680→550) | −₹1,095 | −₹2,190 | −₹4,380 | quotes at 1k volume |
| SiC 5000-pc break (×0.88 on semis) | −₹950 | −₹1,900 | −₹3,800 | aggregate order |
| AC-DC board 4-layer (control zones only need 4) | −₹300 | −₹430 | −₹740 | layout phase confirms |
| Relay direct RFQ (Hongfa annual) | −₹500 | −₹900 | −₹1,900 | volume agreement |
| Fuse→MCB-coordinated external (charger-level absorbs) | −₹270 | −₹630 | −₹1,440 | system integrator accepts |
| 120 kW partial magnetics de-commonization (12→6 larger chokes; 12→6 dual-section xfmrs) | — | — | −₹6,100 | Phase-12 rev; breaks family p/n, keep only if 120 kW volume justifies |
| **Sum of levers** | **−₹3,695** | **−₹7,210** | **−₹20,680** | |

Red-line reachability after levers: 30 kW ≈ ₹28.2k (−₹3.2k gap), 60 kW ≈ ₹48.2k (−₹6.2k gap),
120 kW ≈ ₹83.6k (−₹5.6k gap). Closing the remainder requires combinations of: SR-variant/clamp
trade (−₹0.3–0.9k), bank-cap optimization (−₹0.3–1.2k), assembly localization (−₹0.5–1.5k),
sandwich→single-board reversal (−₹1.45k+, **conflicts with directive E17**), or red-line renegotiation.
**Stretch targets are not reachable in this architecture — standing management flag (R12).**
`);
md.push(`## Directive cost impacts (recorded)
- Two-board sandwich (E17): +1 PCB, interconnect studs/harness — ≈ +₹1,450/-module @30 kW vs single-board baseline.
- HMI (2 buttons + 2-digit display + driver parts): ≈ +₹45.
- Pre-insertion relays + K_OUT (E12, safety-mandatory): ≈ +₹800 @30 kW.
- CTs replacing shunt+iso-amp phase sensing (E18): −₹240 net @30 kW.
`);
writeFileSync(join(ROOT, "docs", "bom-cost.md"), md.join("\n") + "\n");
console.log(`\n→ docs/bom-cost.md, calculations/out/bom-*.csv${anyUnmatched ? "  (FIX UNMATCHED!)" : "  (all components matched ✓)"}`);
