// parts-db.mjs — component database + designator-pattern classifier for BOM generation.
// price1k = INR at the ~1000-module aggregate (RFQ-target basis, ±25 %); breaks are 100 pc ×1.35 and
// 5000 pc ×0.88 unless a part carries its own volume quote (`p10k`). Every entry names a second source.
// SKU-dependent parts (fuses, relays, CM chokes, magnetics, snubbers, burdens) resolve via skuOverrides.
// Ordering matters: first matching pattern wins; keep specific patterns above the catch-alls.
// `desc`, `note` and `alt` are PURCHASING TEXT — they print into the BOM pages, the line-item CSVs and
// the release schematic sheets. Write them as a specification: what the part is, its ratings, its
// acceptance rows, its second source. Never as a change log.

// The four module SKUs — every pipeline consumer iterates THIS list.
export const BUILDABLE_SKUS = ["30kw", "40kw", "50kw", "50kwa"];   // 30 kW air · 40 kW air · 50 kW liquid · 50 kW air

export const DB = [
  // --- power semiconductors
  { m: /^Q[ABC]\d+[AB]2?$/, mpn: "B3M010C075Z", mfr: "BASiC", desc: "SiC MOSFET 750 V 10 mΩ TO-247-4", price1k: 330, alt: "SiChain 750V/10mΩ (RFQ)" },
  { m: /^Q\d+[HL][23]?$/, mpn: "SG2M023120LJ", mfr: "SiChain", desc: "SiC MOSFET 1200 V 23 mΩ TO-247-4L — full-bridge LLC switch, clip-mounted; tanks.mjs sets the dies per position (1 at 30 kW, 2 at 40 / 50 kW liquid and air — Q#H2/Q#L2). RFQ ACCEPTANCE: IDM ≥ 265 A @25 °C (the 30 kW single die carries 209 A at the F.11 kill)", price1k: 390, alt: "BASiC B3M020120ZL" },
  { m: /^D[ABC]\d+[TB]$/, mpn: "SICJBS-1200-40", mfr: "SiChain", desc: "SiC JBS 1200 V 40 A-class TO-247-2, SINGLE die, 2-terminal (exact p/n at RFQ). ACCEPTANCE: IFSM ≥ 250 A (10 ms half-sine, 25 °C) — the precharge-bypass closure surge. DO NOT FIT GC4D20120D (LCSC C7435099) against this line: the manufacturer data is a TO-247-3 DUAL common-cathode die, 16.5 A/leg at Tc 135 °C, IFSM 71 A/leg — a different part in a package the drawn 2-pin land does not take. Ordering stays FROZEN until either a true 2-terminal ≥ 40 A die is selected or the position is deliberately redesigned for a dual die on a 3-pin land with sharing and surge recomputed. **PRICE RISK, NOT APPLIED:** distributor anchors for a correctly-rated single-die TO-247-2 40 A part sit far above the ₹120 @1k carried here, and 22 positions per module make this the single largest unquantified line in the BOM; RFQ round 1 closes it, and nothing else in this file assumes the ₹120 holds", price1k: 120, alt: "BASiC B3D040120H" },
  { m: /^D[ABC]\d+CM?$/, mpn: "SICJBS-1200-10", mfr: "SiChain", desc: "SiC JBS 1200 V 10 A TO-247-2 (Vienna RCD clamp; D{x}0CM is the mirrored clamp diode for the negative half-cycle, PH below DCN)", price1k: 55, alt: "CR Micro 1200V/10A" },
  { m: /^D\d+[AB][1-4](P[23])?$/, mpn: "SICJBS-1200-40", mfr: "SiChain", desc: "SiC JBS 1200 V 40 A TO-247-2 (LLC secondary bridge: 2 per position on every SKU, 3 on the 50 kW air; exact p/n at RFQ)", price1k: 120, alt: "BASiC B3D40120H" },
  { m: /^QDIS[FAB]$/, mpn: "SIC-1200-5A", mfr: "CR Micro", desc: "SiC FET 1200 V 5 A (bus discharge QDISF / bank bleeders QDISA-B). GATE SPEC for the PV-driven bleeders: Vth(max) ≤ 3.5 V, Igss ≤ 100 nA. The 6.8 MΩ load-line figure (≈5.8 V after leakage) is a 25 °C-ENDPOINT MODEL, not an all-temperature guarantee — VOM1271 Voc(typ) falls to ~5.4 V at 100 °C; declared bleed-interval local ambient ≤ 70 °C, and an EVT loaded-Vgs/discharge measurement with the exact orderable FET gates the BOM freeze", price1k: 120, alt: "BASiC small 1200V" },
  { m: /^QAUX$/, mpn: "SIC-1700-1R-G15", mfr: "Infineon CoolSiC M1 / CR Micro / BASiC", desc: "SiC FET 1700 V ~1 Ω **specified at V_GS 12–15 V** (aux flyback switch on the full bus; TO-247 likely package, footprint placeholder). The NCP1252 DRV pin CLAMPS at 15 V typ / 18 V max (datasheet Rev 9), so a part whose R_DS(on) is quoted at a 20 V gate is never fully enhanced here and is barely on at the 9 V UVLO corner — the gate-voltage the R_DS(on) is specified at is the selection criterion, not the ohms. ACCEPTANCE: R_DS(on) ≤ 1.1 Ω at V_GS = 15 V and T_j = 25 °C, V_GS(th) ≤ 4.5 V, V_GS(max) ≥ 19 V, R_G,int stated (IMBF170R1K0M1-class — CoolSiC trench M1 is a +15 V/−5 V part). No gate resistor is fitted because R_G,int is ≈ 25 Ω", price1k: 160, alt: "G3R1700 class specified at 15 V gate" },
  { m: /^DZAUX$/, mpn: "BZX84-B15", mfr: "any", desc: "15 V **±2 %** zener (aux primary-side regulation reference — VCC regulates at VZ+VBE and the aux winding tracks the rails). ±2 % is a requirement, not a preference: N15 = Naux = 4 T, so V15 tracks VCC almost exactly and inherits the whole reference tolerance. At ±2 %, VZ 14.7–15.3 V → V15 ≈ 14.6–15.4 V, inside the gate-bias modules' 13.5–16.5 V input window with margin and under the SMBJ18A standoff; a ±5 % part puts the top of V15 at 16.6 V, outside that window", price1k: 1.2, alt: "TL431 + 2-resistor divider (+₹1.4, ±1 %)" },
  { m: /^DCLA$/, mpn: "SIC-SBD-1700V", mfr: "GeneSiC/Littelfuse/Wolfspeed class", desc: "SiC Schottky ≥1700 V, IF(AV) ≥1 A, IFRM ≥10 A, no forward recovery (aux RCD clamp). The 1700 V class is the requirement: this diode blocks Vbus + Vc = 1307–1337 V at the stack-up leakage, so a 1200 V part avalanches every cycle; d4-flyback computes Vr ≤ 80 % at 860 V + limit current + 5 µH [est ₹150 @1k: 1.7 kV SiC SBD distributor class, RFQ]", price1k: 150, alt: "2× STTH112U series (only with a measured VFP allowance re-run through d4-flyback)" },
  { m: /^D\w*S[12]$/, mpn: "US1M", mfr: "Yageo/MDD", desc: "1 kV 1 A fast diode SMA (DESAT chain)", price1k: 1.2, alt: "M7/US1M any" },
  { m: /^DAUX24$/, mpn: "UF-400V-3A", mfr: "onsemi/MDD (MURS340 class)", desc: "400 V 3 A ultrafast, SMC pad (aux 24 V rectifier — PIV ≈ 176 V plus the leakage ring, which is why the class is 400 V and not a 100 V Schottky)", price1k: 5, alt: "ES3 series 400 V" },
  { m: /^DAUX(15|VC)$/, mpn: "US2G", mfr: "MDD/Yageo", desc: "400 V 2 A ultrafast SMB (aux 15 V / self-supply rectifiers — PIV ≈ 157 V plus ring)", price1k: 3, alt: "MURS240" },
  { m: /^DTVS24$/, mpn: "SMBJ28A", mfr: "any", desc: "TVS **28 V** uni SMB — V24 rail clamp for a gross feedback-open fault, not rail regulation. The 28 V standoff is the requirement: V24 runs 25–26.5 V at light load, and a standoff at or below that normal maximum leaks continuously and becomes a heater instead of a clamp. Works with the 4.7 k V24 preload (RPL24)", price1k: 3, alt: "any" },
  { m: /^DTVS15$/, mpn: "SMBJ18A", mfr: "any", desc: "TVS **18 V** uni SMB — V15 rail clamp, fault duty only. 18 V clears the ±2 % reference band (V15 upper corner 15.4 V) with room and still sits under the gate-bias modules' 16.5 V input ceiling; a 16 V standoff would sit below the rail's own upper corner and leak in normal operation", price1k: 3, alt: "any" },
  { m: /^D\d+W$/, mpn: "BAT54A", mfr: "any", desc: "dual Schottky SOT-23 common anode (F.11 window comparator diode-OR onto the FLT wire-OR)", price1k: 0.6, alt: "BAT54AW" },
  { m: /^D\w+P$/, mpn: "1N4148WS", mfr: "any", desc: "clamp diode SOD-323 (to 3V3)", price1k: 0.4, alt: "BAS316" },
  { m: /^D\w+N$/, mpn: "1N4148WS", mfr: "any", desc: "clamp diode SOD-323 (from AGND — bipolar front end)", price1k: 0.4, alt: "BAS316" },
  { m: /^(QAUXFB|QPVD)$/, mpn: "S8050", mfr: "CJ", desc: "NPN SOT-23 (QAUXFB: opto-emulating feedback pull-down · QPVD: low-side switch for the PV-driver LEDs at the guaranteed 10 mA point)", price1k: 0.4, alt: "MMBT2222" },
  { m: /^QDIG[12]$/, mpn: "S8050", mfr: "CJ", desc: "NPN SOT-23 (display digit driver)", price1k: 0.4, alt: "MMBT2222" },
  // --- gate drive, isolation & safety chain
  { m: /^U([ABC]\d+G|\d+[HL])$/, mpn: "NSI6611", mfr: "NOVOSENSE", desc: "iso gate driver 10 A, DESAT / Miller clamp (CLAMP pin wired) / UVLO, SOIC-16", price1k: 85, alt: "NSI6602B" },
  { m: /^PS(CAN|SH)$/, mpn: "ISO5V-RFC-6K", mfr: "MORNSUN QA/URB-grade", desc: "iso 15→5 V ≥1 W REINFORCED-rated module, ≥5 kVrms 1-min test. This module IS part of the mains/output→SELV barrier, so a functional-grade 1.5 kV part does not qualify however well it fits: the insulation certificate class is the §K acceptance line", price1k: 95, p10k: 65, alt: "RECOM RxxP-R / certified eq" },
  // MUST precede the /^PS5\w+$/ rule below. In "PS5AC"/"PS5BUS" the 5 means 5 VOLTS; in "PS5H" the 5
  // is the LLC LEG INDEX, and a 5 V isolated SENSE module in a gate-bias position is a different part,
  // a different symbol and a gate that cannot turn on.
  { m: /^PS\d+[HL]$/, overrides: ["ISO5V-RFC-6K"], mpn: "ISO-GBIAS-15-1W", mfr: "MORNSUN", desc: "LLC-channel isolated gate-bias module, **+15 V / −3 V**, 1 W class. Specified as a CLASS, not a catalogue code: reinforced isolated gate-bias module, DC input 13.5–16.5 V against V15 ≈ 15.0 V (inside range; cross-regulation verified at EVT), dual output **+15 V / −3…−4 V**, ≥ 5 kVrms 1-min test, C_io ≤ 5 pF. ACCEPTANCE ROW: **+15 V ±5 % at 20–100 % of rated load, ≤ +17.5 V at 5 % load** — these modules run at ≈ 17 % load, where an unregulated open-frame part rises +10…+18 % and a nominally +15 V device class arrives at the gate as 18 V. +15 V rather than +18 V because +18 V exceeds the registered second source's −4/+15 V operational limit and leaves 1 V against its +19 V transient absolute maximum, which a real gate loop's 1–3 V of overshoot crosses; the vendor short-circuit-withstand classes the DESAT budget is graded against are 15 V numbers, and 15 V cuts Q_g·ΔV by 14 % at an ~8 % higher R_DS(on) that is carried in the thermal grid. The −3 V off-bias is what the models and the DPT run. **1 W class is correct only where the channel drives ONE die (30 kW)** — the 2 W ISO-GBIAS-15-2W override lands on 40/50 kW. Whether the frozen switch finally wants +15 V or +18 V follows ITS recommended V_GS: the SG2M023120LJ has no public datasheet and 1200 V / 23 mΩ Chinese dies are specified at 18 V, so this row moves with the device freeze (open decision C-10) and not before it", price1k: 95, p10k: 55, alt: "domestic iso-module eq (2nd source at RFQ)" },
  { m: /^PS5\w+$/, mpn: "ISO5V-RFC-6K", mfr: "MORNSUN QA/URB-grade", desc: "iso 15→5 V reinforced-rated module (floating bias for the isolated sense amplifiers — AC star / DCN / BKAN / BKBN). Same barrier argument as the CAN/shunt modules: the certificate class is the acceptance line, DC-use clearance is the §K item", price1k: 95, p10k: 65, alt: "RECOM RxxP-R / certified eq" },
  { m: /^PSQD\w*$/, mpn: "ISO-GBIAS-15-1W", mfr: "MORNSUN", desc: "iso 15→15 V module ≥6 kVDC (bus-discharge driver bias; insulation certificate class is a §K line). Specified as a CLASS: reinforced isolated gate-bias module, 15 V DC in (13.5–16.5 V), dual output **+15 V / −3…−4 V**, ≥ 5 kVrms 1-min test, C_io ≤ 5 pF. ACCEPTANCE ROW: **+15 V ±5 % at 20–100 % of rated load, ≤ +17.5 V at 5 % load** — the module runs at ≈ 17 % load, where an unregulated open-frame part rises +10…+18 %. One variant serves the whole module: the TLP152 VCC range is 10–30 V and the QDISF gate is fine at 15 V", price1k: 95, p10k: 60, alt: "B1518S-3WR3HD" },
  { m: /^PS\w+$/, mpn: "ISO-GBIAS-15-1W", mfr: "MORNSUN", desc: "isolated gate-bias module **+15 V / −3 V**, 1 W class (Vienna channels: ONE common-source pair per channel at 50 kHz = 0.33 W, so the 1 W class holds). Specified as a CLASS: reinforced isolated gate-bias module, 15 V DC in (13.5–16.5 V) against V15 ≈ 15.0 V off the regulated aux, dual output **+15 V / −3…−4 V**, ≥ 5 kVrms 1-min test, C_io ≤ 5 pF. ACCEPTANCE ROW: **+15 V ±5 % at 20–100 % of rated load, ≤ +17.5 V at 5 % load** — these modules run at ≈ 17 % load, where an unregulated open-frame part rises +10…+18 %. Packaged modules are permanent at ≥10k modules/yr: at that volume module pricing ≤ ₹55 makes a custom bias transformer worth ≈ ₹0 against added EMC and manufacturing risk. Whether the frozen switch wants +15 V or +18 V follows ITS recommended V_GS (open decision C-10)", price1k: 95, p10k: 55, alt: "domestic iso-module eq (2nd source at RFQ)" },
  { m: /^USHO$/, mpn: "NSI1200-DSWR", mfr: "NOVOSENSE", desc: "iso shunt amplifier SOIC-8 (differential OUTP/OUTN both routed)", price1k: 70, alt: "AMC1200" },
  { m: /^UIVV[123]$/, mpn: "AMC1350-class", mfr: "TI/NOVOSENSE", desc: "iso voltage-sense amp ±5 V input (AC phase sense against the artificial star)", price1k: 135, alt: "NSI1300 class" },
  { m: /^UIV\w+$/, mpn: "AMC1311-class", mfr: "TI/NOVOSENSE", desc: "iso voltage-sense amp 0–2 V input (bus / bank / output senses). On the 1311 class the symbol's pin-3 'VINN' is physically SHTDN — grounded = enabled; the netlist is correct and the label is the shared iso-amp table's", price1k: 115, alt: "NSI1311 class" },
  { m: /^UCAN$/, mpn: "NSI1042-DSWR", mfr: "NOVOSENSE", desc: "iso CAN transceiver SO-16, -DSWR order suffix. Pin map (datasheet Rev 1.3 drawing and pin table agree, and the sheets carry it): VDD1=1, GND1=2/8, RXD=3, TXD=6, GND2=9/10/15, CANL=12, CANH=13, pin 11 NC", price1k: 60, alt: "NSI1050-DSWR" },
  { m: /^UQD$/, mpn: "TLP152-class", mfr: "Toshiba/eq", desc: "opto gate driver (isolated bus-discharge control, default-OFF)", price1k: 42, alt: "1ED31xx lite" },
  { m: /^UPV[AB]$/, mpn: "VOM1271T", mfr: "Vishay/eq", desc: "photovoltaic MOSFET driver with integrated turn-off (bank bleeders — no floating supply needed; the ms-class turn-on is the point)", price1k: 35, p10k: 28, alt: "TLP3906" },
  { m: /^USUP(CARD|[AB])$/, mpn: "TPS3430-class", mfr: "TI/eq", desc: "external windowed watchdog SOT-23-6: VDD/GND/WDI/WDO/SET straps (strap values per datasheet, §K)", price1k: 35, alt: "MAX6753" },
  { m: /^UAND(CARD|[AB])$/, mpn: "74HC11", mfr: "any", desc: "triple 3-input AND (gate-enable wired-AND)", price1k: 8, alt: "74LVC1G11 ×1" },
  { m: /^UEXCL$/, mpn: "74HC02", mfr: "any", desc: "quad NOR SOIC-14 — hardware S/P exclusion: KSER coil = KSER ∧ ¬(KPARA∨KPARB). Every destructive matrix state involves KSER, so the exclusion is wired in hardware and not left to firmware", price1k: 5, alt: "any" },
  { m: /^U\d+W$/, mpn: "TLV3202-class", mfr: "TI/3PEAK", desc: "dual 40 ns push-pull comparator SOIC/VSSOP-8, 2.7–5.5 V (F.11 window: trips above F11_VH and below F11_VL, diode-OR onto FLT = HRTIMER_FLT2)", price1k: 16, alt: "TS3022 / LMV7239 ×2" },
  { m: /^UAVB$/, mpn: "TLV9061-class", mfr: "TI/3PEAK", desc: "rail-to-rail op-amp (AVMID buffer)", price1k: 12, alt: "LMV321" },
  // --- control: UCARD/USUPCARD/UANDCARD/UBKCARD/LBKCARD live on the control card, so their patterns
  //     must stay card-aware — a per-board-only regex drops the MCU and its chain from the BOM.
  { m: /^U(PFC|LLC|CARD)$/, mpn: "GD32G553VET7", mfr: "GigaDevice", desc: "MCU Cortex-M33 216 MHz LQFP100 −40…105 °C. The V suffix is the 100-pin part, and GigaDevice's ordering table lists ONLY VET7 (105 °C / 216 MHz) and VET3 (125 °C / 170 MHz) — no other suffix is a valid order code at this pin count; silicon and pinout are identical across the two", price1k: 210, alt: "GD32G553VET3 (125 °C)" },
  { m: /^USR1$/, mpn: "74HC595", mfr: "any", desc: "shift register SOIC-16 (HMI segments)", price1k: 4, alt: "TPIC6C595" },
  { m: /^U(PA|LB)$/, mpn: "ULN2803A", mfr: "any", desc: "8-ch relay coil driver SOIC-18 (unused inputs grounded)", price1k: 9, alt: "TBD62083" },
  { m: /^UAUX$/, mpn: "NCP1252D", mfr: "onsemi", desc: "current-mode flyback controller, RT-set 65 kHz (66.5 kΩ, datasheet Rev 9), SOIC-8. The **D suffix is mandatory** — no pre-soft-start delay, VCC(on) 14 V with 5.0 V hysteresis and DCmax 45.6 % against the 22 % worst duty this DCM flyback needs at the 321 V brown-in. The A version carries a 120 ms pre-soft-start delay with only 1.0 V of UVLO hysteresis, and the 940 k startup feed (0.59 mA) minus ICC (1.4–2.2 mA) collapses VCC in 28–60 ms, so it hiccups forever instead of starting. Startup budget: ≈5.6 mA × 60 ms of soft-start + takeover = 336 µC → CVCC ≥ 67 µF, 220 µF fitted (3× margin; cold start ≈ 5–6 s at a 565 V precharged bus)", price1k: 24, alt: "UCC28C43 + RT/CT & BO rework" },
  { m: /^UBK(CARD|[AB])$/, mpn: "TPS54202-class", mfr: "TI/eq", desc: "15→3.3 V 2 A sync buck SOT-23-6, on the control card and exporting V3P3 over the 88-way. An LDO is thermally impossible in this position: the 11.7 V drop at the rail current has nowhere to go in a chip package", price1k: 15, alt: "MP2451/SY8113" },
  { m: /^LBK(CARD|[AB])$/, mpn: "IND-10u-3A", mfr: "any shielded", desc: "10 µH 3 A shielded power inductor (3V3 buck)", price1k: 6, alt: "any" },
  // --- magnetics (custom assemblies; costed builds from the magnetics calculations)
  { m: /^L[ABC]\d+$/, mpn: "IND-PFC-165u", mfr: "custom wind (docs/magnetics.md D1 rev B)", desc: "PFC choke 165 µH class, 3× OD79 26µ sendust (Magnetics 0077908A7 / Chang Sung KS eq, catalog AL 37 nH/T² ±8%), N=39, 9× 1.6 mm enamelled bundle, 18 mm² class; one end face gap-pad bonded to the PE web under an insulating clamp (d1-choke: 43 W and 87 °C hot-spot at the 330 VAC corner, 131 °C air-cooled as registered); Rdc ≤ 6.9 mΩ @25 °C. Round bundle, not flat-on-edge strip: a 6 mm dimension lying across the 50 kHz bore field loses the Rdc and L acceptance", price1k: 1035, alt: "POCO/DMEGC equiv core" },
  { m: /^L\d+R$/, mpn: "IND-LR-E70-30", mfr: "custom wind (D2 rev F — GAPPED FERRITE)", desc: "D2-30 rev F: EXTERNAL resonant inductor 5.00 µH ±3% on 2× E70/33/32 PC95-class (TDK former B66372A2000), N=5, litz 8000×0.05 mm (15.7 mm²) compacted single layer ≥3 mm clear of a DISTRIBUTED centre-leg gap Σ 8.3 mm PER FLUX PATH (≤1.0 mm per segment; the two core sets are parallel paths — never sum across them; acceptance is the assembled AL, and Σ re-derives from it at the winder RFQ); vacuum-impregnated, both yoke faces gap-padded to the extrusion webs, end turns potted. Carries Lr 5.6 µH − 2 × D3 cell leakage (0.252 µH, acceptance ±20 %) − 0.1 µH loop — no trim bins. Powder cores prohibited in this slot: sendust at the full 140 kHz AC swing is a loss problem, not a cost saving. Envelope gate: 30.5 W Fe + 15.1 W Cu at the 764 V-bus PSM corner, hot-spot 95 °C at 55 °C inlet; B̂ 88 mT. Cost roll-up [est, REVIEW at winder RFQ]: 2 × E70 set ₹160, litz 0.05 mm ₹2,600/kg (₹292), +10 % leads, former, insulation, gap work, labour + test → ₹965", price1k: 965, alt: "any E70-capable winder (TDG/DMEGC cores)" },
  { m: /^T\d+[AB]$/, mpn: "XFMR-LLC-CELL-2E70-30", mfr: "custom wind (D3 rev D cell)", desc: "D3-30 rev D: full-bridge LLC transformer CELL (2 per module, primaries in SERIES → n = 2 overall) — 2× E70/33/32 PC95-class on TDK B66372A2000, 6:6∥6 (S1–P–S2 with S1 ∥ S2 feeding one bank), Lm 28 µH per cell ±7% (distributed gap ground to AL), primary TIW-served litz 3850×0.063 mm (12 mm²), secondary halves Cu foil 0.10×28 mm; leakage 0.252 µH computed on the 28 mm conductor band (acceptance ±20 %), vacuum-impregnated, both yoke faces gap-padded to the webs, end turns potted. Envelope gate: Fe 31.9 W at 159 mT (500 V bank) · Cu 45.8 W at the 764 V-bus PSM corner · hot-spot 106 °C at 55 °C inlet. Cost roll-up [est, REVIEW at winder RFQ]: 2 × E70 set ₹160, TIW-served litz ₹2,210/kg (₹300), foil ₹1,050/kg (₹67), +10 % leads, former, insulation, shield, gap work, labour + test → ₹1,169", price1k: 1169, alt: "any E70-capable winder" },
  { m: /^TAUX$/, mpn: "XFMR-AUX-FLY-E", mfr: "custom wind (D4 rev E)", desc: "aux flyback transformer ETD44 PC95, 110 W class, 321–860 V input, Np38 / N24 6 / N15 4 / Naux 4, Lp 345 µH ±5 % / AL 239, P/2–S–P/2 sandwich, leakage ≤ 4 µH, primary pins 1–4 / SELV pins 5–8, reinforced primary→secondary barrier, 100 % hipot 4 kV. ETD44 (Ae 173 mm²) is the requirement, not a size preference: at the real cycle-by-cycle limit — CS filter lag plus tILIM, with the 0.28 Ω / 100 pF sense chain — it computes 71 % of Bsat at 130 °C, where an ETD39 reaches 410 mT = 113 % [est ₹230 @1k: ETD39 wind ₹185 + larger core set/former]", price1k: 230, alt: "—" },
  { m: /^CMC[12]$/, mpn: "CMC-3PH-2mH-SKU", mfr: "custom/Hongfa mag", desc: "3-phase CM choke 2 mH nanocrystalline, winding rated to the SKU line current (D7). ACCEPTANCE: L_cm ≥ 2 mH @10 kHz AND ≥ 1.0 mH @150 kHz, ≥ 80 % of it held with I_pk DM bias line-to-line, leakage 6–12 µH, A_Fe floor on the quote (L_lk,max·I_pk/(8·A_Fe) ≤ 0.6 T), ΔT ≤ 45 K on hot copper. 30 kW: qualify Schaffner RT8131-63-2M8 (63 A / 2.8 mH / 600 VAC, 3-line nanocrystalline, Digi-Key) as the catalog drop-in; the custom drawing stays the second source", price1k: 1327, alt: "Schaffner RT8131-63-2M8 @30 kW" },
  { m: /^CT[ABC]\d+$/, mpn: "ACX-1100", mfr: "Talema (Salem, India)", desc: "line CT 2500:1, 100 A, ±1%, Ø14.6 mm window, 4 kV hipot, PCB pins. Rated for a 33 Ω burden, so the 27 Ω fitted value is inside spec; quote Talema direct at volume — distributor retail is not the RFQ price. **ACCEPTANCE ROWS — this is a metering CT doing a control and a µs-trip job:** (a) amplitude error ≤ 3 % and phase ≤ 5° at **50 kHz** (the current loop rides the Vienna ripple at the carrier); (b) **step response ≤ 1 µs** to 90 % on the fitted burden (τ = L_lk/R_b is 0.7 µs at 100 µH of leakage but 13.5 µs at 2 mH — the part decides whether F.01 is a µs trip or a 10 ms one); (c) **DC tolerance ≥ 5 A of primary DC with ≤ 1 % ratio error**, or a stated low-µ core — a high-µ 1:2500 core saturates at ≈ 0.6 T with about 2 A of DC (H ≈ 25 A/m). Test three samples at Stage 5 BEFORE the PO. FALLBACK if any row fails: 2 mΩ shunt + NSI1200 per phase (+₹150–300/module) — both commercial references use shunt + isolated amplifier, and it removes the DC blindness for free", price1k: 65, alt: "ZEMCT/HCT class eq" },
  { m: /^CT\d+$/, mpn: "CT-RES-1:100-100A", mfr: "**CUSTOM (RFQ)** — NOT a Talema AS catalogue part", desc: "resonant CT 1:100, 100 A rms class, 20–250 kHz, pass-through — the tank conductor is the primary, so tank-potential insulation stays on your wire (ONE CT on the full-bridge tank; the 30 kW class current 78 A rms = 78 %). REQUIREMENT: 1:100, secondary ≥ 1.3 A rms continuous (≥0.35 mm²), MnZn ferrite, 20–250 kHz, ratio ±0.5 % at 140 kHz, phase ≤ 2° over 83–203 kHz, window ≥ the tank conductor. No catalogue AS-family part covers this: that family stops at 20–200 kHz and a 30 A primary and caps the 1:50…1:500 ratios at 15 amp-turns rms (150 mA secondary = 15 A primary), while this tank runs 78/100/120 A rms → I_sec 0.78/1.00/1.20 A, 5–8× the secondary rating. The magnetic duty is trivial (2.8 V·µs per half-cycle against 350 listed, B ≈ 0.7 mT) — the limit is secondary conductor heating and the window. First article: ratio + phase sweep 83→203 kHz on the fitted burden and a 1 h thermal run at the tank class current (T-37)", price1k: 165, alt: "2nd HF-CT winder at RFQ (no catalogue drop-in exists at this class)" },
  // --- capacitors
  { m: /^CD[TB]\d*\d$/, mpn: "ELH-470u500", mfr: "Aishi", desc: "470 µF **500 V** snap-in aluminium electrolytic, 105 °C, −40 °C category, 35 mm land (split DC link). The 500 V class is the requirement: at 500 V the worst continuous half is 435 V = 87 % and 86 % at the F.38 (430 V) / F.03 (850 V) limits, while a 450 V part runs 92 % nominal, 96 % at the 860 V OVP and 97.3–97.8 % at the F.38 boundary — above ~90 % of V_R the leakage and oxide-repair rate climb off the datasheet endurance curve. Lowering the bus instead is not available: the 830 V link is SET by the 500 V bank edge with 2.3 % of FHA gain margin (checked at Lr +5 % / Cr −5 % / Lm +7 %), so 810 V and below fail the gain, and capping LOW mode at 480 V pushes 480–500 V into HIGH with a 240–250 V bank. RFQ LINE (binding): height ≤ the drawn can, **ripple ≥ 5.2 A rms @ 100 kHz / 105 °C**, **ESR ≤ 80 mΩ @ 100 kHz**, leakage ≤ 0.5 mA per can at 85 °C/415 V graded/matched per half, endurance lot 1000 h at 438 V/105 °C on 5 samples. THE DUTY THAT LINE IS FOR: the dominant term is the **Vienna's own 50 kHz capacitor current**, not the LLC's 2·f_sw share. At 50 kHz the per-phase commutation films are 3 µF per half (1.06 Ω) against a can bank of 13–16 mΩ, so the cans take essentially all of it. Direct PWM evaluation on the firmware's own modulator (common centred carrier, min-max zero sequence) plus the LLC 2·f_sw share and the 150 Hz neutral-point term in quadrature gives **5.7 / 6.5 / 5.9 A rms per can at 400 VAC / 800 V** and **6.7 / 7.6 / 7.0 A at 340 VAC / 700 V** (30 / 40 / 50 kW, full power — V_FULL is 330 VAC, so 340 VAC is NOT a derated point). An independent switched model with its own film/ESR split reads about 0.6 × the nominal figure, so the two methods bracket the answer and this line is set from the conservative bracket. `current-coordination [DCLINK-VIENNA]` recomputes all of it every run from tanks.mjs, the committed ripple-share CSV and THIS line, and gates the nominal-line corner against it × the ≤ 70 °C ambient multiplier (1.3×). **REGISTERED EXCEEDANCE — the 340 VAC full-power corner runs 99–112 % of that allowance and is the RFQ decision, not a number to widen.** Levers, in order: force air across the bank (the ambient multiplier is worth more than any part change); a taller / larger-diameter 470–680 µF / 500 V long-life can at ≥ 6 A — note the height line above, this is a mechanical decision; +1 can per half (+₹350–400 and a board change). 5.2 A at 105 °C is at the TOP of what a 35 mm snap-in gives. **PRICE RISK, NOT APPLIED:** a long-life ≥ 4.8 A snap-in is above the ₹185 @1k carried here; RFQ round 1 closes it", price1k: 185, alt: "ChengX/Nichicon 470u/500V snap-in" },
  { m: /^CF[AB]\d+$/, mpn: "PP-2u2-630", overrides: ["MLCC-1u-0805"],   /* CFB1/CFB2 also match the driver-bias ^C\w*B[12]$ rule — this film rule must own them */ mfr: "Faratronic C3D/CBB class", desc: "2.2 µF 630 V PP film, ripple-rated (bank rectifier film: ≤ 10 A rms per part of the 30/39/49 A rms 2·fsw bridge ripple)", price1k: 45, alt: "KEMET R76 / CDE 944U" },
  { m: /^DOUT$/, mpn: "DIODE-1600V-150A-MOD", mfr: "IXYS/MacMic/Yangjie class — RFQ", desc: "output series blocking diode 1600 V 150 A, insulated-base 2-terminal module — back-feed and reverse-battery proof with no output contactor and no matched-voltage make (100 A = 67 % at 30 kW; ~1.05 V × Iout, heatsink-mounted)", price1k: 420, alt: "MacMic MDD150-16" },
  { m: /^C\d+R\d+$/, mpn: "PP-33n-1200V", mfr: "Faratronic/CDE 942C class", desc: "33 nF 1200 V PP resonant-duty film (full-bridge tank: 7/9/11 in parallel at 30/40/50 kW → ≤ 10.3 A rms per cap of the 12 A line at the 250 V-bank full-power corner; Vcr ≤ 595 V pk = 421 V rms). RFQ line (open decision O-8): published Vrms-vs-f curve ≥ 460 V @140 kHz", price1k: 68, alt: "CDE 942C20P33K" },
  { m: /^C\w+F[PN]$/, mpn: "PP-1u-600", mfr: "Faratronic", desc: "1 µF 600 V film (Vienna per-phase commutation)", price1k: 32, alt: "Songtian" },
  { m: /^CFDMP$/, mpn: "PP-2u2-1100", mfr: "Faratronic", desc: "2.2 µF 1100 V PP film — the capacitor half of the DC-link entry DAMPER, in series with RFDMP 0.33 Ω across DCP–DCN at the bridge. The series resistor is not optional: film alone takes the can current to 0.80 A but leaves a 209 V bus ring at the 764 V SER corner, where the RC gives a 37 V ring and 0.77 A. RFQ ROW: **I_rms ≥ 12 A at 400 kHz / 85 °C** — the damper branch carries 6–10 A rms whenever the bridge runs at f_max", price1k: 92, alt: "KEMET C4AQ / Songtian 2.2u 1100V" },
  { m: /^RFDMP$/, mpn: "RTF-50W-R33-TO247", mfr: "Riedon/Vishay LTO/local RTP class", desc: "0.33 Ω ≥ 50 W THICK-FILM NON-INDUCTIVE power resistor, TO-247 two-lead, clipped to the DC-DC heatsink with the dies — the resistor half of the DC-link entry damper. DUTY: 7 / 16 / 36 W worst per SKU (30 / 40 / 50 kW) whenever the bridge runs at f_max, because every f_max point puts 2·f_sw = 406 kHz on the entry-film / stud resonance the damper exists to absorb; the link deck reads 10.4 A rms = 35.6 W at the 50 kW SER250 / 764 V corner. The power is the source's, not the resistor's — 0.68 / 1.0 / 2.2 Ω dissipate the same ≈ 40 W and let the bus ring 185–206 V instead of 127 V, so 0.33 Ω is the value. Series L ≤ 100 nH including its leads: the damper is worthless on a long stub", price1k: 95, alt: "Bourns PWR247T-100-R330J · Vishay LTO100 0R33 · RTP50/RTP100 0R33" },
  { m: /^CF\d+$/, mpn: "PP-1u-1100", mfr: "Faratronic", desc: "1 µF 1100 V film (bridge commutation at the DC-DC entry; 830 V ≤ 76 % of the class). THE COUNT IS PART OF THE SPECIFICATION — boards.tsx `nEntryFilm`, 16 or 20 per SKU. A small bank puts the films on a 268–425 kHz anti-resonance with the stud loop, inside the 280–406 kHz 2·fsw band; that is a PARALLEL anti-resonance, so the two branches circulate more current than the bridge injects — 6.5–18 A rms and 10–45 W per 470 µF can against a ≈3 A / 2 W allowance, and 21–47 A rms in a box part rated 8–12 A. Sixteen parts move the resonance to ~140 kHz and hold 2.7 A (30 kW) / 4.6 A (50 kW) per film. EVT T-43 measures it: current probe on one can and one film at PAR400-full and SER250-full, plus a 10 kHz–2 MHz VNA sweep of the link looking in from the bridge", price1k: 68, alt: "Songtian" },
  { m: /^COF[12]$/, mpn: "PP-4u7-1200", mfr: "Faratronic", desc: "4.7 µF 1200 V film (output; 1000 V = 83 % of the class)", price1k: 125, alt: "—" },
  { m: /^CDMP\d$/, mpn: "X1-2u2-530", mfr: "Faratronic/Songtian", desc: "X1 2.2 µF 530 VAC, delta across the 475 VAC line-line (inter-CMC stage CX1x; with RDMPx it forms the CX2-node series-RC network that stabilises the filter against the current loop, pfc-control)", price1k: 62, alt: "Vishay 3386 X1" },
  { m: /^CX[012]\d$/, mpn: "X2-4u7-305", mfr: "Faratronic/Songtian/Jimson", desc: "X2 4.7 µF 305 VAC MKP safety film, 27.5 mm pitch — twelve caps in three STAR stages: line side CX0x, inter-CMC CX1x, converter CX2x ×2 per phase; 274 VAC per cap at 475 VAC line-line. The star X bank IS the differential-mode filter; there are no series DM chokes to fall back on", price1k: 42, alt: "any X2 305 VAC 4.7 µF class" },
  { m: /^CY[123]$/, mpn: "Y2-10n-300", mfr: "Songtian/Faratronic", desc: "Y2 **10 nF** 300 VAC, L-PE on the CONVERTER node AC1..3. 10 nF is sized for the LLC bridge as a CM source (830 V at 83–203 kHz, coupled through the DC-link studs), which costs ≈3 dB of the CM margin where the impedance matters. SAME 10 mm land if the part fits it, else the next pitch — layout re-check. ON THE RECORD: PE leakage scales with C, so one line open at 1.1 × 475 VAC with +20 % tolerance gives 1.67 mA per module and three modules on one PE conductor read 5.0 mA against the 3.5 mA line (verify-independent §G FAILS deliberately — the charger PE architecture is an open decision, not a number to widen)", price1k: 25, alt: "TDK CD series Y2 10 nF" },
  { m: /^(CY(O)?[1-6]?|CPET)$/, mpn: "Y1-4n7-440", mfr: "Songtian/Faratronic", desc: "Y1 4.7 nF 440 VAC (second CM stage on AC1M..3M, between the two CM chokes, where the trio works against 4 mH of CM inductance / output-PE / DGND-PE; DC-use clearance is open decision O-7)", price1k: 16, alt: "TDK CD series" },
  { m: /^C\d+[HL]OS\d$/, mpn: "C1206-1n-1kV-C0G", mfr: "Murata/Samsung/Walsin C0G", desc: "1 kV **C0G** 1206 LLC turn-off snubber, ONE per die, drain–source AT THE PACKAGE PINS. Value per SKU from tanks.mjs `cs`: **330 pF @30 kW** · **680 pF @40 kW** · **1 nF @50 kW L/A** (per-SKU override below). 680 pF is the 40 kW knee (k_off 5.20 nJ/(V·A), V_ds,pk 83.8 % of 1200 V, 379 ns of dead time); 1 nF rings that SKU's PAR500 corner to 91 %, and its 43.5 µH Lm gives the lowest magnetizing current of the three tanks so its ZVS dead time binds first. With C_s fitted and R_g,off = 0 Ω, k_off is 2.0 / 6.5 / 3.6 nJ/(V·A) and V_ds,pk 77 % of 1200 V, against 13–15 nJ/(V·A) and 84 % un-snubbed. Bounded ABOVE by the ZVS budget at PS150-Imax and by the L_loop–C_s ring above ~2.2 nF (4.7 nF is worse than 2.2 nF at every corner). Duty is trivial — I_rms ≈ 0.6 A, ≈11 mW, no CV²f term in ZVS — so C0G at 1 kV is about dielectric stability under bias, not power", price1k: 10, alt: "2× 1206 in parallel for the same C at half the ESL" },
  { m: /^C\w+SN$/, mpn: "C1812-330p-1k", mfr: "any MLCC", desc: "**330 pF** 1 kV C0G 1812 (Vienna RC snubber). 330 pF is the value the single-polarity clamp needs: at 100 pF the unclamped half-cycle reaches 78 % of 750 V at 30 kW, 85–89 % at 50 kW and 95 % on a 20 nH loop. It costs +6 W of CV²f across the module and buys that margin back without a second clamp stage", price1k: 9, alt: "film 630V" },
  { m: /^CCLA$/, mpn: "PP-10n-1200", mfr: "Faratronic", desc: "10 nF 1200 V film (aux RCD clamp)", price1k: 9, alt: "MLCC 1kV ×2" },
  { m: /^C[ABC]\d+CM?$/, mpn: "FILM-100n-250", mfr: "Faratronic", desc: "100 nF 250 V film (Vienna RCD clamp; C{x}0CM is the mirrored clamp cap)", price1k: 18, alt: "MLCC 250V" },
  { m: /^CAUX(24|15)$/, mpn: "EL-220u-35", mfr: "Aishi", desc: "220 µF 35 V", price1k: 4, alt: "any" },
  { m: /^CVCC$/, mpn: "EL-220u-35", mfr: "Aishi", desc: "220 µF 35 V (controller VCC cold-start reservoir — the NCP1252D needs ≥67 µF through soft-start before the aux winding takes over)", price1k: 4, alt: "any" },
  { m: /^C[ABC]\d+GBL$/, mpn: "MLCC-47p-0603", mfr: "any", desc: "47 pF 0603 C0G (DESAT blank, Vienna hard turn-on — NSI66x1A worst response 2.21 µs against the 4.2 µs short-circuit-withstand class, ≥0.8 µs blank)", price1k: 0.4, alt: "any C0G" },
  { m: /^C\d[HL]BL$/, mpn: "MLCC-18p-0603", mfr: "any", desc: "**18 pF** 0603 C0G (DESAT blank, LLC ZVS turn-on). 18 pF is bounded on both sides: the LLC positions carry TWO dies at 40/50 kW on ONE driver channel, so the soft-off term 0.6·Q_g/I_STO doubles (2 × 162 nC / 0.25 A = 778 ns) and the total response must stay inside 1.5 µs (75 % of a 2 µs withstand) — 18 pF gives 1.33 µs with two dies; below it the minimum blank falls under the 0.4 µs noise floor (10 pF sits under it, 15 pF reads 0.39 µs). The 0.47 µs minimum blank it does give makes the ZVS turn-on transient a named EVT bench check", price1k: 0.4, alt: "any C0G" },
  { m: /^C\w*B[12]$/, mpn: "MLCC-1u-0805", mfr: "any", desc: "1 µF 0805 (driver bias)", price1k: 0.8, alt: "any" },
  { m: /^C(5B\w+|SHB|CB5)$/, mpn: "MLCC-1u-0805", mfr: "any", desc: "1 µF 0805 bulk on module-fed floating rails (Bias5 / shunt-amp / CAN 5 V)", price1k: 0.8, alt: "any" },
  { m: /^CCSF$/, mpn: "MLCC-100p-0603", mfr: "any", desc: "100 pF 0603 C0G ±5 % (aux current-sense filter — 1 k ∥ 26.5 k ramp R → 96 ns lag). C0G at this value: a 470 pF X7R part lets the cycle-by-cycle limit overshoot 1.5 A at 860 V", price1k: 0.5, alt: "any C0G" },
  // 1 nF C0G AT every analogue pin of the card MCU. Twenty-two channels reach it over the 88-way — twelve
  // of them after a 0.5–1 m harness carrying a 50 kHz PWM way — and the SAR samples each for 132 ns: with
  // no local reservoir the conversion reads the line's ringing and the kick-back of the previous channel.
  // Every source already has its series element (line CT 200 Ω, iso-amp 100 Ω, NTC 10 k, dividers), so this
  // is the capacitor half of an RC that was never completed. C0G, not X7R: a sampling reservoir must not
  // have a voltage coefficient. MUST precede the /^C[A-Z0-9]+$/ catch-all.
  { m: /^CADC\d+$/, mpn: "MLCC-1n-0402-C0G", mfr: "any C0G", desc: "1 nF 0402 C0G/NP0 50 V — ADC sampling reservoir at the card's analogue pins; comparator paths F.01/F.03/F.13 see τ ≤ 0.4 µs", price1k: 0.2, alt: "any 0402 C0G 1 nF" },
  { m: /^C[A-Z0-9]+$/, mpn: "MLCC-small", mfr: "any", desc: "filter/decoupling MLCC 0402–0805", price1k: 0.5, alt: "any" },
  // --- resistors (power/pulse/precision first, catch-all last)
  { m: /^RPRE[12]$/, mpn: "CER-25W-33R-AX", mfr: "TE/local", desc: "33 Ω 25 W ceramic pulse resistor, axial (AC precharge; the ohms are IN the order code — a class-only p/n lets purchasing buy any value. Pulse energy scales ×3.6 across the SKUs, so the 50 W variant lands per SKU below; T-05). RFQ ROW: **flameproof and FAIL-OPEN under sustained overload** (UL 1412 / IEC 60115 flammability) — a shorted link or a failed-short Vienna pair at switch-on puts 4.8 kW (400 VAC) to 8.4 kW (530 VAC) on each resistor and NOTHING in the module can disconnect it, because the only relays across it are the bypass; the part fusing open without flame IS the protection. The vendor single-pulse energy curve at 0.4 s must cover 235 J (50 kW) / 180 J (30/40 kW) × 3 starts", price1k: 28, alt: "SQP25 33R" },
  { m: /^RDIS\d$/, mpn: "CER-25W-160R-AX", mfr: "TE/local", desc: "160 Ω 25 W ceramic pulse resistor, axial (bus discharge string, 4× in series; value-carrying order code, 50 W variant per SKU below; T-05)", price1k: 28, alt: "SQP25 160R" },
  { m: /^RBD[AB]\d$/, mpn: "CER-2k2-10W-AX", mfr: "TE/local", desc: "2.2 kΩ 10 W wirewound axial (bank bleeder chain; ≤65 J/pulse, τ 4–17 s to <60 V)", price1k: 14, alt: "SQP10" },
  { m: /^RDMP\d$/, mpn: "SQP-6R8-25W", mfr: "local", desc: "6.8 Ω 25 W wirewound pulse, axial, series L ≤ 10 µH (input-filter Rd–Cd damper RDMPx at 30 / 40 kW; ≤ 4.6 W = 18 % of the class)", price1k: 16, alt: "any" },
  // DC-link balance: ONE string per half per MODULE (cells.tsx `bal`, boards pass bal={k===0}) — 4 elements
  // on every SKU. F.06 / F.38 watch the midpoint in every energised state and the Vienna balances it
  // actively whenever it runs, so the string only has to cover the leakage imbalance the RFQ line allows.
  { m: /^RBAL[TB]\w*$/, mpn: "R2512-47k-HV-AS", mfr: "KOA/UniOhm", desc: "**47 kOhm** 2512 2 W anti-surge HV, Umax >= 250 V, 2-series per half, ONE string per half per module. 4.4 mA of bleed against a realistic hot can-to-can leakage imbalance of ≤ ~1.2 mA (the RFQ line ≤ 0.5 mA/can at 85 °C/415 V, graded per half) = ≤ 56 V of midpoint offset with both stages off, on a link sitting at the rectified crest; 0.92 W per element at 830 V (46 % of the 2 W part, 208 V per element), 3.7 W per module on EVERY SKU", price1k: 3.2, alt: "any HV anti-surge" },
  { m: /^RNS[123][AB]$/, mpn: "R2512-33k-HV-AS", mfr: "KOA/UniOhm", desc: "33 kOhm 2512 2 W anti-surge HV, Umax >= 250 V, 2-series per position (artificial-star network; it is also THE X-cap bleed path, which is what sets the value: across three X stages 33 k brings the terminals below 60 V in ≈ 3.7 s (30/40 kW) / 4.5 s (50 kW), inside the 5 s line for permanently connected equipment). 0.57 W per element at 475 VAC (29 % of the 2 W part), +0.7 W per module standing at 400 VAC", price1k: 3.2, alt: "any HV anti-surge" },
  // Passive OUTPUT bleeder behind DOUT — three 150 k in series across OUTP–OUTN. The blocking diode is in
  // every commanded discharge path, so without this string COF1/2 (9.4 µF) hold 4.7 J on the studs behind
  // only the 3.8 MΩ sense divider. MUST precede the generic /^R[A-Z0-9]+$/ rule.
  { m: /^RBO\d$/, mpn: "R2512-150k-HV", mfr: "KOA/UniOhm", desc: "150 kOhm 1 % 2512 HV, Umax >= 400 V, 3-series across the OUTPUT studs (passive output bleeder behind DOUT): 450 kΩ total → τ 4.2 s on COF1+COF2, < 60 V in ≈ 12 s from 1000 V and ≈ 9 s from 500 V; 0.74 W and 333 V per element at 1000 V out, 2.2 W per module only while delivering at 1000 V (−0.007 % η)", price1k: 3, alt: "any HV anti-surge 2512, 3-series" },
  { m: /^R\w*SN$/, mpn: "R2512-10R-3W-PULSE", mfr: "any", desc: "10 Ω 2512 **3 W pulse-proof** (Vienna RC snubber). The 3 W class is the requirement: with C_SN 330 pF the snubber dissipates C·V²·f = 2.84 W per phase at the 750 V-class swing and 50 kHz, which is 142 % of a 2 W chip", price1k: 8, alt: "2× R2512-20R-2W in parallel on the same land" },
  { m: /^RCLA[123]$/, mpn: "R2512-11k-2W-AS", mfr: "KOA/UniOhm", desc: "11 kΩ 1 % 2512 2 W anti-surge, ≥200 V working (aux RCD clamp, 3-series = 33 k; ≤0.94 W/part at full load and 5 µH of leakage, ≤158 V/part at the 860 V limit-current event) [est ₹4 @1k, same family as R2512-47k-HV-AS]", price1k: 4, alt: "any 2 W anti-surge 2512" },
  { m: /^R(AUXST[12]|BR1[AB])$/, mpn: "R2512-HV", mfr: "UniOhm", desc: "2512 HV-rated 1 %, **limiting element voltage ≥ 500 V** (aux startup 2×470 k / brown-out 2×1.2 M, 2-series per 860 V). The working voltage is the specification, not the value: a standard 2512 thick-film is rated 200 V and these strings put ≈ 415–430 V on EACH element at the 830–860 V link, so the order line must name an HV family (RV2512 / CRCW-HV / PS-class, U_max ≥ 500 V) or the string goes to three elements", price1k: 2.5, alt: "3-series standard 2512 (same total R, 277–287 V per element)" },
  { m: /^RPL24$/, mpn: "R2512-4k7-1W", mfr: "any", desc: "4.7 kΩ 1 W 2512 V24 PRELOAD, 5.1 mA / 0.12 W. Fitted because the normal standby state — every relay de-energised, fans off — otherwise leaves V24 with NO minimum load, peak-charging to ≈25–26.5 V against a 26.4 V HF167F coil maximum and 26.4 V-class 24 V fans", price1k: 1, alt: "2× 0805 in series" },
  { m: /^X(CARD|[AB])$/, mpn: "XTAL-8M-30PPM-3225", mfr: "any", desc: "8 MHz ±30 ppm SMD crystal, 3.2 × 2.5 mm, CL 12 pF, on MCU pins 12/13 with a ground guard under the can; firmware sets PORT_HXTAL_HZ = 8 MHz. An external crystal is required, not preferred: the module's only external interface is isolated CAN, classic CAN needs the SUM of both nodes' clock errors inside the resynchronisation jump width (≤0.5 %/node in practice, ±1.58 % absolute worst case), and the GD32 internal RC is ±2–3 % over −40…+105 °C — 5× the ISO 11898-1 budget at 16 tq / SJW 2", price1k: 9, alt: "HC-49SMD 8 MHz ±30 ppm" },
  { m: /^TPWDI\w*$/, mpn: "TP-1mm-PAD", mfr: "—", desc: "1 mm test pad on WDI — the ATE fixture kicks the watchdog through it while the WDO→NRST link (RWDOL) is lifted for blank-chip SWD programming; a process note on the fab drawing, not a purchased part", price1k: 0.2, alt: "probe-only pad, no part" },
  { m: /^RAUX24$/, mpn: "R2512-R05-1W-1%", mfr: "any current-sense", desc: "50 mΩ 1 % 1 W 2512 in the V24 distribution after CAUX24: it holds a V24 hard-short loop ≥100 mΩ so the NCP1252D min-on-time ratchet stays ≤80 % of Bsat (130 °C) for the 10–20 ms before the fault latch; 0.29 W at 2.4 A [est ₹3 @1k]", price1k: 3, alt: "any 2512 CS 1 W" },
  // Card-interface rescues — MUST precede the two catch-alls below them. RFLTC (4.7 k FLT pull-up) and
  // RAGTC (0 Ω ground tie) would otherwise match the clamp-bleeder rule and be bought as 470 Ω 10 W
  // wirewounds; RPD0..4 (10 k card-way pull-downs) would match the HV-divider rule and be bought as 475 k.
  { m: /^R(FLTC|AGTC)$/, mpn: "R-small", mfr: "any", desc: "card FLT wired-OR pull-up 4.7 k 0603 / AGND–DGND 0 Ω 0805 single-point tie", price1k: 0.4, alt: "any" },
  { m: /^RPDB?[0-9]$/, mpn: "R0603-10k", mfr: "any", desc: "10 kΩ 0603 card-interface pull-down (board-side default-OFF on the GATE_EN/EN/DO ways — CARD_RULES)", price1k: 0.3, alt: "any" },
  { m: /^R[ABC]\d+CM$/, mpn: "WW-470R-10W", mfr: "local/TE", desc: "470 Ω 10 W wirewound axial — the MIRRORED Vienna clamp bleeder. The drawn clamp is single-polarity (PH → D{x}0C → C{x}0C → DCP), so without the mirror the negative half-cycle, where PH swings below DCN, is unclamped: the DPT at the real currents reads 81–92 % of 750 V on a 10 nH loop against 71–78 % clamped. The LAND is on every phase of every board; POPULATED on 50 kW liquid and 50 kW air only (82 % unclamped at the 5 nH loop), DNP on 30/40 kW which read 76–79 %. ₹157 per phase fitted = ₹471/module (diode ₹55 + film ₹18 + bleeder ₹22, ×3 phases at the 1k basis); T-59 measures both the loop and the overshoot", price1k: 22, alt: "SQP10" },
  { m: /^R\w+C$/, mpn: "WW-470R-10W", mfr: "local/TE", desc: "470 Ω 10 W wirewound axial (Vienna clamp bleeder; 4.3 W worst case = 43 % of rating)", price1k: 22, alt: "SQP10" },
  { m: /^R\w+D[0-7]$/, mpn: "HV73-475k-1%", mfr: "KOA/UniOhm", desc: "475 kΩ 1206 1% anti-surge (HV divider)", price1k: 1.4, alt: "any anti-surge 1%" },
  { m: /^R\w{2}DL$/, mpn: "R0805-prec-0.1%", mfr: "UniOhm", desc: "divider bottom 0.1% (6.8 k unipolar / 11.5 k AC)", price1k: 2.5, alt: "any 0.1%" },
  { m: /^RAUXCS$/, mpn: "R1206-R28-1%-0.5W", mfr: "any current-sense", desc: "0.28 Ω 1% 0.5 W 1206 current-sense (aux cycle-by-cycle limit — with CCSF 100 pF the worst comparator margin at full load is 8 % and the limit flux 71 % of Bsat at 130 °C; 0.19 W worst)", price1k: 2.5, alt: "any CS 1206" },
  { m: /^RPVL[AB]$/, mpn: "R2010-1k-0.75W-1%", mfr: "any thick-film", desc: "1 kΩ 0.75 W 2010, PV-driver LED feed (≥10 mA at the guaranteed spec point, held down to the 13.5 V rail floor; 0.24 W worst = 31 %)", price1k: 1.2, alt: "2× 510R 1206 series" },
  { m: /^RG([ABC]\d+[AB]|\d+[HL])[123]$/, mpn: "R0805-2R2", mfr: "any thick-film", desc: "per-device series gate R — one on EVERY die including the original device, never a shared node. LLC paralleled positions 2.2 Ω; the Vienna common-source pair takes **1 Ω per die**, because two 5–6 nF C_iss gates tied together through package lead inductance are an undamped 50–200 MHz loop that no single-device simulation shows. +₹1.2/module", price1k: 0.5, alt: "any" },
  // 100 Ω in series with every isolated-amplifier OUTPUT — the card carries 1 nF at each analogue pin
  // (CADC*), and an iso-amp output must not drive that reservoir bare. 100 Ω · 1 nF = 0.1 µs, invisible to
  // every loop and to the 23 kHz trip channels. MUST precede /^R\w+(ON|OFF)$/, which would otherwise class
  // RSHON as a 1206 GATE resistor because it ends in "ON".
  { m: /^(R(V[123]|BP|BM|OA|OB|OV)O|RSHO[PN])$/, mpn: "R-small", mfr: "any", desc: "100 Ω 0603 1 % series isolation between an isolated-amplifier output and its ADC line (the resistor half of the RC whose 1 nF sits at the card pin)", price1k: 0.4, alt: "any" },
  { m: /^R\w+(ON|OFF)$/, mpn: "R1206-RG-0.5W", mfr: "any thick-film HP", desc: "gate resistor 1206, 0.5 W-rated (LLC R_on 4.7 Ω dissipates ~0.2 W at 140 kHz, so a standard 0.25 W part runs 80 %). The LLC **R_off is 0 Ω** — OUTL straight to the gate, driver R_OL 0.3 Ω — which is only correct WITH the per-die C_s fitted: together they give 69/76/77 % peak V_ds and −5.4 V of gate undershoot, where 0 Ω alone gives 77 % and −5.6…−6.7 V against a −8 V transient maximum. The 1206 land is kept so a bench re-fit can put the resistor back. Vienna keeps 4.7/4.7 Ω", price1k: 2, alt: "2× 0805 parallel" },
  { m: /^R\w+GS$/, mpn: "R0805-10k", mfr: "any", desc: "10 kΩ gate-source", price1k: 0.5, alt: "any" },
  { m: /^R\d+CT$/, mpn: "R2512-0R47-1W-1%", mfr: "any", desc: "0.47 Ω 1% 1 W 2512 resonant-CT burden (full bridge: F.11 140 A pk = 0.66 V above AVMID; observable to 345 A, past the 328 A monitor peak 3 µs after an internal short; 78 A rms class → 0.29 W)", price1k: 4.1, alt: "2× 1206 0R91 parallel" },
  { m: /^R[ABC]\d+B$/, mpn: "R1206-22R-1%", mfr: "any", desc: "22 Ω line-CT burden 1% (F.01 120 A pk = 2.71 V; observable to 184 A through the D1 soft-saturation 3 µs race; 55 A rms → 0.48 V rms metering)", price1k: 1.2, alt: "any" },
  { m: /^RSH?O$/, mpn: "SHUNT-50MV-100A", mfr: "Isabellenhütte-eq/local", desc: "manganin shunt, 50 mV at rated current, Kelvin 4-terminal — the value follows the order code per SKU: 0.500 / 0.376 / 0.299 mΩ at the 100 / 133 / 167 A codes", price1k: 120, alt: "local manganin" },
  { m: /^RSEG\d$/, mpn: "R0603-220", mfr: "any", desc: "220 Ω segment", price1k: 0.3, alt: "any" },
  { m: /^R[A-Z0-9]+$/, mpn: "R-small", mfr: "any", desc: "small-signal resistor 0402–0805 (pulls/filters/feedback)", price1k: 0.4, alt: "any" },
  // --- ferrites
  { m: /^FB\w+$/, mpn: "FB-600R-0805", mfr: "any", desc: "ferrite bead 600 Ω@100 MHz (VDDA feed)", price1k: 0.8, alt: "any" },
  // --- electromech / connectors / HMI / protection
  { m: /^KPRE[12]$/, mpn: "HF167F-80A-M", mfr: "Hongfa", desc: "power relay ≥80 A/line with a mirror contact — the precharge bypass carries full line current (SKU class via override). §K line: contact-gap withstand and insulation group at the 475 VAC system plus the ~660 V pk precharge transient", price1k: 260, alt: "TE T9G / contactor option" },
  { m: /^K(SER|PARA|PARB)$/, mpn: "RELAY-PCB-120A-24V", mfr: "Hongfa HF161F / Churod CHC-D120 class", desc: "PCB power relay 120 A, 24 V coil, no mirror contact (S/P matrix, switched at ZERO current — modes change in standby with the LLC stopped; open-contact dielectric ≥ 2.5 kV holds the ≤ 500 V bank; SER 60/80 A, per-bank PAR ≤ 50/67 A at 30/40 kW)", price1k: 220, alt: "Churod CHC-D120" },
  { m: /^MOVP?[123]$/, mpn: "S20K550", mfr: "TDK/Songtian", desc: "MOV 550 VAC 20 mm (Δ line-line, and in series with the GDT to PE)", price1k: 22, alt: "Songtian eq" },
  { m: /^GDT[123]$/, mpn: "GDT-2k5-20kA", mfr: "Bourns/eq", desc: "gas discharge tube **2.5 kV** (L-PE surge path). The 2.5 kV class is the requirement: the MOV+GDT series path only conducts when BOTH devices do, and a 3.5 kV GDT sparks over at 4.5–5 kV at a 1 kV/µs rate of rise — with the S20K550 clamping at ≈1.45 kV that is 5–6.5 kV of let-through, above the 4 kV OVC III impulse the insulation-coordination table assumes the L-PE barrier survives, so at 4 kV the path is simply open. At 2.5 kV: impulse sparkover ≈3.2–3.7 kV, total let-through ≈4.6 kV, and the 550 VAC MOV in series still blocks mains follow current", price1k: 18, alt: "Littelfuse CG3 2.5 kV" },
  { m: /^F[123]$/, mpn: "FUSE-gG-690V", mfr: "local/Bussmann", desc: "gG fuse 690 VAC, 22×58 frame (rating per SKU, 80 A @30 kW). The holder must be the matching 22×58 base — a 10×38 RT28-32 base does not take this element at any SKU current", price1k: 105, alt: "SIBA" },
  // A connector PAIR is two different parts: one p/n on all three refs buys three headers that do not mate.
  { m: /^J[AB]$/, mpn: "CONN-CARD-88-H", mfr: "any 2×44 0.1in", desc: "88-way 2×44 2.54 mm card interface, PIN HEADER side (power board), keyed", price1k: 45, alt: "Samtec TSW-144-xx-x-D class" },
  { m: /^JCARD$/, mpn: "CONN-CARD-88-R", mfr: "any 2×44 0.1in", desc: "88-way 2×44 2.54 mm card interface, RECEPTACLE side (card), keyed, mates CONN-CARD-88-H", price1k: 75, alt: "Samtec SSW-144-xx-x-D class" },
  { m: /^DISP1$/, mpn: "LED-2DIG-0.56CC", mfr: "any", desc: "2-digit 7-seg 0.56\" common-cathode (HMI)", price1k: 18, alt: "any" },
  { m: /^SW[12]$/, mpn: "TACT-6x6", mfr: "any", desc: "tactile switch 6×6 (HMI; pinout pairing verified at BOM freeze against the chosen series)", price1k: 3, alt: "any" },
  { m: /^JSWD\w+$/, mpn: "HDR-1x5-2.54", mfr: "any", desc: "SWD/boot header (end-of-line programming; LV-only test state, §45)", price1k: 8, alt: "TC2030 pads" },
  { m: /^J(ACL\d|PE|PEB|DCP|DCN|OUTP|OUTN|QDIS)?$/, mpn: "STUD-M8", mfr: "local", desc: "M8 stud terminal", price1k: 28, alt: "M6 for signal PE" },
  { m: /^JIC[AB]$/, mpn: "MICROFIT3-40", mfr: "Molex 43045-40 class (2x20)", desc: "40-way inter-board harness header, 5 A/contact — the PFC bundle crosses here: PWM x3, 12 senses, AVMID+Kelvin, fans, precharge, EN/GATE_EN_A/FLT/DRV_RDY, V15/V24, 5 returns, shield", price1k: 72, alt: "JST VL / TE MicroMate 40" },
  { m: /^JCAN$/, mpn: "PH-4", mfr: "JST", desc: "CAN connector 4-way", price1k: 8, alt: "any" },
  { m: /^JFAN[1-4]$/, mpn: "PH-4-FAN", mfr: "JST", desc: "fan header 4-way (the fan p/n must accept 3.3 V PWM)", price1k: 6, alt: "any" },
  { m: /^J(TERM|T\w+)$/, mpn: "PH-2", mfr: "JST", desc: "2-way header (NTC/term)", price1k: 3, alt: "any" },
  { m: /^LCAN$/, mpn: "CMC-CAN-51uH", mfr: "any", desc: "CAN common-mode choke", price1k: 8, alt: "any" },
  { m: /^TVSCAN$/, mpn: "PESD1CAN", mfr: "Nexperia/eq", desc: "CAN TVS", price1k: 4, alt: "any" },
  { m: /^QDIS$/, mpn: "TAB-M4", mfr: "local", desc: "discharge FET heatsink tab stud", price1k: 6, alt: "—" },
];

// per-SKU overrides: name → { price1k, qtyMul, note }
export const skuOverrides = {
  "30kw": {
    QA0A: { price1k: 180, desc: "SiC MOSFET 750 V 20 mΩ class TO-247-4 (Vienna common-source pair, one die per position)", mpn: "SIC-750V-20mR", note: "750 V 20 mΩ class, single die per position, clip-mounted (grid T_j 112 °C) — RFQ target; ACCEPTANCE IDM ≥ 210 A @25 °C (165 A F.01 fault peak)" },
    QA0B: { price1k: 180, desc: "SiC MOSFET 750 V 20 mΩ class TO-247-4 (Vienna common-source pair, one die per position)", mpn: "SIC-750V-20mR", note: "750 V 20 mΩ class, single die per position, clip-mounted (grid T_j 112 °C) — RFQ target; ACCEPTANCE IDM ≥ 210 A @25 °C (165 A F.01 fault peak)" },
    QB0A: { price1k: 180, desc: "SiC MOSFET 750 V 20 mΩ class TO-247-4 (Vienna common-source pair, one die per position)", mpn: "SIC-750V-20mR", note: "750 V 20 mΩ class, single die per position, clip-mounted (grid T_j 112 °C) — RFQ target; ACCEPTANCE IDM ≥ 210 A @25 °C (165 A F.01 fault peak)" },
    QB0B: { price1k: 180, desc: "SiC MOSFET 750 V 20 mΩ class TO-247-4 (Vienna common-source pair, one die per position)", mpn: "SIC-750V-20mR", note: "750 V 20 mΩ class, single die per position, clip-mounted (grid T_j 112 °C) — RFQ target; ACCEPTANCE IDM ≥ 210 A @25 °C (165 A F.01 fault peak)" },
    QC0A: { price1k: 180, desc: "SiC MOSFET 750 V 20 mΩ class TO-247-4 (Vienna common-source pair, one die per position)", mpn: "SIC-750V-20mR", note: "750 V 20 mΩ class, single die per position, clip-mounted (grid T_j 112 °C) — RFQ target; ACCEPTANCE IDM ≥ 210 A @25 °C (165 A F.01 fault peak)" },
    QC0B: { price1k: 180, desc: "SiC MOSFET 750 V 20 mΩ class TO-247-4 (Vienna common-source pair, one die per position)", mpn: "SIC-750V-20mR", note: "750 V 20 mΩ class, single die per position, clip-mounted (grid T_j 112 °C) — RFQ target; ACCEPTANCE IDM ≥ 210 A @25 °C (165 A F.01 fault peak)" },
    // 80 A gG in a 22×58 frame with the matching holder: 55.9 A worst continuous is 88 % of a 63 A
    // element before the ~0.72× enclosed/+55 °C derate, and negative after it.
    "F1": { price1k: 105, mpn: "FUSE-gG-690V-80A", desc: "gG fuse 80 A 690 VAC, 22×58 frame (30 kW AC input, 55.9 A worst continuous). The holder must be the matching 22×58 base" }, "F2": { price1k: 105, mpn: "FUSE-gG-690V-80A", desc: "gG fuse 80 A 690 VAC, 22×58 frame (30 kW AC input, 55.9 A worst continuous). The holder must be the matching 22×58 base" }, "F3": { price1k: 105, mpn: "FUSE-gG-690V-80A", desc: "gG fuse 80 A 690 VAC, 22×58 frame (30 kW AC input, 55.9 A worst continuous). The holder must be the matching 22×58 base" },
    KPRE1: { price1k: 260, note: "80 A class (55 A line) · make ≥ 260 A pk at bypass closure, ≤ 70 V across the contacts, ≥ 30 000 makes" , mpn: "HF167F-80A-M"}, KPRE2: { price1k: 260 , mpn: "HF167F-80A-M"},
    CMC1: { price1k: 1327, note: "D7-30 rev B: T 80/50/25, A_Fe ≥ 281 mm², 3×8 T 20 mm², 9.9 W, ΔT 20 K — second source to the Schaffner catalog part [est roll-up]" }, CMC2: { price1k: 1327 },
    RSHO: { price1k: 120 },
    // 30 kW keeps ONE die per LLC position, so it has four snubbers. The value is 330 pF (tanks.mjs cs,
    // llc.c c->cs_f, boards.tsx snub): the weak leg's ZVS window at the SER250-bus764 corner admits
    // 330 pF and nothing above it, so the part number must not inherit the shared 1 nF class.
    C1HOS1: { price1k: 9, mpn: "C1206-330p-1kV-C0G", desc: "330 pF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @30 kW; 470 pF and above close the weak leg's ZVS window at the SER250-bus764 corner entirely)" },
    C1LOS1: { price1k: 9, mpn: "C1206-330p-1kV-C0G", desc: "330 pF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @30 kW)" },
    C2HOS1: { price1k: 9, mpn: "C1206-330p-1kV-C0G", desc: "330 pF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @30 kW)" },
    C2LOS1: { price1k: 9, mpn: "C1206-330p-1kV-C0G", desc: "330 pF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @30 kW)" },
    // The mirrored Vienna clamp is DNP here — see MIRROR_CLAMP below, which drives the qtyMul.
  },
  // 40 kW air: line 73.3 A worst (design-basis/loss-budget).
  "40kw": {
    QA0A: { price1k: 240, desc: "SiC MOSFET 750 V 15 mΩ class TO-247-4 (Vienna common-source pair, one die per position)", mpn: "SIC-750V-15mR", note: "750 V 15 mΩ class, single die per position (grid T_j 127 °C) — RFQ target; ACCEPTANCE IDM ≥ 260 A @25 °C (205 A F.01 fault peak)" },
    QA0B: { price1k: 240, desc: "SiC MOSFET 750 V 15 mΩ class TO-247-4 (Vienna common-source pair, one die per position)", mpn: "SIC-750V-15mR", note: "750 V 15 mΩ class, single die per position (grid T_j 127 °C) — RFQ target; ACCEPTANCE IDM ≥ 260 A @25 °C (205 A F.01 fault peak)" },
    QB0A: { price1k: 240, desc: "SiC MOSFET 750 V 15 mΩ class TO-247-4 (Vienna common-source pair, one die per position)", mpn: "SIC-750V-15mR", note: "750 V 15 mΩ class, single die per position (grid T_j 127 °C) — RFQ target; ACCEPTANCE IDM ≥ 260 A @25 °C (205 A F.01 fault peak)" },
    QB0B: { price1k: 240, desc: "SiC MOSFET 750 V 15 mΩ class TO-247-4 (Vienna common-source pair, one die per position)", mpn: "SIC-750V-15mR", note: "750 V 15 mΩ class, single die per position (grid T_j 127 °C) — RFQ target; ACCEPTANCE IDM ≥ 260 A @25 °C (205 A F.01 fault peak)" },
    QC0A: { price1k: 240, desc: "SiC MOSFET 750 V 15 mΩ class TO-247-4 (Vienna common-source pair, one die per position)", mpn: "SIC-750V-15mR", note: "750 V 15 mΩ class, single die per position (grid T_j 127 °C) — RFQ target; ACCEPTANCE IDM ≥ 260 A @25 °C (205 A F.01 fault peak)" },
    QC0B: { price1k: 240, desc: "SiC MOSFET 750 V 15 mΩ class TO-247-4 (Vienna common-source pair, one die per position)", mpn: "SIC-750V-15mR", note: "750 V 15 mΩ class, single die per position (grid T_j 127 °C) — RFQ target; ACCEPTANCE IDM ≥ 260 A @25 °C (205 A F.01 fault peak)" },
    // 100 A × 0.72 enclosed derate = 72 A < the 73.3 A worst line current; 125 A derates to 90 A, 23 % margin.
    "F1": { price1k: 210, mpn: "FUSE-gG-690V-125A", desc: "gG fuse 125 A 690 VAC, 22×58 frame (40 kW AC input, 73.3 A worst continuous). The holder must be the matching 22×58 base" }, "F2": { price1k: 210, mpn: "FUSE-gG-690V-125A", desc: "gG fuse 125 A 690 VAC, 22×58 frame (40 kW AC input, 73.3 A worst continuous). The holder must be the matching 22×58 base" }, "F3": { price1k: 210, mpn: "FUSE-gG-690V-125A", desc: "gG fuse 125 A 690 VAC, 22×58 frame (40 kW AC input, 73.3 A worst continuous). The holder must be the matching 22×58 base" },
    KPRE1: { price1k: 300, desc: "power relay 100 A/line with a mirror contact — the precharge bypass carries full line current. §K line: contact-gap withstand and insulation group at the 475 VAC system plus the ~660 V pk precharge transient", note: "100 A class (73 A line) · make ≥ 280 A pk at bypass closure, ≤ 70 V across the contacts, ≥ 30 000 makes", mpn: "HF167F-100A-M" }, KPRE2: { price1k: 300, mpn: "HF167F-100A-M", desc: "power relay 100 A/line with a mirror contact — the precharge bypass carries full line current. §K line: contact-gap withstand and insulation group at the 475 VAC system plus the ~660 V pk precharge transient" },
    CMC1: { price1k: 1327, note: "D7-40 custom wind 75 A (the Schaffner 63 A catalog part is OUT of range here) · D7-40 rev B: T 80/50/25, A_Fe ≥ 281 mm², 3×8 T 20 mm², 17.0 W, ΔT 32 K [est roll-up]", mpn: "CMC-3PH-2mH-SKU" }, CMC2: { price1k: 1327, mpn: "CMC-3PH-2mH-SKU" },
    RSHO: { price1k: 140, mpn: "SHUNT-50MV-133A", desc: "manganin shunt 0.376 mΩ (50 mV at the 133 A rated output), Kelvin 4-terminal", note: "manganin shunt 0.376 mΩ = 50 mV at the 133 A rated output, Kelvin 4-terminal" },
    DOUT: { price1k: 520, desc: "output series blocking diode 1600 V 200 A, insulated-base 2-terminal module (133 A = 67 % at 40 kW; ~1.05 V × Iout, heatsink-mounted)", mpn: "DIODE-1600V-200A-MOD", note: "1600 V 200 A insulated-base module: 133 A out = 67 % (a 150 A part would run 89 %)" },
    // Full-bridge LLC classes (tanks.mjs · magnetics-envelope · current-coordination)
    T1A: { price1k: 1434, mpn: "XFMR-LLC-CELL-3E70-40", desc: "D3-40 rev D: full-bridge LLC transformer CELL (2 per module, primaries in SERIES → n = 2 overall) — 3× E70/33/32 PC95-class on a 3-set former (lN 293 mm, custom), 4:4∥4 (S1–P–S2 with S1 ∥ S2 feeding one bank), Lm 21.75 µH per cell ±7%, primary TIW-served litz 3536×0.071 mm (14 mm²), secondary halves 2 × Cu foil 0.08×28 mm per turn; leakage 0.132 µH computed on the 28 mm conductor band (acceptance ±20 %), vacuum-impregnated, both yoke faces gap-padded to the webs, end turns potted. Envelope gate: Fe 47.6 W at 159 mT (500 V bank) · Cu 46.1 W at the 764 V-bus PSM corner · hot-spot 102 °C at 55 °C inlet. Roll-up: 3 × E70 ₹480 + litz ₹302 + foil ₹115 (+10 %) + 3-set former/insulation/shield/gap/labour/test ₹495 → ₹1,434 [est, REVIEW at winder RFQ]" },
    T1B: { price1k: 1434, mpn: "XFMR-LLC-CELL-3E70-40", desc: "D3-40 rev D: full-bridge LLC transformer CELL (2 per module, primaries in SERIES → n = 2 overall) — 3× E70/33/32 PC95-class on a 3-set former (lN 293 mm, custom), 4:4∥4 (S1–P–S2 with S1 ∥ S2 feeding one bank), Lm 21.75 µH per cell ±7%, primary TIW-served litz 3536×0.071 mm (14 mm²), secondary halves 2 × Cu foil 0.08×28 mm per turn; leakage 0.132 µH computed on the 28 mm conductor band (acceptance ±20 %), vacuum-impregnated, both yoke faces gap-padded to the webs, end turns potted. Envelope gate: Fe 47.6 W at 159 mT (500 V bank) · Cu 46.1 W at the 764 V-bus PSM corner · hot-spot 102 °C at 55 °C inlet. Roll-up: 3 × E70 ₹480 + litz ₹302 + foil ₹115 (+10 %) + 3-set former/insulation/shield/gap/labour/test ₹495 → ₹1,434 [est, REVIEW at winder RFQ]" },
    L1R: { price1k: 1077, mpn: "IND-LR-E70-40", desc: "D2-40 rev F: EXTERNAL resonant inductor 3.99 µH ±3% on 2× E70/33/32 PC95-class (TDK former B66372A2000), N=5, litz 10000×0.05 mm (19.6 mm²) compacted single layer ≥3 mm clear of a DISTRIBUTED centre-leg gap Σ 10.5 mm PER FLUX PATH (≤1.0 mm per segment; parallel sets never summed; acceptance = the assembled AL, from which Σ re-derives at the winder RFQ); vacuum-impregnated, both yoke faces padded, end turns potted. Carries Lr 4.35 µH − 2 × D3 cell leakage (0.132 µH, acceptance ±20 %) − 0.1 µH loop — no trim bins. Envelope gate: 33.1 W Fe (91 mT) + 27.3 W Cu at the PSM corner, hot-spot 100 °C at 55 °C inlet. Roll-up ₹1,077 [est, REVIEW at winder RFQ]" },
    CT1: { price1k: 165, mpn: "CT-RES-1:100-150A", desc: "resonant CT 1:100, 150 A rms class, 20–250 kHz, pass-through — the tank conductor is the primary (ONE CT on the full-bridge tank; the 40 kW tank class 100 A rms = 67 %) — custom HF-CT wind at RFQ" },
    R1CT: { mpn: "R2512-0R36-1W-1%", desc: "0.36 Ω 1% 1 W 2512 resonant-CT burden (F.11 180 A pk = 0.65 V above AVMID; observable to 450 A, past the 417 A monitor peak 3 µs after an internal short; 100 A rms tank class → 0.36 W)", note: "0.36 Ω 1 W resonant-CT burden: F.11 180 A pk = 0.65 V above AVMID, observable to 450 A against the 417 A monitor peak 3 µs after an internal short; 1.0 A rms → 0.36 W" },
    // D1-40 rev B on the CATALOG 0077908A7 (AL 37 ±8 %, Ae 2.27 cm²): 5-stack, N=26 ±1 lot-trim → L0 116 µH
    // [106–135 lot window], ≥61 µH @104 A pk, dIpp 27.5 A nom, ΔT 30 K, fill 36 %. A geometric-core model
    // (Ae 2.62) puts N at 23 and misses the choke's own L floor on the real core.
    LA0: { price1k: 1240, desc: "PFC choke 116 µH class, 5× OD79 26µ sendust (Magnetics 0077908A7 / Chang Sung KS eq, catalog AL 37 nH/T² ±8%), N=26, 13× 1.6 mm enamelled bundle (docs/magnetics.md D1-40 rev B)", mpn: "IND-PFC-116u-40", note: "D1-40 rev B: 5x 0077908A7 CATALOG core, N=26 +/-1 lot-trim" },
    LB0: { price1k: 1240, desc: "PFC choke 116 µH class, 5× OD79 26µ sendust (Magnetics 0077908A7 / Chang Sung KS eq, catalog AL 37 nH/T² ±8%), N=26, 13× 1.6 mm enamelled bundle (docs/magnetics.md D1-40 rev B)", mpn: "IND-PFC-116u-40" }, LC0: { price1k: 1240, desc: "PFC choke 116 µH class, 5× OD79 26µ sendust (Magnetics 0077908A7 / Chang Sung KS eq, catalog AL 37 nH/T² ±8%), N=26, 13× 1.6 mm enamelled bundle (docs/magnetics.md D1-40 rev B)", mpn: "IND-PFC-116u-40" },
    CTA0: { price1k: 95, mpn: "CT-LINE-2500-150A", desc: "line CT 2500:1, 150 A class (Talema ACX-1150 catalog), 4 kV hipot, PCB pins — the 50 kHz amplitude/phase, ≤ 1 µs step and ≥ 5 A DC acceptance rows apply to this class too; F.01 155 A pk on 18 Ω plus the 50 A race needs linearity to ≥ 205 A" }, CTB0: { price1k: 95, mpn: "CT-LINE-2500-150A", desc: "line CT 2500:1, 150 A class (Talema ACX-1150 catalog), 4 kV hipot, PCB pins — the 50 kHz amplitude/phase, ≤ 1 µs step and ≥ 5 A DC acceptance rows apply to this class too; F.01 155 A pk on 18 Ω plus the 50 A race needs linearity to ≥ 205 A" }, CTC0: { price1k: 95, mpn: "CT-LINE-2500-150A", desc: "line CT 2500:1, 150 A class (Talema ACX-1150 catalog), 4 kV hipot, PCB pins — the 50 kHz amplitude/phase, ≤ 1 µs step and ≥ 5 A DC acceptance rows apply to this class too; F.01 155 A pk on 18 Ω plus the 50 A race needs linearity to ≥ 205 A" },
    RA0B: { mpn: "R1206-18R-1%", desc: "18 Ω line-CT burden 1% 1206 (F.01 155 A pk = 2.77 V; observability ceiling 225 A through the D1 soft-saturation race)", note: "18 Ω line-CT burden: F.01 155 A pk = 2.77 V, observability ceiling 225 A" }, RB0B: { mpn: "R1206-18R-1%", desc: "18 Ω line-CT burden 1% 1206 (F.01 155 A pk = 2.77 V; observability ceiling 225 A through the D1 soft-saturation race)" }, RC0B: { mpn: "R1206-18R-1%", desc: "18 Ω line-CT burden 1% 1206 (F.01 155 A pk = 2.77 V; observability ceiling 225 A through the D1 soft-saturation race)" },
    // Turn-off snubbers (tanks.mjs cs) and the 2 W bias class on the two-die LLC channels
    C1HOS1: { price1k: 9, mpn: "C1206-680p-1kV-C0G", desc: "680 pF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @40 kW — 1 nF is excluded here: it rings the PAR500 corner to 91 % of 1200 V at the 5 nH loop, and this SKU’s 43.5 µH Lm gives the lowest magnetizing current of the three tanks, so its ZVS dead time binds first)" }, C1HOS2: { price1k: 9, mpn: "C1206-680p-1kV-C0G", desc: "680 pF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @40 kW — the knee: k_off 5.20 nJ/(V·A), 83.8 % of 1200 V, 379 ns. 1 nF is excluded here, ringing the PAR500 corner to 91 %, and this SKU's 43.5 µH Lm gives the lowest magnetizing current of the three tanks, so its ZVS dead time binds first)" },
    C1LOS1: { price1k: 9, mpn: "C1206-680p-1kV-C0G", desc: "680 pF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @40 kW — 1 nF is excluded here: it rings the PAR500 corner to 91 % of 1200 V at the 5 nH loop, and this SKU’s 43.5 µH Lm gives the lowest magnetizing current of the three tanks, so its ZVS dead time binds first)" }, C1LOS2: { price1k: 9, mpn: "C1206-680p-1kV-C0G", desc: "680 pF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @40 kW — the knee: k_off 5.20 nJ/(V·A), 83.8 % of 1200 V, 379 ns. 1 nF is excluded here, ringing the PAR500 corner to 91 %, and this SKU's 43.5 µH Lm gives the lowest magnetizing current of the three tanks, so its ZVS dead time binds first)" },
    C2HOS1: { price1k: 9, mpn: "C1206-680p-1kV-C0G", desc: "680 pF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @40 kW — 1 nF is excluded here: it rings the PAR500 corner to 91 % of 1200 V at the 5 nH loop, and this SKU’s 43.5 µH Lm gives the lowest magnetizing current of the three tanks, so its ZVS dead time binds first)" }, C2HOS2: { price1k: 9, mpn: "C1206-680p-1kV-C0G", desc: "680 pF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @40 kW — the knee: k_off 5.20 nJ/(V·A), 83.8 % of 1200 V, 379 ns. 1 nF is excluded here, ringing the PAR500 corner to 91 %, and this SKU's 43.5 µH Lm gives the lowest magnetizing current of the three tanks, so its ZVS dead time binds first)" },
    C2LOS1: { price1k: 9, mpn: "C1206-680p-1kV-C0G", desc: "680 pF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @40 kW — 1 nF is excluded here: it rings the PAR500 corner to 91 % of 1200 V at the 5 nH loop, and this SKU’s 43.5 µH Lm gives the lowest magnetizing current of the three tanks, so its ZVS dead time binds first)" }, C2LOS2: { price1k: 9, mpn: "C1206-680p-1kV-C0G", desc: "680 pF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @40 kW — the knee: k_off 5.20 nJ/(V·A), 83.8 % of 1200 V, 379 ns. 1 nF is excluded here, ringing the PAR500 corner to 91 %, and this SKU's 43.5 µH Lm gives the lowest magnetizing current of the three tanks, so its ZVS dead time binds first)" },
    PS1H: { price1k: 140, p10k: 100, mpn: "ISO-GBIAS-15-2W", desc: "iso gate-bias module +15/−3 V, **2 W class**: this channel drives TWO paralleled SG2M023120LJ dies at up to f_max 203 kHz, so P_gate = n·Q_g·ΔV·f + driver I_CC2 = 1.13 W at f_r and 1.59 W at f_max — 113–159 % of a 1 W module, continuously. An overloaded module droops, the NSI66x1A VCC2 UVLO falling threshold is 9.8–11.8 V, and a sagging rail first raises R_DS(on) on the paralleled dies and then takes the channel offline at exactly the light-output-voltage corners, presenting as a control fault that is not one. The 30 kW channels drive one die (0.85 W worst) and keep the 1 W class. RFQ: C_io ≤ 5 pF for the CM budget" },
    PS1L: { price1k: 140, p10k: 100, mpn: "ISO-GBIAS-15-2W", desc: "iso gate-bias module +15/−3 V, **2 W class**: this channel drives TWO paralleled SG2M023120LJ dies at up to f_max 203 kHz, so P_gate = n·Q_g·ΔV·f + driver I_CC2 = 1.13 W at f_r and 1.59 W at f_max — 113–159 % of a 1 W module, continuously. An overloaded module droops, the NSI66x1A VCC2 UVLO falling threshold is 9.8–11.8 V, and a sagging rail first raises R_DS(on) on the paralleled dies and then takes the channel offline at exactly the light-output-voltage corners, presenting as a control fault that is not one. The 30 kW channels drive one die (0.85 W worst) and keep the 1 W class. RFQ: C_io ≤ 5 pF for the CM budget" },
    PS2H: { price1k: 140, p10k: 100, mpn: "ISO-GBIAS-15-2W", desc: "iso gate-bias module +15/−3 V, **2 W class**: this channel drives TWO paralleled SG2M023120LJ dies at up to f_max 203 kHz, so P_gate = n·Q_g·ΔV·f + driver I_CC2 = 1.13 W at f_r and 1.59 W at f_max — 113–159 % of a 1 W module, continuously. An overloaded module droops, the NSI66x1A VCC2 UVLO falling threshold is 9.8–11.8 V, and a sagging rail first raises R_DS(on) on the paralleled dies and then takes the channel offline at exactly the light-output-voltage corners, presenting as a control fault that is not one. The 30 kW channels drive one die (0.85 W worst) and keep the 1 W class. RFQ: C_io ≤ 5 pF for the CM budget" },
    PS2L: { price1k: 140, p10k: 100, mpn: "ISO-GBIAS-15-2W", desc: "iso gate-bias module +15/−3 V, **2 W class**: this channel drives TWO paralleled SG2M023120LJ dies at up to f_max 203 kHz, so P_gate = n·Q_g·ΔV·f + driver I_CC2 = 1.13 W at f_r and 1.59 W at f_max — 113–159 % of a 1 W module, continuously. An overloaded module droops, the NSI66x1A VCC2 UVLO falling threshold is 9.8–11.8 V, and a sagging rail first raises R_DS(on) on the paralleled dies and then takes the channel offline at exactly the light-output-voltage corners, presenting as a control fault that is not one. The 30 kW channels drive one die (0.85 W worst) and keep the 1 W class. RFQ: C_io ≤ 5 pF for the CM budget" },
  },
  // 50 kW LIQUID (pfc-design @PFC_P=50e3/PFC_PAR=2, frozen 50 kHz; envelope grid at the 65 °C hot-plate
  // reference): line 91.6 A worst, output 167 A. One PFC die per phase and two LLC dies per position on
  // the clip mount (mount.mjs) — the same silicon as the 40 kW.
  "50kw": {
    // 125 A × 0.72 enclosed derate = 90 A < the 91.6 A worst line current; 160 A gG derates to 115 A
    // (26 % margin) and the frame steps 22×58 → NH00 (the mech line carries the holder).
    "F1": { price1k: 260, mpn: "FUSE-gG-690V-160A", desc: "gG fuse 160 A 690 VAC, NH00 blade (50 kW AC input, 91.6 A worst continuous). The holder is the matching NH00 base — the 22×58 frame ends at 125 A" }, "F2": { price1k: 260, mpn: "FUSE-gG-690V-160A", desc: "gG fuse 160 A 690 VAC, NH00 blade (50 kW AC input, 91.6 A worst continuous). The holder is the matching NH00 base — the 22×58 frame ends at 125 A" }, "F3": { price1k: 260, mpn: "FUSE-gG-690V-160A", desc: "gG fuse 160 A 690 VAC, NH00 blade (50 kW AC input, 91.6 A worst continuous). The holder is the matching NH00 base — the 22×58 frame ends at 125 A" },
    // S/P matrix and output at 50 kW: SER 100 A = 67 % of a 150 A PCB relay; DOUT 167 A = 84 % of the
    // 200 A class, and the diode is a continuous-current part, so it steps to the 250 A module.
    KSER: { price1k: 280, mpn: "RELAY-PCB-150A-24V", desc: "PCB power relay 150 A, 24 V coil, no mirror contact (S/P matrix, switched at ZERO current — modes change in standby with the LLC stopped; open-contact dielectric ≥ 2.5 kV holds the ≤ 500 V bank; SER 100 A = 67 % of the class)" }, KPARA: { price1k: 280, mpn: "RELAY-PCB-150A-24V", desc: "PCB power relay 150 A, 24 V coil, no mirror contact (S/P matrix, switched at ZERO current — modes change in standby with the LLC stopped; open-contact dielectric ≥ 2.5 kV holds the ≤ 500 V bank; in PAR each relay carries one bank's half of the 167 A output)" }, KPARB: { price1k: 280, mpn: "RELAY-PCB-150A-24V", desc: "PCB power relay 150 A, 24 V coil, no mirror contact (S/P matrix, switched at ZERO current — modes change in standby with the LLC stopped; open-contact dielectric ≥ 2.5 kV holds the ≤ 500 V bank; in PAR each relay carries one bank's half of the 167 A output)" },
    DOUT: { price1k: 620, desc: "output series blocking diode 1600 V 250 A, insulated-base 2-terminal module (167 A = 67 % at 50 kW; ~1.05 V × Iout, heatsink-mounted)", mpn: "DIODE-1600V-250A-MOD", note: "1600 V 250 A insulated-base module: 167 A out = 67 % (a 200 A part would run 84 %)" },
    CMC1: { price1k: 2065, note: "D7-50 custom wind 95 A · D7-50 rev B: T 90/50/30, A_Fe ≥ 450 mm², 3×8 T 25 mm², 26.7 W, ΔT 38 K [est roll-up]", mpn: "CMC-3PH-2mH-SKU" }, CMC2: { price1k: 2065, mpn: "CMC-3PH-2mH-SKU" },
    RSHO: { price1k: 155, mpn: "SHUNT-50MV-167A", desc: "manganin shunt 0.299 mΩ (50 mV at the 167 A rated output), Kelvin 4-terminal", note: "manganin shunt 0.299 mΩ = 50 mV at the 167 A rated output, Kelvin 4-terminal" },
    // Full-bridge LLC classes (tanks.mjs · magnetics-envelope · current-coordination) — the air twin copies these
    T1A: { price1k: 1434, mpn: "XFMR-LLC-CELL-3E70-50", desc: "D3-50 rev D: full-bridge LLC transformer CELL (2 per module, primaries in SERIES → n = 2 overall) — the D3-40 construction: 3× E70/33/32 PC95-class on a 3-set former, 4:4∥4, Lm 17.8 µH per cell ±7%, TIW-served litz 3536×0.071 mm, 2 × Cu foil 0.08×28 mm halves; leakage 0.132 µH (±20 %), vacuum-impregnated, both yoke faces plate-bonded (liquid) or web-bonded (air), end turns potted. Envelope gate: Fe 47.5 W at 159 mT · Cu 71.3 W at the PSM corner · hot-spot 103 °C liquid / 116 °C air at 55 °C inlet. Roll-up ₹1,434 [est, REVIEW at winder RFQ]" },
    T1B: { price1k: 1434, mpn: "XFMR-LLC-CELL-3E70-50", desc: "D3-50 rev D: full-bridge LLC transformer CELL (2 per module, primaries in SERIES → n = 2 overall) — the D3-40 construction: 3× E70/33/32 PC95-class on a 3-set former, 4:4∥4, Lm 17.8 µH per cell ±7%, TIW-served litz 3536×0.071 mm, 2 × Cu foil 0.08×28 mm halves; leakage 0.132 µH (±20 %), vacuum-impregnated, both yoke faces plate-bonded (liquid) or web-bonded (air), end turns potted. Envelope gate: Fe 47.5 W at 159 mT · Cu 71.3 W at the PSM corner · hot-spot 103 °C liquid / 116 °C air at 55 °C inlet. Roll-up ₹1,434 [est, REVIEW at winder RFQ]" },
    L1R: { price1k: 1191, mpn: "IND-LR-E70-50", desc: "D2-50 rev F: EXTERNAL resonant inductor 3.20 µH ±3% on 2× E70/33/32 PC95-class (TDK former B66372A2000), N=5, litz 12000×0.05 mm (23.6 mm²), DISTRIBUTED centre-leg gap Σ 13.1 mm PER FLUX PATH (≤1.0 mm per segment; parallel sets never summed; acceptance = the assembled AL, from which Σ re-derives at the winder RFQ); vacuum-impregnated, both yoke faces padded, end turns potted. Carries Lr 3.56 µH − 2 × D3 cell leakage (0.132 µH, acceptance ±20 %) − 0.1 µH loop. Envelope gate: 32.8 W Fe (90 mT) + 45.0 W Cu at the PSM corner, hot-spot 98 °C liquid / 109 °C air. Roll-up ₹1,191 [est, REVIEW at winder RFQ]" },
    CT1: { price1k: 165, mpn: "CT-RES-1:100-150A", desc: "resonant CT 1:100, 150 A rms class, 20–250 kHz, pass-through — the tank conductor is the primary (ONE CT on the full-bridge tank; the 50 kW tank class 120 A rms = 80 %) — custom HF-CT wind at RFQ" },
    R1CT: { mpn: "R2512-0R30-2W-1%", desc: "0.30 Ω 1% 2 W 2512 resonant-CT burden (F.11 220 A pk = 0.66 V above AVMID; observable to 540 A, past the 503 A monitor peak 3 µs after an internal short; 120 A rms tank class → 0.43 W on the 2 W part)", note: "0.30 Ω resonant-CT burden on the 2 W class: F.11 220 A pk = 0.66 V above AVMID, observable to 540 A against the 503 A monitor peak 3 µs after an internal short; 1.2 A rms → 0.43 W" },
    // Pulse energy at the 1.88 mF link — 162 J per discharge resistor, ~211 J per precharge resistor —
    // crosses the highest 25 W-accepted family point (158 J), so both step to the 50 W class part.
    RPRE1: { price1k: 45, desc: "33 Ω 50 W ceramic pulse resistor, axial (AC precharge at the 1.88 mF link, ~211 J per event). RFQ ROW: flameproof and FAIL-OPEN under sustained overload (UL 1412 / IEC 60115 flammability) — a shorted link or a failed-short Vienna pair at switch-on puts kilowatts on each resistor and nothing in the module can disconnect it, so the part fusing open without flame IS the protection; the vendor single-pulse energy curve at 0.4 s must cover 235 J × 3 starts", note: "33 Ω on the 50 W pulse class (~211 J/event at the 1.88 mF link); flameproof, FAIL-OPEN under sustained overload", mpn: "CER-50W-33R-AX" }, RPRE2: { price1k: 45, mpn: "CER-50W-33R-AX", desc: "33 Ω 50 W ceramic pulse resistor, axial (AC precharge at the 1.88 mF link, ~211 J per event). RFQ ROW: flameproof and FAIL-OPEN under sustained overload (UL 1412 / IEC 60115 flammability) — a shorted link or a failed-short Vienna pair at switch-on puts kilowatts on each resistor and nothing in the module can disconnect it, so the part fusing open without flame IS the protection; the vendor single-pulse energy curve at 0.4 s must cover 235 J × 3 starts" },
    RDIS0: { price1k: 45, desc: "160 Ω 50 W ceramic pulse resistor, axial (bus discharge string, 4× in series; 162 J each at the 1.88 mF link)", note: "160 Ω on the 50 W pulse class (162 J each at the 1.88 mF link)", mpn: "CER-50W-160R-AX" }, RDIS1: { price1k: 45, mpn: "CER-50W-160R-AX", desc: "160 Ω 50 W ceramic pulse resistor, axial (bus discharge string, 4× in series; 162 J each at the 1.88 mF link)" }, RDIS2: { price1k: 45, mpn: "CER-50W-160R-AX", desc: "160 Ω 50 W ceramic pulse resistor, axial (bus discharge string, 4× in series; 162 J each at the 1.88 mF link)" }, RDIS3: { price1k: 45, mpn: "CER-50W-160R-AX", desc: "160 Ω 50 W ceramic pulse resistor, axial (bus discharge string, 4× in series; 162 J each at the 1.88 mF link)" },
    // D1-50 rev B on the CATALOG 0077908A7: no N on the 5-stack holds BOTH the ripple basis and the 0.40
    // swing floor, so the honest point is N=24 ±1 lot-trim → L0 107 µH [98–124], ≥45 µH @129.5 A pk, dIpp
    // basis 36.2 A pp nom, swing 0.405, ΔT 41 K convective (plate/web bond).
    LA0: { price1k: 1240, desc: "PFC choke 107 µH class, 5× OD79 26µ sendust (Magnetics 0077908A7 / Chang Sung KS eq, catalog AL 37 nH/T² ±8%), N=24, 13× 1.6 mm enamelled bundle (docs/magnetics.md D1-50 rev B)", mpn: "IND-PFC-107u-50", note: "D1-50 rev B: 5x T79 26u CATALOG core, N=24 +/-1 lot-trim" },
    LB0: { price1k: 1240, desc: "PFC choke 107 µH class, 5× OD79 26µ sendust (Magnetics 0077908A7 / Chang Sung KS eq, catalog AL 37 nH/T² ±8%), N=24, 13× 1.6 mm enamelled bundle (docs/magnetics.md D1-50 rev B)", mpn: "IND-PFC-107u-50" }, LC0: { price1k: 1240, desc: "PFC choke 107 µH class, 5× OD79 26µ sendust (Magnetics 0077908A7 / Chang Sung KS eq, catalog AL 37 nH/T² ±8%), N=24, 13× 1.6 mm enamelled bundle (docs/magnetics.md D1-50 rev B)", mpn: "IND-PFC-107u-50" },
    // Line CTs: a 100 A class part would run 92 % at 91.6 A rms, so the sensor path classes up.
    CTA0: { price1k: 95, mpn: "CT-LINE-2500-150A", desc: "line CT 2500:1, 150 A class (Talema ACX-1150 catalog, linear to 200 A at 33 Ω), 4 kV hipot, PCB pins — the 50 kHz amplitude/phase, ≤ 1 µs step and ≥ 5 A DC acceptance rows apply to this class too; F.01 195 A pk on 13 Ω = 2.66 V, observable to 311 A through the D1 soft-saturation race" },
    CTB0: { price1k: 95, mpn: "CT-LINE-2500-150A", desc: "line CT 2500:1, 150 A class (Talema ACX-1150 catalog, linear to 200 A at 33 Ω), 4 kV hipot, PCB pins — the 50 kHz amplitude/phase, ≤ 1 µs step and ≥ 5 A DC acceptance rows apply to this class too; F.01 195 A pk on 13 Ω = 2.66 V, observable to 311 A through the D1 soft-saturation race" }, CTC0: { price1k: 95, mpn: "CT-LINE-2500-150A", desc: "line CT 2500:1, 150 A class (Talema ACX-1150 catalog, linear to 200 A at 33 Ω), 4 kV hipot, PCB pins — the 50 kHz amplitude/phase, ≤ 1 µs step and ≥ 5 A DC acceptance rows apply to this class too; F.01 195 A pk on 13 Ω = 2.66 V, observable to 311 A through the D1 soft-saturation race" },
    RA0B: { mpn: "R1206-13R-1%", desc: "13 Ω line-CT burden 1% 1206 (F.01 195 A pk = 2.66 V; observable to 311 A through the D1 soft-saturation race, inside the 3.275 V rail budget above AVMID)", note: "13 Ω line-CT burden: F.01 195 A pk = 2.66 V, observable to 311 A" },
    RB0B: { mpn: "R1206-13R-1%", desc: "13 Ω line-CT burden 1% 1206 (F.01 195 A pk = 2.66 V; observable to 311 A through the D1 soft-saturation race, inside the 3.275 V rail budget above AVMID)" }, RC0B: { mpn: "R1206-13R-1%", desc: "13 Ω line-CT burden 1% 1206 (F.01 195 A pk = 2.66 V; observable to 311 A through the D1 soft-saturation race, inside the 3.275 V rail budget above AVMID)" },
    // Turn-off snubbers (tanks.mjs cs) and the 2 W bias class on the two-die LLC channels
    C1HOS1: { price1k: 10, mpn: "C1206-1n-1kV-C0G", desc: "1 nF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @50 kW L and A — the 35.6 µH Lm leaves ZVS headroom the 40 kW does not have)" }, C1HOS2: { price1k: 10, mpn: "C1206-1n-1kV-C0G", desc: "1 nF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @50 kW L and A — the 35.6 µH Lm leaves ZVS headroom the 40 kW does not have)" },
    C1LOS1: { price1k: 10, mpn: "C1206-1n-1kV-C0G", desc: "1 nF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @50 kW L and A — the 35.6 µH Lm leaves ZVS headroom the 40 kW does not have)" }, C1LOS2: { price1k: 10, mpn: "C1206-1n-1kV-C0G", desc: "1 nF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @50 kW L and A — the 35.6 µH Lm leaves ZVS headroom the 40 kW does not have)" },
    C2HOS1: { price1k: 10, mpn: "C1206-1n-1kV-C0G", desc: "1 nF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @50 kW L and A — the 35.6 µH Lm leaves ZVS headroom the 40 kW does not have)" }, C2HOS2: { price1k: 10, mpn: "C1206-1n-1kV-C0G", desc: "1 nF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @50 kW L and A — the 35.6 µH Lm leaves ZVS headroom the 40 kW does not have)" },
    C2LOS1: { price1k: 10, mpn: "C1206-1n-1kV-C0G", desc: "1 nF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @50 kW L and A — the 35.6 µH Lm leaves ZVS headroom the 40 kW does not have)" }, C2LOS2: { price1k: 10, mpn: "C1206-1n-1kV-C0G", desc: "1 nF 1 kV C0G 1206 LLC turn-off snubber (tanks.mjs cs @50 kW L and A — the 35.6 µH Lm leaves ZVS headroom the 40 kW does not have)" },
    PS1H: { price1k: 140, p10k: 100, mpn: "ISO-GBIAS-15-2W", desc: "iso gate-bias module +15/−3 V, **2 W class**: this channel drives TWO paralleled SG2M023120LJ dies at up to f_max 203 kHz, so P_gate = n·Q_g·ΔV·f + driver I_CC2 = 1.13 W at f_r and 1.59 W at f_max — 113–159 % of a 1 W module, continuously. An overloaded module droops, the NSI66x1A VCC2 UVLO falling threshold is 9.8–11.8 V, and a sagging rail first raises R_DS(on) on the paralleled dies and then takes the channel offline at exactly the light-output-voltage corners, presenting as a control fault that is not one. The 30 kW channels drive one die (0.85 W worst) and keep the 1 W class. RFQ: C_io ≤ 5 pF for the CM budget" },
    PS1L: { price1k: 140, p10k: 100, mpn: "ISO-GBIAS-15-2W", desc: "iso gate-bias module +15/−3 V, **2 W class**: this channel drives TWO paralleled SG2M023120LJ dies at up to f_max 203 kHz, so P_gate = n·Q_g·ΔV·f + driver I_CC2 = 1.13 W at f_r and 1.59 W at f_max — 113–159 % of a 1 W module, continuously. An overloaded module droops, the NSI66x1A VCC2 UVLO falling threshold is 9.8–11.8 V, and a sagging rail first raises R_DS(on) on the paralleled dies and then takes the channel offline at exactly the light-output-voltage corners, presenting as a control fault that is not one. The 30 kW channels drive one die (0.85 W worst) and keep the 1 W class. RFQ: C_io ≤ 5 pF for the CM budget" },
    PS2H: { price1k: 140, p10k: 100, mpn: "ISO-GBIAS-15-2W", desc: "iso gate-bias module +15/−3 V, **2 W class**: this channel drives TWO paralleled SG2M023120LJ dies at up to f_max 203 kHz, so P_gate = n·Q_g·ΔV·f + driver I_CC2 = 1.13 W at f_r and 1.59 W at f_max — 113–159 % of a 1 W module, continuously. An overloaded module droops, the NSI66x1A VCC2 UVLO falling threshold is 9.8–11.8 V, and a sagging rail first raises R_DS(on) on the paralleled dies and then takes the channel offline at exactly the light-output-voltage corners, presenting as a control fault that is not one. The 30 kW channels drive one die (0.85 W worst) and keep the 1 W class. RFQ: C_io ≤ 5 pF for the CM budget" },
    PS2L: { price1k: 140, p10k: 100, mpn: "ISO-GBIAS-15-2W", desc: "iso gate-bias module +15/−3 V, **2 W class**: this channel drives TWO paralleled SG2M023120LJ dies at up to f_max 203 kHz, so P_gate = n·Q_g·ΔV·f + driver I_CC2 = 1.13 W at f_r and 1.59 W at f_max — 113–159 % of a 1 W module, continuously. An overloaded module droops, the NSI66x1A VCC2 UVLO falling threshold is 9.8–11.8 V, and a sagging rail first raises R_DS(on) on the paralleled dies and then takes the channel offline at exactly the light-output-voltage corners, presenting as a control fault that is not one. The 30 kW channels drive one die (0.85 W worst) and keep the 1 W class. RFQ: C_io ≤ 5 pF for the CM budget" },
    // 50 kW input-filter damper: 4.7 µF X1 with 4.7 Ω. Lightly damped, the LCL modes oscillate at 194.7 %
    // of the shipped 15 µs delay; this pair gives modulus margin 0.73 at Td 20 µs. The resistor stays the
    // 25 W class (11.8 W, 47 %). The 50 kW-air twin inherits the block by construction.
    CDMP1: { price1k: 92, mpn: "X1-4u7-530", desc: "X1 4.7 µF 530 VAC (50 kW input-filter damper cap, delta across the 475 VAC line-line)" },
    CDMP2: { price1k: 92, mpn: "X1-4u7-530", desc: "X1 4.7 µF 530 VAC (50 kW input-filter damper cap, delta across the 475 VAC line-line)" }, CDMP3: { price1k: 92, mpn: "X1-4u7-530", desc: "X1 4.7 µF 530 VAC (50 kW input-filter damper cap, delta across the 475 VAC line-line)" },
    RDMP1: { price1k: 16, mpn: "SQP-4R7-25W", desc: "4.7 Ω 25 W wirewound pulse, axial, series L ≤ 10 µH (CX2-node series-RC damper RDMPx at 50 kW; 11.8 W = 47 % of the class)", note: "4.7 Ω CX2-node damper resistor, 11.8 W on the 25 W class (47 %)" },
    RDMP2: { price1k: 16, mpn: "SQP-4R7-25W", desc: "4.7 Ω 25 W wirewound pulse, axial, series L ≤ 10 µH (CX2-node series-RC damper RDMPx at 50 kW; 11.8 W = 47 % of the class)" }, RDMP3: { price1k: 16, mpn: "SQP-4R7-25W", desc: "4.7 Ω 25 W wirewound pulse, axial, series L ≤ 10 µH (CX2-node series-RC damper RDMPx at 50 kW; 11.8 W = 47 % of the class)" },
    // 50 kW precharge bypass: 91.6 A line on a 250 A frame = 37 %. The HF167F family tops out at ~100 A
    // main, so this position is a real EV-contactor class part with an auxiliary, not an HF167F variant.
    KPRE1: { price1k: 620, desc: "precharge-bypass power relay, 250 A class — an EV-type contactor (Hongfa HFE18V/NB90 or TE EV200 class) with a 1 Form A auxiliary as the mirror contact; 91.6 A line = 37 % of the class. §K line: contact-gap withstand and insulation group at the 475 VAC system plus the ~660 V pk precharge transient", note: "250 A class CONTACTOR with a 1 Form A auxiliary (Hongfa HFE18V/NB90 or TE EV200 class) · 91.6 A line = 37 % · make ≥ 360 A pk at bypass closure, ≤ 70 V across the contacts, ≥ 30 000 makes · land pattern re-checked against the chosen part's drawing before BOM freeze", mpn: "HFE18V-250A-AUX" }, KPRE2: { price1k: 620, mpn: "HFE18V-250A-AUX", desc: "precharge-bypass power relay, 250 A class — an EV-type contactor (Hongfa HFE18V/NB90 or TE EV200 class) with a 1 Form A auxiliary as the mirror contact; 91.6 A line = 37 % of the class. §K line: contact-gap withstand and insulation group at the 475 VAC system plus the ~660 V pk precharge transient" },
  },
  // 50 kW AIR: every electrical class IDENTICAL to the liquid 50 kW (same line, tank and output currents —
  // the classes are set by current, not by coolant). Assigned programmatically below so the two cannot drift.
};

// THE mirror-clamp population source. The LAND is on every phase of every board (boards.tsx passes
// `mirrorClamp` to ViennaPhase unconditionally: one PCB, four SKUs); WHICH SKUs are POPULATED lives here
// and nowhere else, and the per-part qtyMul entries above are derived from it below. Every consumer — the
// BOM, the DPT deck's drawn() network, a DFM sheet — reads this.
// STANDING BOM NOTE for the DNP SKUs: fit the mirrored clamp if T-59 measures the unclamped negative
// half-cycle above 85 % of 750 V — +₹471/module (3 phases × [SiC JBS ₹55 + 100 nF/250 V film ₹18 + 470 Ω
// 10 W bleeder ₹22] at the 1k basis). At the 5 nH loop the DPT reads 76–79 % on 30/40 kW and 82 % on both
// 50 kW SKUs, which is why only the 50s are populated.
export const MIRROR_CLAMP = { "30kw": false, "40kw": false, "50kw": true, "50kwa": true };
// DC-DC entry film count per SKU: 16 × 1 µF/1100 V holds the 30/40 kW cans at 58/68 % of the RFQ ripple
// line at the 40 nH design stud; the 50 kW pair reads 81 % at 16 and needs 20 (+₹218). boards.tsx draws
// this count and the dclink deck / current-coordination gate it; the 20-film variant on 30/40 kW is the
// registered lever if T-57 measures ≤ 25 nH.
export const ENTRY_FILM = { "30kw": 16, "40kw": 16, "50kw": 20, "50kwa": 20 };
for (const [sku, fit] of Object.entries(MIRROR_CLAMP)) {
  if (fit || !skuOverrides[sku]) continue;
  for (const ph of ["A", "B", "C"]) for (const pre of ["D", "C", "R"]) {
    const ref = `${pre}${ph}0CM`;
    skuOverrides[sku][ref] = { ...(skuOverrides[sku][ref] ?? {}), qtyMul: 0 };
  }
}
skuOverrides["50kwa"] = { ...skuOverrides["50kw"] };   // air-50 shares every class part with the liquid

// 2U CONSTRUCTION SCENARIO, NOT the design basis: heatsink chassis with the magnetics potted into wells,
// both PCBAs 4-layer 2 oz at about half today's area, 3 × 80×38 high-speed fans, a light cover.
// Prerequisites no gate has proven: (1) the PFC choke must lie in a chassis well (today's 3/5 × T79 stacks
// stand 60–95 mm); (2) the chassis must hold the 70 °C device base at 55 °C ambient (mount.mjs basis, EVT
// T-38); (3) the potted D2/D3 path must match the two-face bond the magnetics envelope assumes.
// Estimates @1k, India basis — a mechanical design and quotes replace them.
export const mech2U = {
  "30kw": [["PCB-ACDC 4L 2 oz ≈380×280 (2U scenario est)", 1, 700], ["PCB-DCDC 4L 2 oz ≈380×280 (2U scenario est)", 1, 750],
    ["Heatsink chassis with magnetics wells, dies clipped (2U scenario est)", 1, 1600], ["Fans 80×38 high-speed PWM IP55 (2U scenario est)", 3, 230],
    ["Cover + front/rear panels (2U scenario est)", 1, 550], ["Busbars/interconnect studs + harness (compact, 2U scenario est)", 1, 650],
    ["NTC sensor assemblies (insulated tip spec)", 4, 18], ["TIM/insulators/fasteners (clip mount, 27 dies)", 1, 480],
    ["Magnetics potting into chassis wells (replaces bond + D1 mount kits, 2U scenario est)", 1, 450],
    ["Conformal coating (acrylic, both boards + card)", 1, 320], ["Assembly + calibration + EOL test (fewer parts, 2U scenario est)", 1, 1600]],
  "40kw": [["PCB-ACDC 4L 2 oz ≈400×290 (2U scenario est)", 1, 750], ["PCB-DCDC 4L 2 oz ≈400×290 (2U scenario est)", 1, 800],
    ["Heatsink chassis with magnetics wells, dies clipped (2U scenario est)", 1, 1800], ["Fans 80×38 high-speed PWM IP55 (2U scenario est)", 3, 230],
    ["Cover + front/rear panels (2U scenario est)", 1, 550], ["Busbars/interconnect studs + harness (compact, 2U scenario est)", 1, 730],
    ["NTC sensor assemblies (insulated tip spec)", 4, 18], ["TIM/insulators/fasteners (clip mount, 39 dies)", 1, 640],
    ["Magnetics potting into chassis wells (replaces bond + D1 mount kits, 2U scenario est)", 1, 550],
    ["Conformal coating (acrylic, both boards + card)", 1, 340], ["Assembly + calibration + EOL test (fewer parts, 2U scenario est)", 1, 1650]],
};
export const mechLines = {
  "30kw": [
    // Every SKU's boards are 440×500 (boards/*/[ac|dc]dc.tsx w=440 h=500), so the 30 kW carries the
    // 40 kW board area at lighter copper — 0.220 m² on both boards.
    ["PCB-ACDC 6L 440×500", 1, 1250], ["PCB-DCDC 6L 440×500", 1, 1450],
    ["Heatsink extrusions (2, sandwich outer faces)", 1, 1500], ["Fans 120×38 PWM (3.3 V-PWM p/n, dual-ball-bearing, L10 ≥70 kh @40 °C, IP55, −30…+70 °C field-reliability spec; IP55 premium at RFQ · ELECTRICAL CLASS: ≤ 0.6 A at 24 V (≤ 14 W) at 100 % PWM, start surge ≤ 1.5 A for ≤ 0.3 s — the 160 m³/h class the air budget assumes draws 7–14 W and the 110 W aux (d4-flyback i24s 1.6–2.4 A) is sized on it; a 25 W fan pushes the aux into the NCP1252's LATCHED over-current). The third fan runs on the FAN_TACH3 way with its PWM ganged on FAN_PWM2", 3, 280],
    ["Enclosure sheet metal + hardware", 1, 1000], ["Busbars/interconnect studs + harness (busbar-calc)", 1, 724],
    ["NTC sensor assemblies (insulated tip spec)", 4, 18], ["TIM/insulators/fasteners (clip mount: 0.635 mm Al2O3 insulator + spring clip + grease under each of 27 TO-247 dies, mount.mjs 0.8 K/W)", 1, 480],
    ["Magnetics bond kit: 3 W/mK silicone gap pads on BOTH yoke faces of the two D3 cells and the D2 to the upper/lower extrusion webs + clamp bars, end turns potted (≥0.8 W/mK), CTE-compliant (no rigid epoxy to aluminium); VPI is in the part price — three parts", 1, 220],
    ["D1 choke mount kit: per stack — fiberglass-reinforced silicone gap pad 1.0 mm ≥3 W/mK (≥5 kVAC ASTM D149, basic insulation to the PE-bonded web), GF-PPS insulating clamp cap + bore sleeve (basic insulation winding↔bolt), M6 A4 bolt + Belleville + nut, 2-point glass banding; the bonded end face is the D1 cooling path [est: pad ₹45, cap+sleeve ₹42, hardware+banding ₹18]", 3, 105],
    ["Conformal coating (acrylic, both boards + card)", 1, 320],
    ["Assembly + calibration + EOL test", 1, 1900],
  ],
  // 40 kW: same envelope; heavier busbars/heatsink share, 2 extra link cans in PCB area
  "40kw": [
    ["PCB-ACDC 6L 440×500", 1, 1250], ["PCB-DCDC 6L 440×500", 1, 1450],
    ["Heatsink extrusions (2, sandwich outer faces — 40 kW fin stock)", 1, 1750],
    ["Fans 120×38 PWM (3.3 V-PWM p/n, dual-ball-bearing, L10 ≥70 kh @40 °C, IP55, −30…+70 °C field-reliability spec; IP55 premium at RFQ · ELECTRICAL CLASS: ≤ 0.6 A at 24 V (≤ 14 W) at 100 % PWM, start surge ≤ 1.5 A for ≤ 0.3 s — the 160 m³/h class the air budget assumes draws 7–14 W and the 110 W aux (d4-flyback i24s 1.6–2.4 A) is sized on it; a 25 W fan pushes the aux into the NCP1252's LATCHED over-current)", 3, 280],
    ["Enclosure sheet metal + hardware", 1, 1000], ["Busbars/interconnect studs + harness (busbar-calc)", 1, 810],
    ["NTC sensor assemblies (insulated tip spec)", 4, 18], ["TIM/insulators/fasteners (clip mount: 0.635 mm Al2O3 insulator + spring clip + grease under each of 39 TO-247 dies, mount.mjs 0.8 K/W)", 1, 640],
    ["Magnetics bond kit: 3 W/mK silicone gap pads on BOTH yoke faces of the two 3-set D3 cells and the D2 to the upper/lower extrusion webs + clamp bars, end turns potted to the web (≥0.8 W/mK silicone), CTE-compliant; VPI is in the part price — three parts", 1, 380],
    ["D1 choke mount kit: per stack — fiberglass-reinforced silicone gap pad 1.0 mm ≥3 W/mK (≥5 kVAC ASTM D149, basic insulation to the PE-bonded web), GF-PPS insulating clamp cap + bore sleeve (basic insulation winding↔bolt), M6 A4 bolt + Belleville + nut, 2-point glass banding; the bonded end face is the D1 cooling path [est: pad ₹45, cap+sleeve ₹42, hardware+banding ₹18]", 3, 105],
    ["Conformal coating (acrylic, both boards + card)", 1, 340],
    ["Assembly + calibration + EOL test", 1, 1950],
  ],
  // 50 kW LIQUID: same 440×500 envelope; coldplates REPLACE the extrusions AND the fans (sealed module).
  // Coldplate pricing is the thermal-RFQ estimate (brazed/FSW channel plate at 10k/yr) and is flagged
  // REVIEW like the other custom lines. EOL adds the pressure/leak test.
  "50kw": [
    ["PCB-ACDC 6L 440×500 (50 kW copper masses)", 1, 1300], ["PCB-DCDC 6L 440×500", 1, 1500],
    ["Liquid coldplates (2, sandwich outer faces, brazed channel — REVIEW at thermal RFQ)", 1, 4400],
    ["Coolant fittings: 2× quick-disconnect + internal manifold/hose set", 1, 380],
    ["Gap pads + potting (choke stacks / transformers / EMI magnetics → plate webs)", 1, 420],
    ["Magnetics two-face plate bond: gap pads on BOTH yoke faces of the two D3 cells and the D2 to the two coldplates, end turns potted to the plate (adds to the potting line above); VPI is in the part price — three parts", 1, 200],
    ["Enclosure sheet metal + hardware (sealed, gasket set; NH00 fuse bases)", 1, 1250],
    ["Busbars/interconnect studs + harness (busbar-calc, 167 A output class)", 1, 850],
    ["NTC sensor assemblies (insulated tip spec — plate-mounted)", 4, 18],
    ["D1 choke mount kit: per stack — gap pad in the plate-web line above; GF-PPS insulating clamp cap + bore sleeve (basic insulation winding↔bolt), M6 A4 bolt + Belleville + nut, 2-point glass banding; the bonded end face is the D1 cooling path [est: pad ₹45, cap+sleeve ₹42, hardware+banding ₹18]", 3, 60],
    ["D1 over-temperature cutout: NC snap-action thermostat 130 ±5 °C on each D1 clamp cap, basic-insulated to line potential, series-wired into the magnetics cutout loop — bond-loss cover in the sealed liquid module, which has no air path: a lost D1 pad has no fallback", 3, 48],
    ["TIM/insulators/fasteners (clip mount: 0.635 mm Al2O3 insulator + spring clip + grease under each of 39 TO-247 dies, mount.mjs 0.8 / 0.65 K/W)", 1, 640],
    ["Conformal coating (acrylic, both boards + card)", 1, 360],
    ["Assembly + calibration + EOL test (incl. coolant-loop pressure/leak test)", 1, 2150],
  ],
  // 50 kW AIR: extrusions + 4 fans replace the coldplate set; vented enclosure; same PCBs
  "50kwa": [
    ["PCB-ACDC 6L 440×500 (50 kW copper masses)", 1, 1300], ["PCB-DCDC 6L 440×500", 1, 1500],
    ["Heatsink extrusions (2, sandwich outer faces — 50 kW fin stock)", 1, 1900],
    ["Fans 120×38 PWM (3 front + 1 rear, 3.3 V-PWM p/n, dual-ball L10 ≥70 kh, IP55, −30…+70 °C; IP55 premium at RFQ · ELECTRICAL CLASS: ≤ 0.6 A at 24 V (≤ 14 W) at 100 % PWM, start surge ≤ 1.5 A for ≤ 0.3 s — the 160 m³/h class the air budget assumes draws 7–14 W and the 110 W aux (d4-flyback i24s 1.6–2.4 A) is sized on it; a 25 W fan pushes this four-fan SKU into the NCP1252's LATCHED over-current)", 4, 280],
    ["Enclosure sheet metal + hardware (vented; NH00 fuse bases)", 1, 1000],
    ["Busbars/interconnect studs + harness (busbar-calc, 167 A output class)", 1, 850],
    ["NTC sensor assemblies (insulated tip spec)", 4, 18],
    ["Magnetics bond kit: 3 W/mK silicone gap pads on BOTH yoke faces of the two 3-set D3 cells and the D2 to the upper/lower extrusion webs + clamp bars, end turns potted to the web (≥0.8 W/mK silicone), CTE-compliant; VPI is in the part price — three parts", 1, 380],
    ["D1 choke mount kit: per stack — fiberglass-reinforced silicone gap pad 1.0 mm ≥3 W/mK (≥5 kVAC ASTM D149, basic insulation to the PE-bonded web), GF-PPS insulating clamp cap + bore sleeve (basic insulation winding↔bolt), M6 A4 bolt + Belleville + nut, 2-point glass banding; the bonded end face is the D1 cooling path [est: pad ₹45, cap+sleeve ₹42, hardware+banding ₹18]", 3, 105],
    ["TIM/insulators/fasteners (clip mount: 0.635 mm Al2O3 insulator + spring clip + grease under each of 39 TO-247 dies, mount.mjs 0.8 / 0.65 K/W)", 1, 640],
    ["Conformal coating (acrylic, both boards + card)", 1, 360],
    ["Assembly + calibration + EOL test", 1, 2000],
  ],
};
