// card-pinmap-gen.mts — generate CARD_MCU_PINS from the released GD32G553VET7 allocation.
//
// The card is ONE part number for both converter roles, but the released allocation has TWO maps
// (UPFC, ULLC) allocated independently, and they disagree on 27 of the 29 signals they share.
// Merging them is not a preference, it is a requirement, and the merge rule matters:
//
//   SUPERSET RULE. Where the two roles want different PERIPHERALS on the same way, take the pin
//   whose peripheral is the superset. A timer/ADC pin can always fall back to plain GPIO; a plain
//   GPIO can never become a capture input. Taking the DC-DC pin blindly would have cost the AC-DC
//   role hardware fan PWM (DO0/DO1) and hardware tach capture (DI0/DI1) -- four functions silently
//   downgraded to bit-banging on a 30 kW converter.
//
//   Otherwise the DC-DC (ULLC) pin wins: it is the sizing role, 77 signals over 87 landings
//   against the PFC's 61/69, so it is the one with no room to move.
//
// Run: npx tsx calculations/card-pinmap-gen.mts
import { readFileSync } from "node:fs";
const alloc = JSON.parse(readFileSync(process.cwd() + "/calculations/out/mcu-pin-allocation.json", "utf8"));
const { cardMap, CARD_PIN_DECISIONS } = await import(process.cwd() + "/packages/common-components/control-card.tsx");

const pinOf = (r: string, n: string) => alloc[r]?.map?.[n]?.[0];
const POWER = new Set(["V24", "V15", "V3P3", "DGND", "AGND", "AGND_2", "PE"]);
const klass = (f: string) => /ADC/.test(f) ? "ADC"
  : /HRTIMER_ST|TIMER\d+_CH|input capture/.test(f) ? "PWM"
  : /BRKIN|_FLT\d/.test(f) ? "FAULT" : /USART|CAN|SPI|I2C/.test(f) ? "COMM" : "GPIO";

// Datasheet-fixed pins. Nothing may be allocated over these.
const FIXED: Record<number, string> = { 23:"VSS",48:"VSS",63:"VSS",74:"VSS",99:"VSS",
  24:"VDD",49:"VDD",64:"VDD",75:"VDD",100:"VDD",37:"VDDA",35:"VSSA",36:"VREFP",6:"VBAT",
  14:"NRST",95:"BOOT0",76:"SWDIO",77:"SWCLK",12:"OSCIN",13:"OSCOUT" };
// PC13/PC14/PC15 sit in the backup domain (shared ~3 mA through the backup power switch) -- the
// R3 audit calls them out as unreliable general I/O. Keep them out of the pool.
const AVOID = new Set([7, 8, 9]);
// Ways generated by hardware ON the card and sent out. No MCU pin exists or is needed: GATE_EN is
// the AND gate's output, and the AND gate is the authority on it, not firmware.
const NO_PIN = new Set(["GATE_EN"]);

const AC = cardMap("acdc", 2), DC = cardMap("dcdc", 2);
const acN = new Map(AC.map(([w, n]: any) => [w, n?.replace("net.", "") ?? null]));
const dcN = new Map(DC.map(([w, n]: any) => [w, n?.replace("net.", "") ?? null]));
const ways = cardMap("card").map(([w]: any) => w).filter((w: string) => !POWER.has(w));

const out: Record<string, number> = {}, why: Record<string, string> = {}, unresolved: string[] = [];
for (const w of ways) {
  if (NO_PIN.has(w)) continue;
  const an = acN.get(w), dn = dcN.get(w);
  // ROLE0 is a STRAP: the AC-DC board ties it to DGND, so following the net would land on VSS.
  // It is a GPIO input on the card, never the ground net.
  const ap = an && an !== "DGND" ? pinOf("UPFC", an) : undefined;
  const dp = dn ? pinOf("ULLC", dn) : undefined;
  let pick: any = null, src = "";
  if (ap && dp) {
    const ak = klass(ap.func), dk = klass(dp.func);
    if (ak !== dk && dk === "GPIO") { pick = ap; src = `UPFC — ${ak} is a superset of the DC-DC role's GPIO`; }
    else { pick = dp; src = "ULLC (sizing role)"; }
  } else if (dp) { pick = dp; src = "ULLC only"; } else if (ap) { pick = ap; src = "UPFC only"; }
  if (pick && !FIXED[pick.pin]) { out[w] = pick.pin; why[w] = `${pick.port} ${pick.func} — ${src}`; }
  else unresolved.push(w);
}

// Resolve collisions: the way with the HARDER peripheral requirement keeps the pin.
const seen = new Map<number, string>();
for (const w of Object.keys(out)) {
  const p = out[w], prev = seen.get(p);
  if (prev === undefined) { seen.set(p, w); continue; }
  const keep = /TIMER|capture|HRTIMER|ADC/.test(why[w]) && !/TIMER|capture|HRTIMER|ADC/.test(why[prev]) ? w : prev;
  const move = keep === w ? prev : w;
  delete out[move]; unresolved.push(move); seen.set(p, keep);
}

// Deliberate allocations for ways the released 120 kW map never carried, with the reason each pin
// was chosen. ADC-capability is evidenced by a released map using that pin for an ADC function.
const adcCap = new Set<number>();
for (const r of ["UPFC", "ULLC"]) for (const arr of Object.values(alloc[r].map) as any)
  for (const e of arr) if (/ADC/.test(e.func)) adcCap.add(e.pin);
const MANUAL: Record<string, [number, string]> = {
  // pins 15-34 are the contiguous analogue block (R3 audit); AVMID is the reference every bipolar
  // sense is measured against, so it gets the cleanest analogue pin available.
  AVMID: [18, "PC3 ADC01_IN8 — clean analogue block (pins 15-34), MCU nulls AVMID drift out of every sense"],
  AIN11: [25, "PA3 ADC — analogue expansion way, spare at 30/60 kW"],
  AIN12: [26, "PA4 ADC — analogue expansion way, spare at 30/60 kW"],
  // PE7 is the one analogue pin sitting inside the gate-drive block, which the R3 audit flags as a
  // bad home for a live current sense. A static resistor code read once at boot is exactly the load
  // that does not care about a noisy neighbour, so the compromised pin is put to its best use.
  ROLE1: [38, "PE7 ADC2_IN3 — rating resistor code, read once at boot; noise-immune use for the one analogue pin inside the gate-drive block"],
  ROLE0: [90, "PB3 GPIO — slot strap, read once at boot"],
  DRV_RDY: [81, "PC12 GPIO input — per-board driver power-good, wired-OR of every gate driver's open-drain RDY"],
  HMI6: [91, "PB4 GPIO/EXTI — BTN2, displaced from PD3 by the AC-DC role's tach capture"],
};
for (const [w, [p, reason]] of Object.entries(MANUAL)) {
  if (!unresolved.includes(w) && out[w] !== undefined) continue;
  if (FIXED[p] || AVOID.has(p) || [...Object.values(out)].includes(p))
    throw new Error(`manual pin ${p} for ${w} is not free`);
  out[w] = p; why[w] = reason; unresolved.splice(unresolved.indexOf(w), 1);
}

// ------------------------------------------------------------------------------------------------
// DECISION 2026-09-08 (audit F8; docs/control-card-scope.md §6): the card's PWM group runs on the
// HRTIMER, not TIMER0/7/19. At card scope (≤6 legs) the HRTIMER's 8 units × 2 ch cover both roles:
//   DC-DC — each LLC leg is one slave unit in complementary mode (H=CHx0, L=CHx1) → HARDWARE
//   dead-time per leg, native per-unit phase offset, sub-ns resolution;
//   AC-DC — the 6 Vienna phases take ST0..5 CH0, independent units, per-unit lane interleave;
//   FLT   — one filtered fault input (HRTIMER_FLT2, PB10/47) gates every output in hardware with
//           24 ns latency. The card's fault wired-OR is pulled to V3P3 ON THE CARD (RFLTC), so
//           PB10's non-5VT rating is satisfied by construction — R3's 5VT concern was for a 5 V
//           pulled fault line. This dissolves the PA6 one-AF break-input conflict (the released
//           ULLC map's TIMER0/7 plan left 4 of 12 legs with no hardware break at all).
// Displacements are a closed set: EN_B vacates 47 for FLT; DI2/DI3 and HMI0..3 vacate the HRTIMER
// output pins onto pins freed by the advanced-timer plan's retirement. CH1-of-ST1/3/5 pin numbers
// (PA11/72, PB15/54, PC7/66) follow the ST-pair adjacency the released map shows for ST0/2/4 —
// confirm against Table 2-10 AF column at §K before tape-out.
const HRTIMER_DECISION: Record<string, [number, string]> = CARD_PIN_DECISIONS;
{
  const moved = new Set(Object.keys(HRTIMER_DECISION));
  const freed = new Set(Object.entries(out).filter(([w]) => moved.has(w)).map(([, p]) => p));
  for (const w of moved) delete out[w];
  for (const [w, [p, reason]] of Object.entries(HRTIMER_DECISION)) {
    const holder = Object.entries(out).find(([, q]) => q === p);
    if (holder) throw new Error(`HRTIMER decision: pin ${p} for ${w} still held by ${holder[0]}`);
    if (FIXED[p] || AVOID.has(p)) throw new Error(`HRTIMER decision: pin ${p} for ${w} not usable`);
    out[w] = p; why[w] = `${reason} — HRTIMER decision 2026-09-08`;
    const ui = unresolved.indexOf(w); if (ui >= 0) unresolved.splice(ui, 1);
  }
  void freed; // pins 39/46/79/80 return to the spare pool
}

const v = Object.values(out);
console.log(`\nways ${ways.length}  allocated ${Object.keys(out).length}  card-generated (no pin) ${NO_PIN.size}  unresolved ${unresolved.length}`);
console.log(`duplicates: ${v.filter((x, i) => v.indexOf(x) !== i).join(" ") || "none"}`);
console.log(`on fixed pins: ${Object.entries(out).filter(([, p]) => FIXED[p]).map(([w, p]) => `${w}->${p}`).join(" ") || "none"}`);
console.log(`in backup domain: ${Object.entries(out).filter(([, p]) => AVOID.has(p)).map(([w]) => w).join(" ") || "none"}`);
console.log(`unresolved: ${unresolved.join(" ") || "none"}`);
console.log(`non-ADC pin on an analogue way: ${Object.entries(out).filter(([w, p]) => /^(AIN|AVMID|ROLE1|TSNS)/.test(w) && !adcCap.has(p)).map(([w, p]) => `${w}->${p}`).join(" ") || "none"}`);
console.log(`\n${JSON.stringify(out)}\n`);
if (process.argv[2] === "--why") for (const w of Object.keys(out).sort()) console.log(`  ${w.padEnd(9)} ${String(out[w]).padStart(3)}  ${why[w]}`);
