// card-pinmap-reconcile.mts — derive the ONE card pin map from the GD32G553VET6 allocation.
//
// The card is a single part number serving both converter roles, so every connector way must land
// on exactly ONE MCU pin. The released allocation has TWO maps (UPFC, ULLC) that were allocated
// independently and disagree on the same signal. This reconciles them and shows the cost.
//
// The DC-DC (ULLC) allocation wins on conflict: it is the sizing role (77 signals over 87 landings
// against the PFC's 61/69), so it is the one with no room to move.
import { readFileSync } from "node:fs";
const alloc = JSON.parse(readFileSync(process.cwd() + "/calculations/out/mcu-pin-allocation.json", "utf8"));
const { cardMap, CARD_MCU_PINS, CARD_PIN_DECISIONS } = await import(process.cwd() + "/packages/common-components/control-card.tsx");

const pinOf = (role: string, net: string) => alloc[role]?.map?.[net]?.[0];
const POWER = new Set(["V24", "V15", "V3P3", "DGND", "AGND", "AGND_2", "PE"]);

// Peripheral class implied by the datasheet function string -- an ADC way cannot move to a pin
// with no ADC, and a PWM way cannot move to a pin with no timer output.
const klass = (f: string) => /ADC/.test(f) ? "ADC"
  : /HRTIMER_ST|TIMER\d+_CH/.test(f) ? "PWM"
  : /BRKIN|_FLT\d/.test(f) ? "FAULT"
  : /USART|CAN|SPI|I2C/.test(f) ? "COMM"
  : /input capture/.test(f) ? "CAPTURE" : "GPIO";

const AC = cardMap("acdc", 2), DC = cardMap("dcdc", 2);
const acNet = new Map(AC.map(([w, n]: any) => [w, n?.replace("net.", "") ?? null]));
const dcNet = new Map(DC.map(([w, n]: any) => [w, n?.replace("net.", "") ?? null]));
const ways = cardMap("card").map(([w]: any) => w).filter((w: string) => !POWER.has(w));

const rows: any[] = [];
for (const w of ways) {
  const an = acNet.get(w), dn = dcNet.get(w);
  const ap = an ? pinOf("UPFC", an) : undefined;
  const dp = dn ? pinOf("ULLC", dn) : undefined;
  rows.push({ way: w, acNet: an, dcNet: dn, ap, dp,
    pin: dp?.pin ?? ap?.pin ?? null,
    from: dp ? "ULLC" : ap ? "UPFC" : null,
    conflict: !!(ap && dp && ap.pin !== dp.pin),
    classClash: !!(ap && dp && klass(ap.func) !== klass(dp.func)),
  });
}

const have = rows.filter((r) => r.pin);
const miss = rows.filter((r) => !r.pin);
const conf = rows.filter((r) => r.conflict);
const clash = rows.filter((r) => r.classClash);

console.log(`\n== card ways reconciled against GD32G553VET6 (R3 allocation)\n`);
console.log(`  signal ways            ${ways.length}`);
console.log(`  landed on a real pin   ${have.length}`);
console.log(`  in BOTH role maps      ${rows.filter((r) => r.ap && r.dp).length}`);
console.log(`  the two maps DISAGREE  ${conf.length}  (DC-DC wins; AC-DC firmware must follow)`);
console.log(`  peripheral CLASS clash ${clash.length}  (merge would break one role's function)`);
console.log(`  no pin in either map   ${miss.length}`);

if (clash.length) {
  console.log(`\n  -- class clashes (a way whose two roles need DIFFERENT peripherals):`);
  for (const r of clash)
    console.log(`     ${r.way.padEnd(9)} AC ${r.acNet} p${r.ap.pin} ${r.ap.port} ${klass(r.ap.func)}   vs   DC ${r.dcNet} p${r.dp.pin} ${r.dp.port} ${klass(r.dp.func)}`);
}
if (miss.length) {
  console.log(`\n  -- ways with NO pin in either released map:`);
  for (const r of miss) console.log(`     ${r.way.padEnd(9)} ac=${r.acNet ?? "-"}  dc=${r.dcNet ?? "-"}`);
}
console.log(`\n  -- first 12 disagreements (pin taken from ULLC):`);
for (const r of conf.slice(0, 12))
  console.log(`     ${r.way.padEnd(9)} AC ${String(r.acNet).padEnd(14)} p${String(r.ap.pin).padStart(3)}   DC ${String(r.dcNet).padEnd(14)} p${String(r.dp.pin).padStart(3)} <- taken`);

// dedupe / safety
const byPin = new Map<number, string[]>();
for (const r of have) (byPin.get(r.pin) ?? byPin.set(r.pin, []).get(r.pin)!).push(r.way);
const dup = [...byPin].filter(([, v]) => v.length > 1);
const FIXED: Record<number, string> = { 23: "VSS", 48: "VSS", 63: "VSS", 74: "VSS", 99: "VSS",
  24: "VDD", 49: "VDD", 64: "VDD", 75: "VDD", 100: "VDD", 37: "VDDA", 35: "VSSA", 36: "VREFP",
  6: "VBAT", 14: "NRST", 95: "BOOT0", 76: "SWDIO", 77: "SWCLK" };
const onFixed = have.filter((r) => FIXED[r.pin]);
console.log(`\n  -- safety`);
console.log(`     pins used twice: ${dup.length ? dup.map(([p, v]) => `${p}:${v.join("/")}`).join(" ") : "none"}`);
console.log(`     ways landing on a FIXED pin (VSS/VDD/NRST/BOOT0/SWD/VREF): ${onFixed.length ? onFixed.map((r) => `${r.way}->p${r.pin}(${FIXED[r.pin]})`).join(" ") : "none"}`);

console.log(`\n== naive merge (what the two released maps alone would give)\n`);
const out: Record<string, number> = {};
for (const r of have) out[r.way] = r.pin;
console.log(JSON.stringify(out));

// == the DECIDED map (E35: HRTIMER decision + manual allocations) vs the naive merge ==
// CARD_MCU_PINS is the authority (generated by card-pinmap-gen.mts). This section shows exactly
// which ways the decision moved and re-runs the safety checks on the decided map, so this tool
// stays a meaningful cross-check instead of disagreeing with the decision forever.
const moved = Object.keys(CARD_MCU_PINS).filter((w) => out[w] !== undefined && out[w] !== CARD_MCU_PINS[w]);
console.log(`\n== decided map (CARD_MCU_PINS) vs naive merge — ${moved.length} way(s) moved by decisions\n`);
for (const w of moved)
  console.log(`     ${w.padEnd(9)} naive p${String(out[w]).padStart(3)} -> decided p${String(CARD_MCU_PINS[w]).padStart(3)}  ${CARD_PIN_DECISIONS[w]?.[1] ?? "(manual allocation)"}`);
const dv = Object.values(CARD_MCU_PINS);
const ddup = dv.filter((x, i) => dv.indexOf(x) !== i);
const donFixed = Object.entries(CARD_MCU_PINS).filter(([, p]) => FIXED[p as number]);
console.log(`\n  -- decided-map safety: duplicates ${ddup.length ? ddup.join(" ") : "none"}; on fixed pins ${donFixed.length ? donFixed.map(([w, p]) => `${w}->p${p}`).join(" ") : "none"}`);
if (ddup.length || donFixed.length) process.exit(1);
