#!/usr/bin/env node
// footprint-gen.mjs — author the through-hole land patterns whose geometry is fully determined
// by the dimensions already encoded in the footprint name, and emit them as KiCad .kicad_mod
// files (a format EasyEDA Pro imports directly).
//
// WHY THIS IS NOT INVENTED DATA. A name like CAP-TH_L26.5-W11.0-P22.50 already carries the
// part's body length, body width and lead pitch from its datasheet. The land pattern follows:
// two pads on the lead pitch, hole sized to the lead, annular ring per IPC, silkscreen the body
// outline. The ONE thing not in the name is the lead diameter, so it is stated explicitly per
// family below and is the single number to correct if a datasheet disagrees.
//
// Deliberately NOT generated here: wound magnetics, current transformers and the manganin shunt.
// Those have no standard land — their pad geometry comes from the winder's/maker's drawing, and
// guessing it would be fabricating manufacturing data. They stay as placeholders.
//
// Run: node calculations/footprint-gen.mjs  ->  kicad5/footprints/*.kicad_mod

import { writeFileSync, mkdirSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "kicad5/footprints");
mkdirSync(OUT, { recursive: true });

// Lead diameter by family, in mm. The only assumed number in this file.
//   film/box caps on a wide pitch use 0.8 mm leads; small film 0.6 mm;
//   axial power resistors (48-60 mm bodies, 10-25 W) use 1.0 mm.
const LEAD = (kind, pitch) => (kind === "RES" ? 1.0 : pitch > 10 ? 0.8 : 0.6);

const HOLE_CLEAR = 0.3;     // hole = lead + 0.3 mm  (IPC-2222 class 2, plated)
const ANNULAR = 0.45;       // pad  = hole + 2 x 0.45 mm

const pad = (n, x, hole) => {
  const d = Number((hole + 2 * ANNULAR).toFixed(2));
  const shape = n === 1 ? "rect" : "circle";     // pin 1 square, the usual convention
  return `  (pad ${n} thru_hole ${shape} (at ${x} 0) (size ${d} ${d}) (drill ${hole}) (layers *.Cu *.Mask))`;
};

const line = (x1, y1, x2, y2, layer = "F.SilkS", w = 0.15) =>
  `  (fp_line (start ${x1} ${y1}) (end ${x2} ${y2}) (layer ${layer}) (width ${w}))`;

const rect = (L, W, layer = "F.SilkS", w = 0.15) => {
  const x = Number((L / 2).toFixed(2)), y = Number((W / 2).toFixed(2));
  return [line(-x, -y, x, -y, layer, w), line(x, -y, x, y, layer, w),
          line(x, y, -x, y, layer, w), line(-x, y, -x, -y, layer, w)].join("\n");
};

const twoLead = (name, kind, L, W, P) => {
  const lead = LEAD(kind, P);
  const hole = Number((lead + HOLE_CLEAR).toFixed(2));
  const x = Number((P / 2).toFixed(2));
  const body = rect(L, W);
  // courtyard 0.5 mm outside the greater of body and lead span
  const cx = Number((Math.max(L, P + hole + 2 * ANNULAR) / 2 + 0.5).toFixed(2));
  const cy = Number((W / 2 + 0.5).toFixed(2));
  return `(module ${name} (layer F.Cu) (tedit 0)
  (descr "${kind === "RES" ? "Axial through-hole resistor" : "Through-hole capacitor"} body ${L} x ${W} mm, lead pitch ${P} mm, lead dia ${lead} mm (assumed), hole ${hole} mm. Generated by calculations/footprint-gen.mjs.")
  (fp_text reference REF** (at 0 ${-(W / 2 + 1.2).toFixed(2)}) (layer F.SilkS) (effects (font (size 1 1) (thickness 0.15))))
  (fp_text value ${name} (at 0 ${(W / 2 + 1.2).toFixed(2)}) (layer F.Fab) (effects (font (size 1 1) (thickness 0.15))))
${body}
${/* lead stubs only where the pads sit OUTSIDE the body, i.e. axial parts. On a radial box cap
      the pitch is shorter than the body and the leads exit underneath, so there is nothing to draw. */
  x > L / 2 ? line(-x, 0, -Number((L / 2).toFixed(2)), 0) + "\n" + line(x, 0, Number((L / 2).toFixed(2)), 0) : ""}
${rect(cx * 2, cy * 2, "F.CrtYd", 0.05)}
${pad(1, -x, hole)}
${pad(2, x, hole)}
)
`;
};

// M8 bolted stud / M4 tab: a single large plated hole with a ring pad, sized to the thread.
const stud = (name, thread, padDia) => {
  const hole = Number((thread + 0.4).toFixed(2));
  const c = Number((padDia / 2 + 0.5).toFixed(2));
  return `(module ${name} (layer F.Cu) (tedit 0)
  (descr "M${thread} bolted power stud land: ${hole} mm plated hole, ${padDia} mm ring pad. Torque/washer stack per the mechanical drawing. Generated by calculations/footprint-gen.mjs.")
  (fp_text reference REF** (at 0 ${-c - 1}) (layer F.SilkS) (effects (font (size 1 1) (thickness 0.15))))
  (fp_text value ${name} (at 0 ${c + 1}) (layer F.Fab) (effects (font (size 1 1) (thickness 0.15))))
  (fp_circle (center 0 0) (end ${padDia / 2 + 0.3} 0) (layer F.SilkS) (width 0.15))
${rect(c * 2, c * 2, "F.CrtYd", 0.05)}
  (pad 1 thru_hole circle (at 0 0) (size ${padDia} ${padDia}) (drill ${hole}) (layers *.Cu *.Mask))
)
`;
};

// ---- families whose geometry the NAME fully determines, same argument as the two-lead parts ----
// A pin count and a pitch pin down a header or a connector land completely; the only family
// constant is the hole size, which follows from the contact the series uses. Stated per family.
const HOLE = { PH: 0.8, HDR: 1.0, MicroFit: 1.1 };     // JST PH 0.8, 2.54 header 1.0, Micro-Fit 3.0

const row = (name, n, pitch, hole, dual, descr) => {
  const pd = Number((hole + 2 * ANNULAR).toFixed(2));
  const cols = dual ? Math.ceil(n / 2) : n;
  const x0 = -((cols - 1) * pitch) / 2;
  const rowY = dual ? pitch / 2 : 0;
  let pads = "";
  for (let i = 0; i < n; i++) {
    const c = dual ? Math.floor(i / 2) : i;
    const y = dual ? (i % 2 ? rowY : -rowY) : 0;
    const x = Number((x0 + c * pitch).toFixed(2));
    pads += `  (pad ${i + 1} thru_hole ${i === 0 ? "rect" : "circle"} (at ${x} ${y}) (size ${pd} ${pd}) (drill ${hole}) (layers *.Cu *.Mask))\n`;
  }
  const W = (cols - 1) * pitch + pitch, H = dual ? pitch * 2 : pitch * 1.6;
  return `(module ${name} (layer F.Cu) (tedit 0)
  (descr "${descr}: ${n} way${dual ? ", dual row" : ""}, ${pitch} mm pitch, ${hole} mm holes. Generated by calculations/footprint-gen.mjs.")
  (fp_text reference REF** (at 0 ${-(H / 2 + 1.2).toFixed(2)}) (layer F.SilkS) (effects (font (size 1 1) (thickness 0.15))))
  (fp_text value ${name} (at 0 ${(H / 2 + 1.2).toFixed(2)}) (layer F.Fab) (effects (font (size 1 1) (thickness 0.15))))
${rect(W, H)}
${rect(W + 1, H + 1, "F.CrtYd", 0.05)}
${pads})
`;
};

// Radial two-lead disc parts (MOV, gas discharge tube): body diameter and lead pitch are both in
// the name; leads are 0.8 mm on both families.
const disc = (name, dia, pitch, what) => {
  const hole = 1.1, pd = Number((hole + 2 * ANNULAR).toFixed(2)), x = Number((pitch / 2).toFixed(2));
  const c = Number((dia / 2 + 0.5).toFixed(2));
  return `(module ${name} (layer F.Cu) (tedit 0)
  (descr "${what}: ${dia} mm disc body, ${pitch} mm lead pitch, 0.8 mm leads, ${hole} mm holes. Generated by calculations/footprint-gen.mjs.")
  (fp_text reference REF** (at 0 ${-(dia / 2 + 1.2).toFixed(2)}) (layer F.SilkS) (effects (font (size 1 1) (thickness 0.15))))
  (fp_text value ${name} (at 0 ${(dia / 2 + 1.2).toFixed(2)}) (layer F.Fab) (effects (font (size 1 1) (thickness 0.15))))
  (fp_circle (center 0 0) (end ${dia / 2} 0) (layer F.SilkS) (width 0.15))
${rect(c * 2, c * 2, "F.CrtYd", 0.05)}
  (pad 1 thru_hole rect (at ${-x} 0) (size ${pd} ${pd}) (drill ${hole}) (layers *.Cu *.Mask))
  (pad 2 thru_hole circle (at ${x} 0) (size ${pd} ${pd}) (drill ${hole}) (layers *.Cu *.Mask))
)
`;
};

// ================= MAGNETICS — approximate envelopes from docs/magnetics.md =================
// Requested so the PCB can be laid out now against realistic outlines, with the real parts wound
// to that size later. Sizes are NOT invented: every core dimension below is quoted from the
// design's own magnetics drawings (D1/D2/D3/D4/D6/D7 and the CT section). What is approximate is
// only how the winding build and lead exits are modelled, and that is stated per family.
//
// APPROXIMATIONS, all deliberately generous so a real part cannot outgrow the land:
//   * winding build adds 2 x 4 mm to a toroid OD (single-layer foil/litz over the core)
//   * lead holes are sized from the conductor CSA: d = sqrt(4A/pi) + 1.2 mm clearance
//   * a wound toroid's start and end leads sit close together (>=300 deg spread), so both
//     terminals of a winding are placed at one angular position, not diametrically opposite
//   * courtyard is the finished OD + 2 mm
// Per-SKU rows are taken straight from the D6 and D7 tables; the footprint NAME is unchanged so
// the schematics do not move, and each SKU's file simply carries its own geometry.

const holeForCSA = (mm2) => Number((Math.sqrt(4 * mm2 / Math.PI) + 1.2).toFixed(1));

// toroid: OD/ID/H from the drawing, nWind windings each with 2 leads, optional centre bolt
const toroid = (name, { od, id, h, stack = 1, csa, nWind = 1, bolt = 0, what }) => {
  const OD = od + 8;                                   // + winding build, both sides
  const hole = holeForCSA(csa), pd = Number((hole + 2 * ANNULAR).toFixed(2));
  const rMid = Number(((od + id) / 4).toFixed(2));     // under the core ring
  const sp = Number((pd + 1.5).toFixed(2));            // lead-to-lead within one winding
  let pads = "", n = 0;
  for (let w = 0; w < nWind; w++) {
    const a = (2 * Math.PI * w) / nWind;
    for (const side of [-1, 1]) {
      n++;
      const x = Number((rMid * Math.cos(a) - side * (sp / 2) * Math.sin(a)).toFixed(2));
      const y = Number((rMid * Math.sin(a) + side * (sp / 2) * Math.cos(a)).toFixed(2));
      pads += `  (pad ${n} thru_hole ${n === 1 ? "rect" : "circle"} (at ${x} ${y}) (size ${pd} ${pd}) (drill ${hole}) (layers *.Cu *.Mask))\n`;
    }
  }
  const boltPad = bolt
    ? `  (pad 0 thru_hole circle (at 0 0) (size ${bolt + 3} ${bolt + 3}) (drill ${bolt + 0.4}) (layers *.Cu *.Mask))\n`
    : "";
  const c = Number((OD / 2 + 2).toFixed(2));
  return `(module ${name} (layer F.Cu) (tedit 0)
  (descr "${what} — APPROXIMATE envelope. Core ${stack > 1 ? stack + "x " : ""}OD${od}/ID${id}/H${h} mm per docs/magnetics.md; finished OD ${OD} mm incl. winding build, stack height ~${(stack * h + 6).toFixed(0)} mm. ${nWind} winding(s), ${csa} mm2 conductor -> ${hole} mm lead holes.${bolt ? ` Centre M${bolt} bolt.` : ""} Wind to this size. Generated by calculations/footprint-gen.mjs.")
  (fp_text reference REF** (at 0 ${-(OD / 2 + 3).toFixed(1)}) (layer F.SilkS) (effects (font (size 1.2 1.2) (thickness 0.2))))
  (fp_text value ${name} (at 0 ${(OD / 2 + 3).toFixed(1)}) (layer F.Fab) (effects (font (size 1.2 1.2) (thickness 0.2))))
  (fp_circle (center 0 0) (end ${(OD / 2).toFixed(2)} 0) (layer F.SilkS) (width 0.2))
  (fp_circle (center 0 0) (end ${(id / 2).toFixed(2)} 0) (layer F.SilkS) (width 0.15))
  (fp_circle (center 0 0) (end ${c} 0) (layer F.CrtYd) (width 0.05))
${boltPad}${pads})
`;
};

// cored transformer on a bobbin: body W x D, pins in two rows on `pitch`, M4 clamp holes
const bobbin = (name, { w, d, h, pins, pitch, csa, clamp = 0, what }) => {
  const hole = holeForCSA(csa), pd = Number((hole + 2 * ANNULAR).toFixed(2));
  const per = Math.ceil(pins / 2), x0 = -((per - 1) * pitch) / 2, ry = Number((d / 2 - 3).toFixed(2));
  let pads = "";
  for (let i = 0; i < pins; i++) {
    const col = Math.floor(i / 2), y = i % 2 ? ry : -ry;
    pads += `  (pad ${i + 1} thru_hole ${i === 0 ? "rect" : "circle"} (at ${(x0 + col * pitch).toFixed(2)} ${y}) (size ${pd} ${pd}) (drill ${hole}) (layers *.Cu *.Mask))\n`;
  }
  let clampPads = "";
  if (clamp) for (const [cx, cy] of [[-1, -1], [1, -1], [1, 1], [-1, 1]])
    clampPads += `  (pad 0 thru_hole circle (at ${(cx * (w / 2 + 4)).toFixed(1)} ${(cy * (d / 2 - 2)).toFixed(1)}) (size ${clamp + 3} ${clamp + 3}) (drill ${clamp + 0.4}) (layers *.Cu *.Mask))\n`;
  const CW = w + (clamp ? 16 : 4), CD = d + 4;
  return `(module ${name} (layer F.Cu) (tedit 0)
  (descr "${what} — APPROXIMATE envelope. Core ${w} x ${d} x ${h} mm per docs/magnetics.md, ${pins} terminations on ${pitch} mm pitch, ${csa} mm2 conductor -> ${hole} mm holes.${clamp ? ` 4x M${clamp} clamp-bar holes.` : ""} Wind to this size. Generated by calculations/footprint-gen.mjs.")
  (fp_text reference REF** (at 0 ${-(CD / 2 + 2.5).toFixed(1)}) (layer F.SilkS) (effects (font (size 1.2 1.2) (thickness 0.2))))
  (fp_text value ${name} (at 0 ${(CD / 2 + 2.5).toFixed(1)}) (layer F.Fab) (effects (font (size 1.2 1.2) (thickness 0.2))))
${rect(w, d)}
${rect(CW, CD, "F.CrtYd", 0.05)}
${clampPads}${pads})
`;
};

// Screw-terminal HV contactor (Hongfa HFE82V class). Dimensions from the manufacturer datasheet
// (source.hongfa.com HFE82V-200W): body 89.0 x 43.0, 2x M6 mounting holes on a 69 x 26.4 pattern,
// main contacts M6 screw terminals on 22 mm centres. The coil and auxiliary contacts do NOT come
// out on board pins — they leave on a flying harness connector — so pads 3..6 here are the land
// for that harness header, placed alongside the body rather than invented onto the relay.
const contactor = (name, { L, W, termPitch, bolt, mountX, mountY, amps, what }) => {
  const tp = bolt + 6, tx = Number((termPitch / 2).toFixed(1));
  const mx = Number((mountX / 2).toFixed(1)), my = Number((mountY / 2).toFixed(1));
  const hx = Number((L / 2 + 6).toFixed(1));
  // Pad NUMBERS must equal the symbol's pin numbers or EasyEDA refuses to bind the footprint
  // ("Pin has no corresponding pad"). Our relay symbol numbers its pins 1,3,4,5,6,8 (C1/M2/A/M1/
  // B/C2), which is our convention, not Hongfa's 1-2 / A1-A2 / C1-C2 labelling. Map by FUNCTION:
  //   4 = A  and 6 = B   -> the two M6 screw main terminals
  //   1 = C1 and 8 = C2  -> coil, on the flying harness
  //   5 = M1 and 3 = M2  -> auxiliary (mirror) contact, same harness
  let pads = `  (pad 4 thru_hole circle (at ${-tx} 0) (size ${tp} ${tp}) (drill ${bolt + 0.4}) (layers *.Cu *.Mask))\n`
           + `  (pad 6 thru_hole circle (at ${tx} 0) (size ${tp} ${tp}) (drill ${bolt + 0.4}) (layers *.Cu *.Mask))\n`;
  ["1", "8", "5", "3"].forEach((n, i) => {
    pads += `  (pad ${n} thru_hole ${i === 0 ? "rect" : "circle"} (at ${hx} ${(-3.81 + i * 2.54).toFixed(2)}) (size 1.9 1.9) (drill 1.0) (layers *.Cu *.Mask))\n`;
  });
  let mnt = "";
  for (const [sx, sy] of [[-1, -1], [1, 1]])
    mnt += `  (pad 0 thru_hole circle (at ${sx * mx} ${sy * my}) (size ${bolt + 3} ${bolt + 3}) (drill ${bolt + 0.1}) (layers *.Cu *.Mask))\n`;
  return `(module ${name} (layer F.Cu) (tedit 0)
  (descr "${what} — APPROXIMATE. Body ${L} x ${W} mm per the Hongfa HFE82V datasheet; ${amps} A main contacts on M${bolt} screw terminals at ${termPitch} mm centres; 2x M${bolt} mounting holes on ${mountX} x ${mountY}. Coil and AUXILIARY (mirror) contacts leave on a flying harness, so pads 3-6 are that harness header on 2.54 mm, NOT relay body pins. Generated by calculations/footprint-gen.mjs.")
  (fp_text reference REF** (at 0 ${-(W / 2 + 3).toFixed(1)}) (layer F.SilkS) (effects (font (size 1.2 1.2) (thickness 0.2))))
  (fp_text value ${name} (at 0 ${(W / 2 + 3).toFixed(1)}) (layer F.Fab) (effects (font (size 1.2 1.2) (thickness 0.2))))
${rect(L, W)}
${rect(L + 16, W + 4, "F.CrtYd", 0.05)}
${mnt}${pads})
`;
};

// PCB-mount power relay with an auxiliary (mirror) contact — Hongfa HF167F "HA" variant.
// Dimensions from the manufacturer datasheet PC BOARD LAYOUT page for the HA type: body 38 x 33,
// two main blade terminals on 20 mm centres, coil and auxiliary pins on the opposite edge.
// Pad NUMBERS follow the SYMBOL (1,3,4,5,6,8), mapped by function, not the datasheet's labels.
const pcbRelay = (name, { L, W, mainPitch, what }) => {
  const mx = Number((mainPitch / 2).toFixed(1));
  const bx = Number((L / 2 - 6).toFixed(1));
  const slot = `(size 4.2 2.4) (drill oval 3.2 1.4)`;
  return `(module ${name} (layer F.Cu) (tedit 0)
  (descr "${what} — APPROXIMATE, from the Hongfa HF167F datasheet PC board layout (HA type, with auxiliary contact). Body ${L} x ${W} mm; main blade terminals on ${mainPitch} mm centres; coil and auxiliary pins on the opposite edge. Pads numbered to the schematic symbol: 4/6 main, 1/8 coil, 5/3 auxiliary. Generated by calculations/footprint-gen.mjs.")
  (fp_text reference REF** (at 0 ${-(W / 2 + 2.5).toFixed(1)}) (layer F.SilkS) (effects (font (size 1.2 1.2) (thickness 0.2))))
  (fp_text value ${name} (at 0 ${(W / 2 + 2.5).toFixed(1)}) (layer F.Fab) (effects (font (size 1.2 1.2) (thickness 0.2))))
${rect(L, W)}
${rect(L + 3, W + 3, "F.CrtYd", 0.05)}
  (pad 4 thru_hole rect (at ${-mx} ${(W / 2 - 4).toFixed(1)}) ${slot} (layers *.Cu *.Mask))
  (pad 6 thru_hole oval (at ${mx} ${(W / 2 - 4).toFixed(1)}) ${slot} (layers *.Cu *.Mask))
  (pad 1 thru_hole circle (at ${bx} ${-(W / 2 - 5).toFixed(1)}) (size 2.6 2.6) (drill 1.6) (layers *.Cu *.Mask))
  (pad 8 thru_hole circle (at ${bx} ${-(W / 2 - 8.5).toFixed(1)}) (size 2.6 2.6) (drill 1.6) (layers *.Cu *.Mask))
  (pad 5 thru_hole circle (at ${-bx} ${-(W / 2 - 5).toFixed(1)}) (size 2.6 2.6) (drill 1.6) (layers *.Cu *.Mask))
  (pad 3 thru_hole circle (at ${-bx} ${-(W / 2 - 8.5).toFixed(1)}) (size 2.6 2.6) (drill 1.6) (layers *.Cu *.Mask))
)
`;
};

// 4-terminal SMD common-mode choke, EIA 1812. Land taken from TDK's own LAYOUT RECOMMENDATION
// for the ACT45B (act45b.pdf): outer span 5.9 mm, inner gap 3.2 mm, pad height 1.6 mm, outer
// row span 3.4 mm -> pads 1.35 x 1.6 on (+/-2.275, +/-0.9). Body 4.5 x 3.2 x 2.8.
// TDK numbers the pins 1 top-left, 2 bottom-left, 3 bottom-right, 4 top-right with the windings
// 1-4 and 2-3 — which is exactly how our symbol pairs A1/A2 and B1/B2, so the numbering maps 1:1.
const smdCMC = (name, { L, W, padW, padH, padX, padY, what }) => `(module ${name} (layer F.Cu) (tedit 0)
  (descr "${what} — land per TDK's layout recommendation for the ACT45B (EIA 1812). Body ${L} x ${W} mm; pads ${padW} x ${padH} mm at +/-${padX} / +/-${padY}. Windings 1-4 and 2-3, no polarity. Generated by calculations/footprint-gen.mjs.")
  (fp_text reference REF** (at 0 ${-(W / 2 + 1.4).toFixed(2)}) (layer F.SilkS) (effects (font (size 0.8 0.8) (thickness 0.12))))
  (fp_text value ${name} (at 0 ${(W / 2 + 1.4).toFixed(2)}) (layer F.Fab) (effects (font (size 0.8 0.8) (thickness 0.12))))
${rect(L, W)}
${rect(L + 1.2, W + 1.2, "F.CrtYd", 0.05)}
  (pad 1 smd rect (at ${-padX} ${-padY}) (size ${padW} ${padH}) (layers F.Cu F.Paste F.Mask))
  (pad 2 smd rect (at ${-padX} ${padY}) (size ${padW} ${padH}) (layers F.Cu F.Paste F.Mask))
  (pad 3 smd rect (at ${padX} ${padY}) (size ${padW} ${padH}) (layers F.Cu F.Paste F.Mask))
  (pad 4 smd rect (at ${padX} ${-padY}) (size ${padW} ${padH}) (layers F.Cu F.Paste F.Mask))
)
`;

// 4-terminal bolted manganin shunt: 2 current bolts + 2 Kelvin sense pads on the centreline.
// parts-db calls it "50 mV class (SKU current)" and architecture.md gives 100/200/400 A, so the
// element is 0.5 / 0.25 / 0.125 mOhm dissipating 5 / 10 / 20 W. Body scales with the dissipation.
const shunt = (name, { L, W, bolt, amps, mohm, watts }) => {
  const bp = bolt + 3, bx = Number((L / 2 - bolt).toFixed(1));
  const kx = Number((L / 4).toFixed(1));
  return `(module ${name} (layer F.Cu) (tedit 0)
  (descr "4-terminal manganin shunt, ${amps} A / ${mohm} mOhm / ~${watts} W (50 mV class per parts-db, SKU current per architecture.md) — APPROXIMATE envelope ${L} x ${W} mm, M${bolt} current bolts, Kelvin sense pads inboard. Make to this size. Generated by calculations/footprint-gen.mjs.")
  (fp_text reference REF** (at 0 ${-(W / 2 + 2.5).toFixed(1)}) (layer F.SilkS) (effects (font (size 1.2 1.2) (thickness 0.2))))
  (fp_text value ${name} (at 0 ${(W / 2 + 2.5).toFixed(1)}) (layer F.Fab) (effects (font (size 1.2 1.2) (thickness 0.2))))
${rect(L, W)}
${rect(L + 4, W + 4, "F.CrtYd", 0.05)}
  (pad 1 thru_hole rect (at ${-bx} 0) (size ${bp} ${bp}) (drill ${bolt + 0.4}) (layers *.Cu *.Mask))
  (pad 2 thru_hole circle (at ${bx} 0) (size ${bp} ${bp}) (drill ${bolt + 0.4}) (layers *.Cu *.Mask))
  (pad 3 thru_hole circle (at ${-kx} 0) (size 2.4 2.4) (drill 1.3) (layers *.Cu *.Mask))
  (pad 4 thru_hole circle (at ${kx} 0) (size 2.4 2.4) (drill 1.3) (layers *.Cu *.Mask))
)
`;
};

// Every row below is quoted from docs/magnetics.md. Where a drawing gives per-SKU cores (D6, D7)
// the SKU key carries its own row; everything else is common to all three SKUs.
const MAGNETICS = {
  // D1 rev B — PFC choke, 3x stacked 0077908A7-class sendust, centre M6 bolt, 18 mm2 Cu (audit F4)
  "L_Toroid_3xT79_26u_custom": { all: { kind: "toroid", od: 79, id: 48, h: 17, stack: 3, csa: 18, bolt: 6,
    what: "D1 rev B PFC choke 165 uH class, 3x stacked sendust toroid mu=26 (AL 37), N=39, 18 mm2 flat Cu" } },
  // D2 rev C — resonant trim inductor, GAPPED FERRITE 2x PQ50/50 stack, 2 litz flying leads
  // (audit F1: sendust at full 140 kHz AC swing = ~43 W core loss; powder prohibited in this slot).
  // Modeled as a 2-lead part with the PQ stack envelope; leads land in plated holes like a toroid.
  "L_Toroid_trim_bin_custom": { all: { kind: "toroid", od: 68, id: 40, h: 35, csa: 8.25, clampNote: "2x M4 clamp bar",
    what: "D2 rev C resonant trim bin set 3.3/3.65/4.0/4.35 uH, gapped 2x PQ50/50 (envelope 68x56)" } },
  // D6 — DM line chokes, per-SKU core and winding
  "L_Toroid_sendust_per-SKU": {
    "30kw":  { kind: "toroid", od: 47, id: 24, h: 18, csa: 9.9,  what: "D6 rev B DM line choke 22 uH, 26u sendust OD47x24x18, 14 T x 3xAWG12 (30 kW, 55 A — audit F7)" },
    "60kw":  { kind: "toroid", od: 57, id: 26, h: 20, csa: 20,  what: "D6 rev B DM line choke 22 uH, 26u sendust OD57x26x20, 11 T foil 0.5x40 (60 kW, 110 A — audit F7)" },
    "120kw": { kind: "toroid", od: 79, id: 40, h: 17, stack: 2, csa: 40, what: "D6 rev B DM line choke 22 uH, 26u sendust OD79x40x17 x2 stacked, 8 T foil 2x(0.5x40) (120 kW, 220 A — audit F7)" },
  },
  // D7 — 3-phase CM chokes, per-SKU core and winding; 3 windings x 2 leads
  "L_CMC_3ph_nanocryst_per-SKU": {
    "30kw":  { kind: "toroid", od: 62,  id: 32, h: 25, csa: 10, nWind: 3, what: "D7 3-ph CM choke >=2 mH, nanocrystalline OD62, 3x 8 T foil 0.3x33 (30 kW, 55 A)" },
    "60kw":  { kind: "toroid", od: 80,  id: 45, h: 30, csa: 25, nWind: 3, what: "D7 3-ph CM choke >=2 mH, nanocrystalline OD80, 3x 7 T foil 0.5x50 (60 kW, 110 A)" },
    "120kw": { kind: "toroid", od: 102, id: 60, h: 35, csa: 50, nWind: 3, what: "D7 3-ph CM choke >=2 mH, nanocrystalline OD102 (or 2x OD80 stacked), 3x 6 T foil/busbar (120 kW, 220 A)" },
  },
  // D3 — LLC section transformer, 3x PQ50/50 stacked, 4x M4 clamp bar, 7 terminations
  "XFMR_3xPQ50-50_custom": { all: { kind: "bobbin", w: 96, d: 50, h: 50, pins: 7, pitch: 10, csa: 10.4, clamp: 4,
    what: "D3 LLC section transformer 10 kW, 3x PQ50/50 stacked, Np/Ns1/Ns2 = 7/7/7, Lm 63 uH" } },
  // D4 rev C — aux flyback, ETD34 PC95, Np 38 / N24 6 / N15 4 / Naux 4 -> 8 terminations
  "XFMR_ETD39_custom": { all: { kind: "bobbin", w: 42, d: 30, h: 30, pins: 8, pitch: 5.08, csa: 0.8,
    what: "D4 rev D aux flyback transformer, ETD39 PC95, 110 W class, Np 38 / N24 6 / N15 4 / Naux 4 (E52 margin rev — Bpk 0.233 T)" } },
  // CTs — line CT needs a >=9 mm busbar window; resonant CT is a 10 mm toroid in series with the tank
  "CT_window_100A_1-2500": { all: { kind: "toroid", od: 42, id: 14.6, h: 25, csa: 0.5, pins4: true,
    what: "Line CT: Talema ACX-1100 catalog (2500:1, 100 A, dia-14.6 window), 27 R burden — audit/R3; land per Talema drawing at layout" } },
  "CT_window_res_1-100": { all: { kind: "toroid", od: 16, id: 10, h: 8, csa: 0.5,
    what: "Resonant CT 1:100 on a 10 mm toroid, in series with the tank, 2.0 R burden" } },
  // CAN common-mode choke — TDK ACT45B-510-2P-TL003 (51 uH, 200 mA, EIA 1812)
  "IND-SMD_L4.5-W3.2_CMC": { all: { kind: "smdCMC", L: 4.5, W: 3.2, padW: 1.35, padH: 1.6, padX: 2.275, padY: 0.9,
    what: "TDK ACT45B-510-2P-TL003, CAN common-mode choke 51 uH / 200 mA / 50 V, AEC-Q200" } },
  // Precharge-bypass relays — Hongfa HF167F "HA" (auxiliary contact) type, PCB mount
  "RELAY_HF167F_PCB": { all: { kind: "pcbRelay", L: 38, W: 33, mainPitch: 20,
    what: "HF167F/024-HATF(764): 24 V coil, 1 Form A main (carry 100 A, break 30 A @1000 VAC) + 1 Form A AUXILIARY for weld detection" } },
  // HV bank/output relays — Hongfa HFE82V class with the auxiliary (mirror) contact, rating by SKU
  "RELAY_HFE82V_PCB": {
    "30kw":  { kind: "contactor", L: 89, W: 43, termPitch: 22, bolt: 6, mountX: 69, mountY: 26.4, amps: 200, what: "HFE82V-200W/1000-24-HA-C5-1, 1 Form A + 1 Form A auxiliary" },
    "60kw":  { kind: "contactor", L: 89, W: 43, termPitch: 22, bolt: 6, mountX: 69, mountY: 26.4, amps: 250, what: "HFE82V-250C/1000-24-HA-C5-1, 1 Form A + 1 Form A auxiliary" },
    "120kw": { kind: "contactor", L: 96, W: 48, termPitch: 26, bolt: 8, mountX: 76, mountY: 30.0, amps: 400, what: "HFE82V-400M/1000-24-HA-C5-1, 1 Form A + 1 Form A auxiliary (larger frame at 400 A)" },
  },
  // output shunt, 50 mV class at the SKU current (architecture.md: 100 / 200 / 400 A)
  "SHUNT_4-terminal_manganin": {
    "30kw":  { kind: "shunt", L: 40, W: 15, bolt: 5, amps: 100, mohm: 0.5,   watts: 5 },
    "60kw":  { kind: "shunt", L: 55, W: 20, bolt: 6, amps: 200, mohm: 0.25,  watts: 10 },
    "120kw": { kind: "shunt", L: 75, W: 25, bolt: 8, amps: 400, mohm: 0.125, watts: 20 },
  },
};

// Which names to generate: read them straight off the emitted sheets so this can never drift
// from what the schematic actually asks for.
const wanted = new Set();
for (const dir of readdirSync(join(ROOT, "kicad5")).filter((d) => d.startsWith("dc-modules-"))) {
  for (const f of readdirSync(join(ROOT, "kicad5", dir)).filter((x) => /^\d.*\.sch$/.test(x))) {
    for (const blk of readFileSync(join(ROOT, "kicad5", dir, f), "utf8").split("$Comp").slice(1)) {
      const m = blk.match(/^F 2 "([^"]+)"/m);
      if (m) wanted.add(m[1]);
    }
  }
}

let n = 0;
const made = [];
// magnetics first: same footprint NAME on every SKU, but the geometry follows that SKU's drawing,
// so the schematics never move while the land matches the part that will actually be wound.
import { mkdirSync as _mk } from "node:fs";
for (const sku of ["30kw", "60kw", "120kw"]) {
  const dir = join(OUT, sku);
  _mk(dir, { recursive: true });
  for (const [name, rows] of Object.entries(MAGNETICS)) {
    const spec = rows.all ?? rows[sku];
    if (!spec) continue;
    const body = spec.kind === "toroid" ? toroid(name, spec)
      : spec.kind === "shunt" ? shunt(name, spec)
      : spec.kind === "contactor" ? contactor(name, spec)
      : spec.kind === "pcbRelay" ? pcbRelay(name, spec)
      : spec.kind === "smdCMC" ? smdCMC(name, spec) : bobbin(name, spec);
    writeFileSync(join(dir, `${name}.kicad_mod`), body);
  }
}
console.log(`magnetics: ${Object.keys(MAGNETICS).length} footprints x 3 SKUs -> kicad5/footprints/<sku>/`);
for (const name of [...wanted].sort()) {
  const tl = name.match(/^(CAP|RES)-TH_L([\d.]+)-W([\d.]+)-P([\d.]+)$/);
  if (tl) {
    writeFileSync(join(OUT, `${name}.kicad_mod`), twoLead(name, tl[1], +tl[2], +tl[3], +tl[4]));
    made.push(name); n++; continue;
  }
  if (name === "TERM_Stud_M8") { writeFileSync(join(OUT, `${name}.kicad_mod`), stud(name, 8, 14)); made.push(name); n++; continue; }
  if (name === "TERM_Tab_M4") { writeFileSync(join(OUT, `${name}.kicad_mod`), stud(name, 4, 8)); made.push(name); n++; continue; }
  const ph = name.match(/^CONN-TH_(\d+)P-P([\d.]+)_PH$/);
  if (ph) { writeFileSync(join(OUT, `${name}.kicad_mod`), row(name, +ph[1], +ph[2], HOLE.PH, false, "JST PH-series wire-to-board header")); made.push(name); n++; continue; }
  const mf = name.match(/^CONN-TH_(\d+)P-P([\d.]+)_MicroFit$/);
  if (mf) { writeFileSync(join(OUT, `${name}.kicad_mod`), row(name, +mf[1], +mf[2], HOLE.MicroFit, true, "Molex Micro-Fit 3.0 header")); made.push(name); n++; continue; }
  const hd = name.match(/^HDR-TH_(\d+)P-P([\d.]+)-V-M$/);
  if (hd) { writeFileSync(join(OUT, `${name}.kicad_mod`), row(name, +hd[1], +hd[2], HOLE.HDR, false, "Vertical male pin header")); made.push(name); n++; continue; }
  const ds = name.match(/^DISC-(\d+)mm_RM(\d+)$/);
  if (ds) { writeFileSync(join(OUT, `${name}.kicad_mod`), disc(name, +ds[1], +ds[2], "Radial disc MOV")); made.push(name); n++; continue; }
  const gd = name.match(/^GDT-(\d+)mm_RM(\d+)$/);
  if (gd) { writeFileSync(join(OUT, `${name}.kicad_mod`), disc(name, +gd[1], +gd[2], "Gas discharge tube")); made.push(name); n++; continue; }
}
console.log(`${n} footprints written to kicad5/footprints/`);
made.forEach((m) => console.log(`   ${m}`));
