#!/usr/bin/env node
// footprint-gen.mjs — author the through-hole land patterns whose geometry is fully determined
// by the dimensions already encoded in the footprint name, and emit them as KiCad .kicad_mod
// files (standard KiCad footprint format).
//
// WHY THIS IS NOT INVENTED DATA. A name like CAP-TH_L26.5-W11.0-P22.50 already carries the
// part's body length, body width and lead pitch from its datasheet. The land pattern follows:
// two pads on the lead pitch, hole sized to the lead, annular ring per IPC, silkscreen the body
// outline. The ONE thing not in the name is the lead diameter, so it is stated explicitly per
// family below and is the single number to correct if a datasheet disagrees.
//
// Deliberately NOT generated here: wound magnetics, current transformers and the manganin shunt.
// Those have no standard land — their pad geometry comes from the winder's/maker's drawing, and
// guessing it would be fabricating manufacturing data. They stay as placeholders.
//
// Run: node calculations/footprint-gen.mjs  ->  kicad5/footprints/*.kicad_mod

import { writeFileSync, mkdirSync, readdirSync, readFileSync, unlinkSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "kicad5/footprints");
mkdirSync(OUT, { recursive: true });

// Lead diameter by family, in mm. The only assumed number in this file.
//   film/box caps on a wide pitch use 0.8 mm leads; small film 0.6 mm;
//   axial power resistors (48-60 mm bodies, 10-25 W) use 1.0 mm.
const LEAD = (kind, pitch) => (kind === "RES" ? 1.0 : pitch > 10 ? 0.8 : 0.6);

const HOLE_CLEAR = 0.3;     // hole = lead + 0.3 mm  (IPC-2222 class 2, plated)
const ANNULAR = 0.45;       // pad  = hole + 2 x 0.45 mm

const pad = (n, x, hole) => {
  const d = Number((hole + 2 * ANNULAR).toFixed(2));
  const shape = n === 1 ? "rect" : "circle";     // pin 1 square, the usual convention
  return `  (pad ${n} thru_hole ${shape} (at ${x} 0) (size ${d} ${d}) (drill ${hole}) (layers *.Cu *.Mask))`;
};

const line = (x1, y1, x2, y2, layer = "F.SilkS", w = 0.15) =>
  `  (fp_line (start ${x1} ${y1}) (end ${x2} ${y2}) (layer ${layer}) (width ${w}))`;

const rect = (L, W, layer = "F.SilkS", w = 0.15) => {
  const x = Number((L / 2).toFixed(2)), y = Number((W / 2).toFixed(2));
  return [line(-x, -y, x, -y, layer, w), line(x, -y, x, y, layer, w),
          line(x, y, -x, y, layer, w), line(-x, y, -x, -y, layer, w)].join("\n");
};

const twoLead = (name, kind, L, W, P) => {
  const lead = LEAD(kind, P);
  const hole = Number((lead + HOLE_CLEAR).toFixed(2));
  const x = Number((P / 2).toFixed(2));
  const body = rect(L, W);
  // courtyard 0.5 mm outside the greater of body and lead span
  const cx = Number((Math.max(L, P + hole + 2 * ANNULAR) / 2 + 0.5).toFixed(2));
  const cy = Number((W / 2 + 0.5).toFixed(2));
  return `(module ${name} (layer F.Cu) (tedit 0)
  (descr "${kind === "RES" ? "Axial through-hole resistor" : "Through-hole capacitor"} body ${L} x ${W} mm, lead pitch ${P} mm, lead dia ${lead} mm (assumed), hole ${hole} mm. Generated by calculations/footprint-gen.mjs.")
  (fp_text reference REF** (at 0 ${-(W / 2 + 1.2).toFixed(2)}) (layer F.SilkS) (effects (font (size 1 1) (thickness 0.15))))
  (fp_text value ${name} (at 0 ${(W / 2 + 1.2).toFixed(2)}) (layer F.Fab) (effects (font (size 1 1) (thickness 0.15))))
${body}
${/* lead stubs only where the pads sit OUTSIDE the body, i.e. axial parts. On a radial box cap
      the pitch is shorter than the body and the leads exit underneath, so there is nothing to draw. */
  x > L / 2 ? line(-x, 0, -Number((L / 2).toFixed(2)), 0) + "\n" + line(x, 0, Number((L / 2).toFixed(2)), 0) : ""}
${rect(cx * 2, cy * 2, "F.CrtYd", 0.05)}
${pad(1, -x, hole)}
${pad(2, x, hole)}
)
`;
};

// M8 bolted stud / M4 tab: a single large plated hole with a ring pad, sized to the thread.
const stud = (name, thread, padDia) => {
  const hole = Number((thread + 0.4).toFixed(2));
  const c = Number((padDia / 2 + 0.5).toFixed(2));
  return `(module ${name} (layer F.Cu) (tedit 0)
  (descr "M${thread} bolted power stud land: ${hole} mm plated hole, ${padDia} mm ring pad. Torque/washer stack per the mechanical drawing. Generated by calculations/footprint-gen.mjs.")
  (fp_text reference REF** (at 0 ${-c - 1}) (layer F.SilkS) (effects (font (size 1 1) (thickness 0.15))))
  (fp_text value ${name} (at 0 ${c + 1}) (layer F.Fab) (effects (font (size 1 1) (thickness 0.15))))
  (fp_circle (center 0 0) (end ${padDia / 2 + 0.3} 0) (layer F.SilkS) (width 0.15))
${rect(c * 2, c * 2, "F.CrtYd", 0.05)}
  (pad 1 thru_hole circle (at 0 0) (size ${padDia} ${padDia}) (drill ${hole}) (layers *.Cu *.Mask))
)
`;
};

// ---- families whose geometry the NAME fully determines, same argument as the two-lead parts ----
// A pin count and a pitch pin down a header or a connector land completely; the only family
// constant is the hole size, which follows from the contact the series uses. Stated per family.
const HOLE = { PH: 0.8, HDR: 1.0, MicroFit: 1.1 };     // JST PH 0.8, 2.54 header 1.0, Micro-Fit 3.0

const row = (name, n, pitch, hole, dual, descr) => {
  const pd = Number((hole + 2 * ANNULAR).toFixed(2));
  const cols = dual ? Math.ceil(n / 2) : n;
  const x0 = -((cols - 1) * pitch) / 2;
  const rowY = dual ? pitch / 2 : 0;
  let pads = "";
  for (let i = 0; i < n; i++) {
    const c = dual ? Math.floor(i / 2) : i;
    const y = dual ? (i % 2 ? rowY : -rowY) : 0;
    const x = Number((x0 + c * pitch).toFixed(2));
    pads += `  (pad ${i + 1} thru_hole ${i === 0 ? "rect" : "circle"} (at ${x} ${y}) (size ${pd} ${pd}) (drill ${hole}) (layers *.Cu *.Mask))\n`;
  }
  const W = (cols - 1) * pitch + pitch, H = dual ? pitch * 2 : pitch * 1.6;
  return `(module ${name} (layer F.Cu) (tedit 0)
  (descr "${descr}: ${n} way${dual ? ", dual row" : ""}, ${pitch} mm pitch, ${hole} mm holes. Generated by calculations/footprint-gen.mjs.")
  (fp_text reference REF** (at 0 ${-(H / 2 + 1.2).toFixed(2)}) (layer F.SilkS) (effects (font (size 1 1) (thickness 0.15))))
  (fp_text value ${name} (at 0 ${(H / 2 + 1.2).toFixed(2)}) (layer F.Fab) (effects (font (size 1 1) (thickness 0.15))))
${rect(W, H)}
${rect(W + 1, H + 1, "F.CrtYd", 0.05)}
${pads})
`;
};

// Radial two-lead disc parts (MOV, gas discharge tube): body diameter and lead pitch are both in
// the name; leads are 0.8 mm on both families.
const disc = (name, dia, pitch, what) => {
  const hole = 1.1, pd = Number((hole + 2 * ANNULAR).toFixed(2)), x = Number((pitch / 2).toFixed(2));
  const c = Number((dia / 2 + 0.5).toFixed(2));
  return `(module ${name} (layer F.Cu) (tedit 0)
  (descr "${what}: ${dia} mm disc body, ${pitch} mm lead pitch, 0.8 mm leads, ${hole} mm holes. Generated by calculations/footprint-gen.mjs.")
  (fp_text reference REF** (at 0 ${-(dia / 2 + 1.2).toFixed(2)}) (layer F.SilkS) (effects (font (size 1 1) (thickness 0.15))))
  (fp_text value ${name} (at 0 ${(dia / 2 + 1.2).toFixed(2)}) (layer F.Fab) (effects (font (size 1 1) (thickness 0.15))))
  (fp_circle (center 0 0) (end ${dia / 2} 0) (layer F.SilkS) (width 0.15))
${rect(c * 2, c * 2, "F.CrtYd", 0.05)}
  (pad 1 thru_hole rect (at ${-x} 0) (size ${pd} ${pd}) (drill ${hole}) (layers *.Cu *.Mask))
  (pad 2 thru_hole circle (at ${x} 0) (size ${pd} ${pd}) (drill ${hole}) (layers *.Cu *.Mask))
)
`;
};

// Which names to generate: read them straight off the emitted sheets so this can never drift
// from what the schematic actually asks for.
const wanted = new Set();
for (const dir of readdirSync(join(ROOT, "kicad5")).filter((d) => d.startsWith("dc-modules-"))) {
  for (const f of readdirSync(join(ROOT, "kicad5", dir)).filter((x) => x.endsWith(".sch") && !x.startsWith("dc-modules-"))) {   // every drawn sheet incl. the control card; the project root sheet holds no parts
    for (const blk of readFileSync(join(ROOT, "kicad5", dir, f), "utf8").split("$Comp").slice(1)) {
      const m = blk.match(/^F 2 "([^"]+)"/m);
      if (m) wanted.add(m[1]);
    }
  }
}

let n = 0;
const made = [];
for (const name of [...wanted].sort()) {
  const tl = name.match(/^(CAP|RES)-TH_L([\d.]+)-W([\d.]+)-P([\d.]+)$/);
  if (tl) {
    writeFileSync(join(OUT, `${name}.kicad_mod`), twoLead(name, tl[1], +tl[2], +tl[3], +tl[4]));
    made.push(name); n++; continue;
  }
  if (name === "TERM_Stud_M8") { writeFileSync(join(OUT, `${name}.kicad_mod`), stud(name, 8, 14)); made.push(name); n++; continue; }
  if (name === "TERM_Tab_M4") { writeFileSync(join(OUT, `${name}.kicad_mod`), stud(name, 4, 8)); made.push(name); n++; continue; }
  const ph = name.match(/^CONN-TH_(\d+)P-P([\d.]+)_PH$/);
  if (ph) { writeFileSync(join(OUT, `${name}.kicad_mod`), row(name, +ph[1], +ph[2], HOLE.PH, false, "JST PH-series wire-to-board header")); made.push(name); n++; continue; }
  const mf = name.match(/^CONN-TH_(\d+)P-P([\d.]+)_MicroFit$/);
  if (mf) { writeFileSync(join(OUT, `${name}.kicad_mod`), row(name, +mf[1], +mf[2], HOLE.MicroFit, true, "Molex Micro-Fit 3.0 header")); made.push(name); n++; continue; }
  const hd = name.match(/^HDR-TH_(\d+)P-P([\d.]+)-V-M$/);
  if (hd) { writeFileSync(join(OUT, `${name}.kicad_mod`), row(name, +hd[1], +hd[2], HOLE.HDR, false, "Vertical male pin header")); made.push(name); n++; continue; }
  const hd2 = name.match(/^HDR-TH_(\d+)P-2R-P([\d.]+)-V-M$/);   // dual-row (2×n/2) keyed header — the 88-way card slot
  if (hd2) { writeFileSync(join(OUT, `${name}.kicad_mod`), row(name, +hd2[1], +hd2[2], HOLE.HDR, true, "Vertical dual-row male pin header, keyed")); made.push(name); n++; continue; }
  const ds = name.match(/^DISC-(\d+)mm_RM(\d+)$/);
  if (ds) { writeFileSync(join(OUT, `${name}.kicad_mod`), disc(name, +ds[1], +ds[2], "Radial disc MOV")); made.push(name); n++; continue; }
  const gd = name.match(/^GDT-(\d+)mm_RM(\d+)$/);
  if (gd) { writeFileSync(join(OUT, `${name}.kicad_mod`), disc(name, +gd[1], +gd[2], "Gas discharge tube")); made.push(name); n++; continue; }
}
// a land no sheet asks for any more is deleted, so the library holds exactly what the sheets use
for (const f of readdirSync(OUT).filter((x) => x.endsWith(".kicad_mod") && !made.includes(x.slice(0, -10)))) { unlinkSync(join(OUT, f)); console.log(`   removed unused ${f}`); }
console.log(`${n} footprints written to kicad5/footprints/`);
made.forEach((m) => console.log(`   ${m}`));
